Repository HyphaApp/hypha, pull requests merged in 2019-11, with the labels that each got.

#1406 Add Debug Toolbar to Dev
  .circleci/config.yml
  .travis.yml
  opentech/settings/dev.py
  opentech/settings/local.py.example
  opentech/urls.py
  requirements-dev.txt
  requirements.txt
  vagrant/provision.sh
Labels: RTBC, maintenance

#1628 Reduce DB queries for Table data
  opentech/apply/funds/models/submissions.py
Labels: RTBC, enhancement

#1653 Remove get_field_kwargs() in ImageFieldBlock. We do not need this whe…
  opentech/apply/stream_forms/blocks.py
Labels: RTBC, enhancement

#1636 Fix the creation of files under the submission's revision path
  opentech/apply/funds/files.py
  opentech/apply/funds/models/submissions.py
  opentech/apply/funds/tests/test_models.py
Labels: RTBC, bug

#1642 Allow staff to see 16 reviewers in the reviewers field, before only f…
  opentech/apply/funds/models/applications.py
Labels: RTBC, enhancement

#1648 Remove the global activity feed. No one is using it so lets save some…
  opentech/apply/activity/views.py
  opentech/apply/funds/templates/funds/includes/activity-feed.html
  opentech/apply/funds/templates/funds/submissions.html
  opentech/apply/funds/templates/funds/submissions_by_round.html
  opentech/apply/funds/templates/funds/submissions_overview.html
  opentech/apply/funds/views.py
  opentech/static_src/src/javascript/apply/activity-feed.js
  opentech/static_src/src/sass/apply/components/_activity-feed.scss
  opentech/static_src/src/sass/apply/main.scss
Labels: RTBC, enhancement

#1684 Set postgres version to 10.10 in CI as it is on production.
  .circleci/config.yml
  .travis.yml
Labels: RTBC, maintenance

#1685 Add index on source_object_id for 10x performance improvment on orderBy
  opentech/apply/activity/migrations/0049_auto_20191112_1227.py
  opentech/apply/activity/models.py
Labels: RTBC, enhancement

#1675 Set TIME_ZONE to UTC to avoid summertime.
  opentech/settings/base.py
Labels: RTBC, enhancement

#1673 Fix to Automatic workflow actions after creating seperate view for re…
  opentech/apply/review/views.py
Labels: RTBC, bug

#1600 Make big tables and long links etc fit within the layout
  opentech/static_src/src/javascript/apply/submission-text-cleanup.js
  opentech/static_src/src/sass/apply/abstracts/_variables.scss
  opentech/static_src/src/sass/apply/components/_feed.scss
  opentech/static_src/src/sass/apply/components/_rich-text.scss
Labels: RTBC, bug

#1689 Admin: Create copy button in Application form
  opentech/apply/funds/admin.py
  opentech/apply/funds/admin_helpers.py
  opentech/apply/funds/admin_views.py
Labels: RTBC

#1631 Add flag feature to allow staff as well as each users to flag submiss…
  opentech/apply/dashboard/templates/dashboard/dashboard.html
  opentech/apply/dashboard/templates/dashboard/includes/flagged.html
  opentech/apply/dashboard/views.py
  opentech/apply/flags/__init__.py
  opentech/apply/flags/migrations/0001_initial.py
  opentech/apply/flags/migrations/__init__.py
  opentech/apply/flags/models.py
  opentech/apply/flags/templates/flags/flags.html
  opentech/apply/flags/templatetags/__init__.py
  opentech/apply/flags/templatetags/flag_tags.py
  opentech/apply/flags/urls.py
  opentech/apply/flags/views.py
  opentech/apply/funds/models/submissions.py
  opentech/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  opentech/apply/funds/templates/funds/applicationsubmission_community_detail.html
  opentech/apply/funds/templates/funds/applicationsubmission_detail.html
  opentech/apply/funds/templates/funds/applicationsubmission_partner_detail.html
  opentech/apply/funds/templates/funds/applicationsubmission_reviewer_detail.html
  opentech/apply/funds/templates/funds/base_submissions_table.html
  opentech/apply/funds/templates/funds/submissions_overview.html
  opentech/apply/funds/templates/funds/submissions_staff_flagged.html
  opentech/apply/funds/templates/funds/submissions_user_flagged.html
  opentech/apply/funds/urls.py
  opentech/apply/funds/views.py
  opentech/settings/base.py
  opentech/static_src/src/javascript/apply/flag.js
  opentech/static_src/src/javascript/js.cookie.min.js
  opentech/static_src/src/javascript/main.js
  opentech/static_src/src/sass/apply/abstracts/_mixins.scss
  opentech/static_src/src/sass/apply/components/_button.scss
  opentech/templates/base-apply.html
Labels: RTBC, feature

#1702 Add a open/closed filter to the round admin page in wagtail admin.
  opentech/apply/funds/admin.py
  opentech/apply/funds/admin_helpers.py
Labels: RTBC, enhancement
