Repository HyphaApp/hypha, pull requests merged in 2019-10, with the labels that each got.

#1482 Add Stats Blocks to Staff Dashboard
  opentech/apply/dashboard/templates/dashboard/dashboard.html
  opentech/apply/dashboard/tests/test_views.py
  opentech/apply/dashboard/views.py
Labels: Sprint 3 🏃

#1489 Projects to Approve
  opentech/apply/dashboard/templates/dashboard/dashboard.html
  opentech/apply/dashboard/tests/test_views.py
  opentech/apply/dashboard/views.py
  opentech/apply/projects/models.py
  opentech/apply/projects/views/project.py
Labels: Sprint 3 🏃

#1513 allow for multiple filters on one page
  opentech/apply/funds/templates/funds/includes/table_filter_and_search.html
  opentech/static_src/src/javascript/apply/submission-filters.js
  opentech/static_src/src/sass/apply/components/_filters.scss
Labels: Sprint 3 🏃

#1296 API Key to access some endpoints
  opentech/apply/funds/api_views.py
  opentech/settings/base.py
  requirements.txt
Labels: RTBC

#1521 Set COOKIE_SECURE to true in env var to set session and CSRF cookies …
  opentech/settings/base.py
  opentech/settings/local.py.example
Labels: RTBC

#1566 Move main.js that sets js class on html tag to header so it loads bef…
  opentech/templates/base-apply.html
  opentech/templates/base.html
Labels: RTBC

#1530 Add a help link field to all stream fields.
  opentech/apply/funds/migrations/0068_add_help_link_field.py
  opentech/apply/review/migrations/0021_add_help_link_field.py
  opentech/apply/stream_forms/blocks.py
  opentech/apply/stream_forms/models.py
  opentech/apply/templates/forms/includes/field.html
  opentech/static_src/src/sass/apply/components/_form.scss
  opentech/static_src/src/sass/public/components/_form.scss
Labels: RTBC

#1592 Fix: New file versions created on status update, adding partner forms
  opentech/apply/funds/forms.py
  opentech/apply/funds/models/submissions.py
Labels: RTBC, bug

#1584 Rename more_info choice for determinations.
  opentech/apply/determinations/migrations/0008_rename_more_info.py
  opentech/apply/determinations/models.py
Labels: RTBC

#1583 Add revert from proposal_determination to post_proposal_review_discussion
  opentech/apply/funds/workflow.py
Labels: RTBC, enhancement

#1577 Adds logo and newsletter wagtail admin settings
  opentech/public/mailchimp/migrations/0001_add_newsletter_setting.py
  opentech/public/mailchimp/models.py
  opentech/public/mailchimp/templates/mailchimp/newsletter_signup.html
  opentech/public/utils/context_processors.py
  opentech/public/utils/migrations/0003_add_site_logo_setting.py
  opentech/public/utils/models.py
  opentech/templates/base.html
Labels: RTBC, enhancement

#1580 Make the production settings work on more enviroments than Heroku.
  opentech/settings/production.py
Labels: RTBC

#1301 Rename meta categories to meta terms, Archive terms and other options
  opentech/apply/categories/admin.py
  opentech/apply/categories/admin_helpers.py
  opentech/apply/categories/admin_views.py
  opentech/apply/categories/migrations/0003_rename_meta_categories_to_meta_terms.py
  opentech/apply/categories/migrations/0004_rename_meta_categories_to_meta_terms.py
  opentech/apply/categories/migrations/0005_alter_is_archived_field_on_terms.py
  opentech/apply/categories/models.py
  opentech/apply/categories/templates/categories/admin/includes/meta_term_list_header.html
  opentech/apply/funds/admin.py
  opentech/apply/funds/forms.py
  opentech/apply/funds/migrations/0070_rename_meta_categories_to_meta_terms.py
  opentech/apply/funds/models/submissions.py
  opentech/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  opentech/apply/funds/templates/funds/applicationsubmission_detail.html
  opentech/apply/funds/templates/funds/includes/actions.html
  opentech/apply/funds/templates/funds/includes/meta_categories_block.html
  opentech/apply/funds/templates/funds/includes/meta_terms_block.html
  opentech/apply/funds/templates/funds/includes/update_meta_categories_form.html
  opentech/apply/funds/templates/funds/includes/update_meta_terms_form.html
  opentech/apply/funds/views.py
  opentech/apply/funds/widgets.py
  opentech/apply/projects/templates/application_projects/project_admin_detail.html
Labels: RTBC, enhancement

#1526 Added export submission command.
  opentech/apply/funds/management/commands/export_submissions_csv.py
Labels: feature

#1605 Expose project urls even when projects are not enabled. Otherwise the…
  opentech/apply/projects/urls.py
Labels: RTBC

#1606 Lint fixes following up on sprint 3.
  opentech/static_src/src/javascript/apply/submission-filters.js
  opentech/static_src/src/sass/apply/components/_payment-block.scss
Labels: bug

#1613 Reduce DB queries for Activity
  opentech/apply/activity/views.py
Labels: RTBC, enhancement

#1612 Make the top boxes on the dashbord take up less space.
  opentech/static_src/src/sass/apply/components/_stat-block.scss
Labels: RTBC, enhancement
