Repository HyphaApp/hypha, pull requests merged in 2020-09, with the labels that each got.

#2120 Updated to Django 2.2.16.
  requirements.txt
Labels: maintenance

#2125 Fix word count script error.
  hypha/static_src/src/javascript/apply/tinymce-word-count.js
Labels: bug

#2129 Node package updates.
  package-lock.json
Labels: maintenance

#2131 Cookie consent feature
  hypha/cookieconsent/__init__.py
  hypha/cookieconsent/apps.py
  hypha/cookieconsent/context_processors.py
  hypha/cookieconsent/migrations/0001_initial.py
  hypha/cookieconsent/migrations/__init__.py
  hypha/cookieconsent/models.py
  hypha/cookieconsent/static/js/cookieconsent.js
  hypha/cookieconsent/templates/includes/banner.html
  hypha/cookieconsent/templatetags/cookieconsent_tags.py
  hypha/settings/base.py
  hypha/static_src/src/sass/apply/components/_button.scss
  hypha/static_src/src/sass/apply/components/_wrapper.scss
  hypha/static_src/src/sass/public/components/_wrapper.scss
  hypha/templates/base-apply.html
  hypha/templates/base.html
Labels: feature

#2116 Use reviewer settings to give submission access to reviewers
  hypha/apply/funds/migrations/0079_add_reviewer_settings_for_submission_access.py
  hypha/apply/funds/models/__init__.py
  hypha/apply/funds/models/reviewer_role.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/views.py
  hypha/apply/funds/workflow.py
Labels: enhancement

#2134 Moving cookie consent to bottom. Improving look and feel.
  hypha/cookieconsent/static/js/cookieconsent.js
  hypha/cookieconsent/templates/includes/banner.html
  hypha/static_src/src/sass/apply/components/_button.scss
  hypha/static_src/src/sass/apply/components/_cookieconsent.scss
  hypha/static_src/src/sass/apply/components/_wrapper.scss
  hypha/static_src/src/sass/apply/main.scss
  hypha/static_src/src/sass/public/components/_button.scss
  hypha/static_src/src/sass/public/components/_cookieconsent.scss
  hypha/static_src/src/sass/public/components/_wrapper.scss
  hypha/static_src/src/sass/public/main.scss
  hypha/templates/base-apply.html
  hypha/templates/base.html
Labels: enhancement
