Repository HyphaApp/hypha, pull requests merged in 2020-03, with the labels that each got.

#1840 Update Django to 2.2.11.
  requirements.txt
Labels: maintenance

#1843 Revert: Allow staff reviewers to be deleted.
  hypha/apply/funds/forms.py
Labels: bug

#1845 Requested Funding value should be positive
  hypha/apply/funds/blocks.py
Labels: enhancement

#1834 Make it possible to filter comment notifications based on type.
  hypha/apply/activity/messaging.py
  hypha/settings/base.py
Labels: enhancement

#1859 Only add root url to local social images not to S3 hosted ones
  hypha/templates/base.html
Labels: bug

#1848 Always allow user to upload supporting documents to projects, not onl…
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
Labels: enhancement

#1860 Activate browser_spellcheck in TinyMCE editor.
  hypha/apply/utils/options.py
Labels: enhancement

#1861 Updated node packages.
  package-lock.json
Labels: maintenance

#1864 Fixed typos that was causing errors in react notes editor
  hypha/apply/activity/models.py
  hypha/apply/api/v1/views.py
Labels: bug

#1867 Correct the datetime template placeholder to ISO standard date format.
  hypha/templates/django/forms/widgets/datetime.html
Labels: bug

#1306 Add a account clenup command.
  hypha/apply/users/management/commands/accounts_cleanup.py
Labels: enhancement

#1868 Better options for default time and date formats.
  hypha/settings/base.py
Labels: enhancement

#1886 Make sure js-hidden is added to field groups with multiple fields.
  hypha/static_src/src/javascript/apply/form-group-toggle.js
Labels: bug

#1890 Upgrade django tables2 to 2.x
  hypha/apply/funds/paginators.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/views.py
  requirements.txt
Labels: maintenance

#1887 Set target blanks on all external links in Wagtail editor. Make targe…
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/utils/options.py
  hypha/settings/base.py
  hypha/static_src/src/javascript/apply/application-form-links-new-window.js
Labels: enhancement

#1888 Add meta term filter to submission tables.
  hypha/apply/funds/tables.py
Labels: enhancement
