Repository HyphaApp/hypha, pull requests merged in 2020-07, with the labels that each got.

#2067 Remove outdated mailgun-validator.js.
  hypha/apply/funds/templates/funds/application_base.html
  hypha/static_src/src/javascript/apply/mailgun-validator.js
Labels: maintenance

#2059 Disable view label from summary card when there is no data to view
  hypha/apply/dashboard/templates/dashboard/dashboard.html
Labels: enhancement

#2063 Let custom slack channels on fund replace default instead of adding to it
  hypha/apply/activity/messaging.py
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/funds/migrations/0075_auto_20200629_1707.py
  hypha/apply/funds/models/applications.py
Labels: enhancement

#2062 Remove fixes for Internet Explorer 11, very few users, if any, are using it still
  .sass-lint.yml
  hypha/static_src/src/app/src/components/DetailView/style.scss
  hypha/static_src/src/app/src/components/Listing/style.scss
  hypha/static_src/src/app/src/containers/DisplayPanel/style.scss
  hypha/static_src/src/javascript/main-top.js
  hypha/static_src/src/sass/apply/abstracts/_mixins.scss
  hypha/static_src/src/sass/apply/components/_grid.scss
  hypha/static_src/src/sass/public/components/_grid.scss
  package.json
Labels: maintenance

#2077 Include submissions with no value.
  hypha/apply/funds/templates/funds/includes/submission_stats.html
  hypha/apply/funds/views.py
Labels: bug

#2033 Add multi inputs single line text field and render url/e-mail as links
  hypha/apply/funds/migrations/0076_multi_input_char_block.py
  hypha/apply/funds/models/mixins.py
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/projects/migrations/0034_multi_input_char_block.py
  hypha/apply/stream_forms/blocks.py
  hypha/apply/stream_forms/models.py
  hypha/apply/stream_forms/templates/stream_forms/render_unsafe_field.html
  hypha/apply/templates/forms/includes/multi_input_field.html
  hypha/static_src/src/javascript/apply/multi-input-fields.js
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/public/components/_form.scss
Labels: enhancement

#2079 Set default value for submission_reapplied.
  hypha/apply/funds/management/commands/export_submissions_csv.py
Labels: bug

#2065 Use legal name field if it exist to prefill Legal name on projects.
  hypha/apply/funds/models/mixins.py
  hypha/apply/projects/models.py
Labels: enhancement

#2084 Update to latest django-two-factor-auth with followup up changes.
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
  hypha/urls.py
  requirements.txt
Labels: maintenance, needs testing

#2093 Updating pillow and other minor packages.
  requirements.txt
Labels: maintenance
