Repository HyphaApp/hypha, pull requests merged in 2020-08, with the labels that each got.

#2098 Update to Django 2.2.15
  requirements.txt
Labels: maintenance

#2096 Add configurable setting to change page size when downloading PDFs
  hypha/apply/funds/views.py
  hypha/apply/projects/views/project.py
  hypha/apply/utils/migrations/0001_add_pdf_page_size_setting.py
  hypha/apply/utils/migrations/__init__.py
  hypha/apply/utils/models.py
  hypha/apply/utils/pdfs.py
Labels: enhancement

#2089 Implement score field without text box block
  hypha/apply/review/blocks.py
  hypha/apply/review/forms.py
  hypha/apply/review/migrations/0023_add_score_without_text_block.py
  hypha/apply/review/models.py
  hypha/apply/review/options.py
  hypha/apply/review/tests/factories/blocks.py
  hypha/apply/review/tests/test_views.py
Labels: feature

#2100 Node package updates.
  package-lock.json
Labels: maintenance

#2058 Settings for Salesforce integration
  .gitignore
  docker/Dockerfile.dev
  docker/docker-compose.yaml
  hypha/settings/base.py
  requirements.txt
Labels: feature

#2088 Add batch delete functionality to all submissions view
  hypha/apply/activity/messaging.py
  hypha/apply/activity/migrations/0055_add_batch_delete_submission.py
  hypha/apply/activity/options.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/templates/funds/includes/batch_delete_submission_form.html
  hypha/apply/funds/templates/funds/includes/delegated_form_base.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/views.py
  hypha/templates/includes/sprites.html
Labels: enhancement

#2085 Add django-file-form to upload fields
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/mixins.py
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/funds/views.py
  hypha/apply/projects/forms.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/report.py
  hypha/apply/stream_forms/blocks.py
  hypha/apply/stream_forms/fields.py
  hypha/apply/stream_forms/files.py
  hypha/apply/stream_forms/forms.py
  hypha/apply/stream_forms/templates/stream_forms/fields/multi_file_field.html
  hypha/apply/stream_forms/tests.py
  hypha/apply/templates/forms/includes/field.html
  hypha/settings/base.py
  hypha/settings/local.py.example
  hypha/static_src/src/javascript/apply/file-uploads.js
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/public/components/_form.scss
  hypha/urls.py
  requirements.txt
Labels: feature

#2111 Rename AC Review to External Review.
  hypha/apply/funds/workflow.py
Labels: enhancement

#2048 Enhancement/use button tag for submit buttons
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/funds/templates/funds/admin/parent_chooser.html
  hypha/apply/funds/templates/funds/applicationsubmission_confirm_delete.html
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/funds/templates/funds/includes/delegated_form_base.html
  hypha/apply/funds/templates/funds/reminder_confirm_delete.html
  hypha/apply/funds/templates/funds/submission_sealed.html
  hypha/apply/funds/views.py
  hypha/apply/projects/templates/application_projects/includes/report_line.html
  hypha/apply/projects/templates/application_projects/includes/reports.html
  hypha/apply/projects/templates/application_projects/paymentrequest_confirm_delete.html
  hypha/apply/projects/templates/application_projects/paymentrequest_form.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/review/templates/review/review_confirm_delete.html
  hypha/apply/review/templates/review/review_edit_form.html
  hypha/public/news/templates/news/news_index.html
  hypha/public/people/templates/people/person_index_page.html
  hypha/static_src/src/sass/apply/abstracts/_mixins.scss
  hypha/static_src/src/sass/public/abstracts/_mixins.scss
  hypha/templates/password_required.html
Labels: enhancement
