Repository HyphaApp/hypha, pull requests merged in 2020-04, with the labels that each got.

#1900 Add user input to the submission form copy javascript.
  hypha/static_src/src/javascript/apply/submission-form-copy.js
Labels: enhancement

#1916 Add pull request template, CONTRIBUTING.md and minor fixes to LICENCE and issue template files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE
Labels: maintenance

#1919 Updated to node and python packages.
  package-lock.json
  requirements.txt
Labels: maintenance

#1921 Make the header with review authors of the reviews list table sticky.
  hypha/apply/review/templates/review/review_list.html
  hypha/static_src/src/sass/apply/components/_reviews-list.scss
  hypha/static_src/src/sass/apply/components/_wrapper.scss
Labels: enhancement

#1257 Improvements to 2FA workflow and UI
  hypha/apply/users/templates/two_factor/_base.html
  hypha/apply/users/templates/two_factor/_base_focus.html
  hypha/apply/users/templates/two_factor/_wizard_actions.html
  hypha/apply/users/templates/two_factor/core/backup_tokens.html
  hypha/apply/users/templates/two_factor/profile/disable.html
  hypha/apply/users/templates/two_factor/profile/profile.html
  hypha/static_src/src/javascript/apply/two-factor-focus.js
  hypha/static_src/src/sass/apply/components/_button.scss
  hypha/static_src/src/sass/apply/components/_two-factor.scss
  hypha/static_src/src/sass/apply/main.scss
Labels: enhancement

#1925 Fix sentence for determination forms for stages
  hypha/apply/determinations/views.py
Labels: maintenance

#1929 Wagtail security release
  requirements.txt
Labels: maintenance

#1933 Fix count of waiting review on Dashboard
  hypha/apply/dashboard/templates/dashboard/dashboard.html
Labels: bug

#1931 Disable user password management from Wagtail admin
  hypha/settings/base.py
Labels: enhancement

#1932 Sort by active/inactive status in admin users listing
  hypha/apply/users/admin_views.py
  hypha/apply/users/templates/wagtailusers/users/list.html
Labels: enhancement

#1937 Add focus to submission export command.
  hypha/apply/funds/management/commands/export_submissions_csv.py
Labels: enhancement

#1938 Refactor dashboard views
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/views.py
Labels: maintenance

#1947 don't show tooltip when status can be changed
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/static_src/src/javascript/apply/batch-actions.js
Labels: bug

#1926 Allow staff to set word limit for text field
  hypha/apply/funds/migrations/0074_add_word_limit_to_text_blocks.py
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/projects/migrations/0033_add_word_limit_to_text_blocks.py
  hypha/apply/review/migrations/0022_add_word_limit_to_text_blocks.py
  hypha/apply/stream_forms/blocks.py
  hypha/apply/stream_forms/models.py
  hypha/apply/templates/forms/includes/field.html
  hypha/static_src/src/javascript/apply/tinymce-word-count.js
  hypha/static_src/src/sass/apply/components/_rich-text.scss
  hypha/static_src/src/sass/public/components/_rich-text.scss
Labels: feature

#1901 Allow staff to edit final determination except status
  hypha/apply/activity/messaging.py
  hypha/apply/determinations/forms.py
  hypha/apply/determinations/migrations/0009_add_send_notice_field.py
  hypha/apply/determinations/models.py
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/determinations/templates/determinations/determination_form.html
  hypha/apply/determinations/templates/determinations/includes/determination_button.html
  hypha/apply/determinations/tests/test_views.py
  hypha/apply/determinations/urls.py
  hypha/apply/determinations/views.py
  hypha/static_src/src/sass/apply/components/_determination.scss
  hypha/static_src/src/sass/apply/main.scss
Labels: feature

#1945 Add a submissions result page to get sum and average of values per ro…
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
Labels: feature

#1942 When two internal reviewers have been selected move the submission to…
  hypha/apply/funds/views.py
Labels: bug

#1928 Make it so reviewers can flag submission.
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/flagged.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/flags/views.py
  hypha/apply/funds/templates/funds/applicationsubmission_reviewer_detail.html
  hypha/apply/funds/templates/funds/submissions_user_flagged.html
  hypha/apply/funds/views.py
Labels: enhancement

#1946 Updating to Python 3.7, Postgres 12 and Node 12.
  .circleci/config.yml
  .travis.yml
  package.json
  runtime.txt
Labels: maintenance

#1952 remove unused field_template on ApplicationSubmission Modal
  hypha/apply/funds/models/submissions.py
Labels: maintenance

#1956 Remove js-tabs classes from result link wrapper. Made all rounds and …
  hypha/apply/funds/templates/funds/submissions_overview.html
Labels: bug
