Repository HyphaApp/hypha, pull requests merged in 2020-06, with the labels that each got.

#2001 Add submission stats section to result page.
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templates/funds/includes/submission_stats.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/views.py
Labels: feature

#2027 Make the ninety_days column primary.
  hypha/apply/funds/tables.py
Labels: enhancement

#1997 Use db functions to calculate submission results. Performs significantly better.
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/views.py
Labels: RTBC, enhancement

#2023 Upgrade to Wagtail 2.9
  hypha/apply/determinations/views.py
  hypha/apply/middleware.py
  hypha/public/home/templates/home/home_page.html
  hypha/public/navigation/templatetags/navigation_tags.py
  hypha/public/search/views.py
  hypha/settings/base.py
  hypha/templates/base-apply.html
  hypha/templates/base.html
  hypha/templates/includes/share.html
  requirements.txt
Labels: RTBC, maintenance

#2026 Add submission_reapplied to submission export command.
  hypha/apply/funds/management/commands/export_submissions_csv.py
Labels: maintenance

#2007 Feature/staff assignments view
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/staff_assignments.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
Labels: feature

#2028 Update Django to version 2.2.13
  package-lock.json
  package.json
  requirements.txt
Labels: maintenance

#1979 Allow Applicants to save application as a draft
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/models/utils.py
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/application_base_landing.html
  hypha/apply/funds/tests/test_models.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/views.py
  hypha/apply/funds/workflow.py
  hypha/apply/review/views.py
  hypha/static_src/src/javascript/apply/submission-form-copy.js
Labels: feature

#2047 Add rel noopener noreferrer to all none local links with target blank.
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/stream_forms/templates/stream_forms/includes/file_field.html
  hypha/apply/templates/forms/includes/field.html
  hypha/static_src/src/javascript/apply/application-form-links-new-window.js
Labels: enhancement

#2057 Use hypha and not old opentech in stellar conf file.
  stellar.yaml
Labels: maintenance

#2064 minor updates to a number of pip packages.
  requirements-dev.txt
  requirements.txt
Labels: maintenance
