Repository HyphaApp/hypha, pull requests merged in 2020-05, with the labels that each got.

#1972 Updated node packages May 2020
  package-lock.json
Labels: maintenance

#1975 Make wagtail use API token for cloudflare cache invalidation and not …
  hypha/settings/base.py
Labels: bug

#1923 Enhancement/allow visibility edit on comments
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/api/v1/serializers.py
  hypha/apply/api/v1/tests/test_views.py
  hypha/apply/api/v1/views.py
  hypha/static_src/src/javascript/apply/edit-comment.js
  hypha/static_src/src/sass/apply/components/_feed.scss
Labels: enhancement

#1960 Add help text and links to application form copy
  hypha/static_src/src/javascript/apply/submission-form-copy.js
Labels: enhancement

#1976 Display a warning to admin user in case a page model like Fund, Round can not be deleted due to ProtectedError exception
  hypha/apply/utils/views.py
  hypha/urls.py
Labels: enhancement

#1968 Allow staff to delete appliation form
  hypha/apply/funds/admin.py
Labels: RTBC, enhancement

#1967 Make receipts an optional field on payment requrests
  hypha/apply/projects/forms.py
  hypha/apply/projects/tests/test_forms.py
Labels: RTBC, enhancement

#1955 Send compliance the link to the simplified views
  hypha/apply/activity/templates/messages/email/sent_to_compliance.html
Labels: RTBC, enhancement

#1935 Moving the edit comment UI to inline in detailed view
  hypha/static_src/src/app/src/containers/DisplayPanel/index.js
  hypha/static_src/src/app/src/containers/NoteListing.js
Labels: RTBC, enhancement

#1958 Improve display of 'Add determination' action
  hypha/apply/determinations/templates/determinations/includes/determination_button.html
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templates/funds/includes/actions.html
  hypha/apply/funds/tests/test_views.py
Labels: RTBC, enhancement

#1922 Improve display of screen application primary action
  hypha/apply/funds/templates/funds/includes/actions.html
  hypha/apply/funds/templates/funds/includes/screening_status_block.html
  hypha/apply/funds/tests/test_views.py
  hypha/static_src/src/sass/apply/components/_link.scss
Labels: RTBC, enhancement

#1953 Improve display of Add Review action
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/generic_primary_actions.html
  hypha/apply/funds/templatetags/primaryactions_tags.py
  hypha/apply/funds/tests/factories/models.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/review/templates/review/includes/review_button.html
Labels: RTBC, enhancement

#1980 Remove unused variable in application_form.html
  hypha/apply/funds/templates/funds/application_base.html
Labels: maintenance

#1981 Upgrade Wagtail for CVE-2020-11037
  requirements.txt
Labels: maintenance

#1927 Improve display of Assign Reviewers action
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/tests/test_views.py
Labels: RTBC, enhancement

#1984 Make use of has_all_reviewer_roles_assigned.
  hypha/apply/funds/views.py
Labels: enhancement

#1986 Fix for submission title in batch dialog.
  hypha/static_src/src/javascript/apply/batch-actions.js
Labels: bug

#1987 Move main.js to bottom and create main-top.js with the bits that need…
  hypha/static_src/src/javascript/main-top.js
  hypha/static_src/src/javascript/main.js
  hypha/templates/base-apply.html
  hypha/templates/base.html
Labels: bug

#1995 Give user login option before raising 403
  hypha/apply/review/views.py
Labels: enhancement

#1993 Only show metaterms with filter_on_dashboard set to true in submissio…
  hypha/apply/funds/tables.py
Labels: enhancement

#1965 Improve display of 'View determination' action
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/generic_primary_actions.html
  hypha/apply/funds/templatetags/primaryactions_tags.py
  hypha/apply/funds/tests/test_views.py
Labels: enhancement

#1998 Improving the result calculation, a lot of dirty data in the db.
  hypha/apply/funds/views.py
Labels: enhancement

#2003 Correcting the confirmation_text_extra variable in the confirmation e…
  hypha/apply/funds/templates/funds/email/confirmation.html
Labels: bug

#2006 Add the confirmation_text_extra to round landing page.
  hypha/apply/funds/templates/funds/application_base_landing.html
Labels: enhancement

#2009 Add setting SEND_READY_FOR_REVIEW, defaults to true but if set to fal…
  hypha/apply/activity/messaging.py
  hypha/apply/activity/templates/messages/email/batch_ready_to_review.html
  hypha/apply/activity/templates/messages/email/ready_to_review.html
  hypha/settings/base.py
Labels: enhancement

#2010 Show deadline on application page
  hypha/apply/funds/templates/funds/application_base.html
Labels: enhancement

#2014 Minor updates to a list of packages.
  hypha/apply/funds/admin_helpers.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/users/forms.py
  requirements-dev.txt
  requirements.txt
Labels: maintenance

#2013 Update psycopg2 to 2.8.5.
  requirements.txt
Labels: maintenance

#2016 No longer a need to pin old Faker version.
  requirements-dev.txt
Labels: maintenance

#2017 Update django-two-factor-auth and unpin old django-otp version.
  requirements.txt
Labels: maintenance

#2018 Always use gettext_lazy.
  hypha/apply/categories/blocks.py
  hypha/apply/categories/models.py
  hypha/apply/determinations/models.py
  hypha/apply/determinations/views.py
  hypha/apply/funds/admin_helpers.py
  hypha/apply/funds/admin_views.py
  hypha/apply/funds/blocks.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/models/__init__.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/views.py
  hypha/apply/projects/forms.py
  hypha/apply/projects/models.py
  hypha/apply/projects/views/project.py
  hypha/apply/review/blocks.py
  hypha/apply/review/models.py
  hypha/apply/stream_forms/blocks.py
  hypha/apply/users/admin_views.py
  hypha/apply/utils/blocks.py
  hypha/public/forms/models.py
  hypha/public/mailchimp/views.py
Labels: maintenance
