Repository HyphaApp/hypha, pull requests merged in 2021-12, with the labels that each got.

#2655 Implement TRANSITION_AFTER_ASSIGNED.
  hypha/apply/funds/views.py
  hypha/apply/review/views.py
  hypha/settings/base.py
  hypha/settings/test.py
Labels: Type: Enhancement, Type: Minor

#2660 Add missing d-none for display none on django-two-factor-auth.
  hypha/static_src/src/sass/apply/components/_two-factor.scss
Labels: Type: Maintenance, Type: Patch

#2653 Require password on email update
  hypha/apply/users/forms.py
  hypha/apply/users/templates/users/email_change/confirm_email.txt
  hypha/apply/users/templates/users/email_change/confirm_password.html
  hypha/apply/users/templates/users/email_change/done.html
  hypha/apply/users/templates/users/email_change/invalid_link.html
  hypha/apply/users/urls.py
  hypha/apply/users/utils.py
  hypha/apply/users/views.py
  hypha/settings/base.py
Labels: Type: Feature, Type: Minor

#2662 Update to Django 2.2.25.
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2661 Make password required to change account 2FA
  hypha/apply/users/forms.py
  hypha/apply/users/templates/two_factor/core/backup_tokens_password.html
  hypha/apply/users/templates/two_factor/profile/disable.html
  hypha/apply/users/templates/two_factor/profile/profile.html
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
Labels: Type: Feature, Type: Minor

#2667 Updated node packages.
  package-lock.json
Labels: Type: Maintenance, Type: Patch

#2672 Add separate table view for awaiting review submissions
  hypha/apply/dashboard/templates/dashboard/includes/waiting-for-review.html
  hypha/apply/funds/templates/funds/submissions_awaiting_review.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
Labels: Type: Enhancement, Type: Minor

#2675 Show short dates in the determination blocks.
  hypha/apply/determinations/templates/determinations/includes/applicant_determination_block.html
  hypha/apply/determinations/templates/determinations/includes/determination_block.html
Labels: Type: Enhancement, Type: Patch

#2673 Add count to the submission by round and by status tables.
  hypha/apply/funds/templates/funds/submissions_by_round.html
  hypha/apply/funds/templates/funds/submissions_by_status.html
Labels: Type: Enhancement, Type: Patch

#2659 Update pip packages december 2021
  requirements-dev.txt
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2498 Use FILE_ALLOWED_EXTENSIONS to validate form upload documents
  hypha/public/forms/models.py
Labels: Type: Bug, Type: Minor
