Repository HyphaApp/hypha, pull requests merged in 2021-03, with the labels that each got.

#2256 Fix wagtail page delete
  hypha/apply/utils/views.py
Labels: bug

#2252 No screening option in react app's filter
  hypha/apply/api/v1/filters.py
  hypha/apply/api/v1/views.py
Labels: enhancement

#2255 Added more block to public pages.
  hypha/public/funds/migrations/0013_add_more_block.py
  hypha/public/news/migrations/0012_add_more_block.py
  hypha/public/people/migrations/0014_add_more_block.py
  hypha/public/projects/migrations/0009_add_more_block.py
  hypha/public/standardpages/migrations/0005_add_more_block.py
  hypha/public/utils/blocks.py
  hypha/static_src/src/sass/public/components/_show-more.scss
  hypha/templates/blocks/more_block.html
Labels: enhancement

#2235 Replace state with title in React app middle pane.
  hypha/static_src/src/app/src/components/SubmissionDisplay/index.js
Labels: enhancement

#2251 Allow to change the screening default when sub screening choices available
  hypha/apply/api/v1/screening/tests/test_views.py
  hypha/apply/api/v1/screening/views.py
  hypha/apply/funds/templates/funds/includes/screening_status_block.html
  hypha/static_src/src/app/src/containers/ScreeningStatus/index.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/javascript/apply/screening-status.js
Labels: enhancement

#2266 Add z-index to cookieconsent so it does not get obscured on mobil by header
  hypha/static_src/src/sass/apply/components/_wrapper.scss
  hypha/static_src/src/sass/public/components/_wrapper.scss
Labels: bug

#2267 Hide submission count on react app
  hypha/apply/funds/templates/funds/submissions.html
  hypha/static_src/src/sass/apply/components/_admin-bar.scss
Labels: bug

#2210 Use category question options to filter submissions
  hypha/apply/api/v1/filters.py
  hypha/apply/api/v1/utils.py
  hypha/apply/api/v1/views.py
  hypha/apply/categories/migrations/0006_use_category_options_as_submission_filter.py
  hypha/apply/categories/models.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/includes/screening_form.html
Labels: feature

#2270 Only render submission funding and address info in header when values are present
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
Labels: enhancement

#2268 Remove the per page filter from submission table.
  hypha/apply/funds/tables.py
Labels: enhancement

#2269 Remove the jump menu from the react app, no longer needed with filters in place
  hypha/static_src/src/app/src/components/GroupedListing/index.js
  hypha/static_src/src/app/src/components/ListingDropdown/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/components/ListingDropdown/__tests__/index.test.js
  hypha/static_src/src/app/src/components/ListingDropdown/index.js
  hypha/static_src/src/app/src/components/SubmissionDisplay/index.js
  hypha/static_src/src/app/src/containers/DisplayPanel/index.js
Labels: enhancement

#2260 Add days to duration block.
  hypha/apply/funds/blocks.py
  hypha/apply/funds/migrations/0085_add_days_to_duration_block.py
Labels: enhancement

#2287 Extra text setting user login
  hypha/apply/users/forms.py
  hypha/apply/users/migrations/0015_login_extra_text.py
  hypha/apply/users/models.py
  hypha/apply/users/templates/users/login.html
  hypha/static_src/src/sass/public/components/_form.scss
Labels: RTBC, enhancement

#2249 Feature: Application summary field & icon to show grouped applications summary in React
  hypha/apply/api/v1/filters.py
  hypha/apply/api/v1/review/permissions.py
  hypha/apply/api/v1/review/views.py
  hypha/apply/api/v1/serializers.py
  hypha/apply/api/v1/views.py
  hypha/apply/funds/migrations/0086_applicationsubmission_summary.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templates/funds/grouped_application_list.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
  hypha/static_src/src/app/src/AllSubmissionsApp.js
  hypha/static_src/src/app/src/SubmissionsByRoundApp.js
  hypha/static_src/src/app/src/SubmissionsByStatusApp.js
  hypha/static_src/src/app/src/SwitcherApp.js
  hypha/static_src/src/app/src/api/index.js
  hypha/static_src/src/app/src/api/submissions.js
  hypha/static_src/src/app/src/components/HoverEditor/index.js
  hypha/static_src/src/app/src/components/HoverEditor/styles.scss
  hypha/static_src/src/app/src/components/SubmissionDisplay/index.js
  hypha/static_src/src/app/src/containers/CurrentSubmissionDisplay.js
  hypha/static_src/src/app/src/containers/GroupedApplications/actions.js
  hypha/static_src/src/app/src/containers/GroupedApplications/constants.js
  hypha/static_src/src/app/src/containers/GroupedApplications/index.js
  hypha/static_src/src/app/src/containers/GroupedApplications/models.js
  hypha/static_src/src/app/src/containers/GroupedApplications/reducer.js
  hypha/static_src/src/app/src/containers/GroupedApplications/sagas.js
  hypha/static_src/src/app/src/containers/GroupedApplications/selectors.js
  hypha/static_src/src/app/src/containers/GroupedApplications/styles.scss
  hypha/static_src/src/app/src/containers/SubmissionFilters/index.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/groupedApplicationsIndex.js
  hypha/static_src/src/app/src/redux/actions/submissions.js
  hypha/static_src/src/app/src/redux/actions/tests/submissions.test.js
  hypha/static_src/src/app/src/redux/reducers/submissions.js
  hypha/static_src/src/app/src/redux/selectors/submissions.js
  hypha/static_src/src/app/webpack.base.config.js
Labels: feature

#2290 Add setting for extra text on application landing page.
  hypha/apply/funds/admin.py
  hypha/apply/funds/migrations/0087_applicationsettings.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/templates/funds/application_base_landing.html
  hypha/apply/funds/templates/funds/lab_type_landing.html
  hypha/apply/users/templates/users/login.html
  hypha/public/home/migrations/0002_create_homepage.py
Labels: enhancement

#2294 Revert permissions on ReviewerSubmissionDetailView when Reviewer sett…
  hypha/apply/funds/views.py
Labels: bug

#2299 Add wagtail-purge, cache CDN purge.
  hypha/settings/base.py
  requirements.txt
Labels: feature

#2300 Add the WAGTAILEMBEDS_RESPONSIVE_HTML setting set to true.
  hypha/settings/base.py
Labels: enhancement

#2291 Add icon to share filter state in react
  hypha/static_src/src/app/src/api/submissions.js
  hypha/static_src/src/app/src/containers/ByRoundListing.js
  hypha/static_src/src/app/src/containers/ByStatusListing.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/index.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/selectors.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/actions.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/index.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/sagas.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/selectors.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/SubmissionFilters/tests/action.test.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/tests/index.test.js
  hypha/static_src/src/app/src/groupedApplicationsIndex.js
  hypha/static_src/src/app/src/redux/actions/submissions.js
  hypha/static_src/src/app/src/redux/selectors/submissions.js
  package-lock.json
  package.json
Labels: Status: RTBC, Type: Enhancement

#2304 Update the text in the invite to proposal notification e-mail.
  hypha/apply/activity/templates/messages/email/applicant_base.html
  hypha/apply/activity/templates/messages/email/determination.html
  hypha/apply/activity/templates/messages/email/invited_to_proposal.html
Labels: Type: Enhancement

#2306 Update node packages.
  package-lock.json
Labels: Type: Maintenance

#2301 Add Flag functionality in react
  hypha/apply/flags/views.py
  hypha/static_src/src/app/src/api/utils.js
  hypha/static_src/src/app/src/containers/DisplayPanel/index.js
  hypha/static_src/src/app/src/containers/FlagContainer/WithFlagType.js
  hypha/static_src/src/app/src/containers/FlagContainer/actions.js
  hypha/static_src/src/app/src/containers/FlagContainer/constants.js
  hypha/static_src/src/app/src/containers/FlagContainer/index.js
  hypha/static_src/src/app/src/containers/FlagContainer/models.js
  hypha/static_src/src/app/src/containers/FlagContainer/reducer.js
  hypha/static_src/src/app/src/containers/FlagContainer/sagas.js
  hypha/static_src/src/app/src/containers/FlagContainer/selectors.js
  hypha/static_src/src/app/src/containers/FlagContainer/style.scss
Labels: Type: Enhancement
