Repository HyphaApp/hypha, pull requests merged in 2021-07, with the labels that each got.

#2438 Add a finance user group, add finance dashboard, give finance access …
  hypha/apply/dashboard/templates/dashboard/community_dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/templates/dashboard/partner_dashboard.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/report.py
  hypha/apply/users/decorators.py
  hypha/apply/users/groups.py
  hypha/apply/users/migrations/0016_add_finance_group.py
  hypha/apply/users/models.py
  hypha/apply/users/tests/factories.py
  hypha/apply/utils/views.py
  hypha/public/navigation/templates/navigation/primarynav-apply.html
  hypha/static_src/src/sass/apply/components/_projects-table.scss
Labels: Type: Feature, Type: Minor

#2446 Replace -placeholder with -uploads
  hypha/apply/funds/views.py
  hypha/apply/stream_forms/fields.py
  requirements.txt
Labels: Status: RTBC, Type: Maintenance, Type: Minor

#2459 Fix no-results-found bug in react filters
  hypha/static_src/src/app/src/containers/ByRoundListing.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/index.js
  hypha/static_src/src/app/src/containers/SubmissionFilters/sagas.js
  hypha/static_src/src/app/src/redux/actions/submissions.js
Labels: Type: Bug, Type: Minor

#2451 Update node packages
  hypha/static_src/src/app/src/common/components/FilterDropDown/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/SubmissionFilters/tests/__snapshots__/index.test.js.snap
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Minor

#2401 Add vendor
  hypha/apply/activity/messaging.py
  hypha/apply/activity/migrations/0056_add_updated_vendor.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/vendor_setup_needed.html
  hypha/apply/activity/templates/messages/email/vendor_updated.html
  hypha/apply/categories/blocks.py
  hypha/apply/projects/forms.py
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/forms/report.py
  hypha/apply/projects/forms/vendor.py
  hypha/apply/projects/migrations/0036_add_vendor.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/models/vendor.py
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
  hypha/apply/projects/templates/application_projects/vendor_form.html
  hypha/apply/projects/templates/application_projects/vendor_success.html
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/vendor.py
  hypha/apply/templates/forms/includes/field.html
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/settings/base.py
  hypha/static_src/src/javascript/apply/file-uploads.js
Labels: Type: Feature, Type: Minor

#2465 Using / for division is deprecated and will be removed in Dart Sass 2.0.0
  hypha/static_src/src/sass/apply/abstracts/_functions.scss
  hypha/static_src/src/sass/apply/abstracts/_mixins.scss
  hypha/static_src/src/sass/apply/base/_typography.scss
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/public/abstracts/_functions.scss
  hypha/static_src/src/sass/public/abstracts/_mixins.scss
  hypha/static_src/src/sass/public/base/_typography.scss
  hypha/static_src/src/sass/public/components/_form.scss
Labels: Type: Maintenance, Type: Patch
