Repository HyphaApp/hypha, pull requests merged in 2021-04, with the labels that each got.

#2307 Update sandbox db.
  public/sandbox_db.dump
Labels: Type: Maintenance

#2314 Update to Django 2.2.20
  requirements.txt
Labels: Type: Maintenance

#2316 Remove salesforce items from Docker conf for now.
  docker/Dockerfile.dev
  docker/docker-compose.yaml
Labels: Type: Maintenance

#2319 Update repo links after move.
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: Type: Maintenance

#2305 Add resizeable panels to left/right columns react
  hypha/static_src/src/app/src/components/DetailView/index.js
  hypha/static_src/src/app/src/components/ResizablePanels.js
  hypha/static_src/src/app/src/components/ResizablePanels.scss
  hypha/static_src/src/app/src/containers/Determination.js
  hypha/static_src/src/app/src/containers/DeterminationForm/index.js
  hypha/static_src/src/app/src/containers/DeterminationForm/styles.scss
  hypha/static_src/src/app/src/containers/DeterminationForm/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/DeterminationForm/tests/index.test.js
  hypha/static_src/src/app/src/containers/DisplayPanel/index.js
  hypha/static_src/src/app/src/containers/DisplayPanel/style.scss
  hypha/static_src/src/app/src/containers/ReviewForm/index.js
  hypha/static_src/src/app/src/containers/ReviewForm/styles.scss
  hypha/static_src/src/app/src/containers/ReviewForm/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/ReviewForm/tests/index.test.js
Labels: Type: Enhancement

#2320 Update node packages, browserlist.
  package-lock.json
Labels: Type: Maintenance

#2321 Update the ISSUE_TEMPLATE after labels renaming.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/discussion-request.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Type: Maintenance

#2332 Update to django-debug-toolbar-3.2.1.
  requirements-dev.txt
Labels: Type: Maintenance

#2282 Make duration not required.
  hypha/apply/funds/blocks.py
  hypha/apply/funds/migrations/0088_make_duraion_not_required.py
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
Labels: Type: Enhancement

#2338 Update Wagtail to 2.11.7.
  requirements.txt
Labels: Type: Maintenance

#2346 Add per page links to submission table template.
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/static_src/src/sass/apply/components/_actions-bar.scss
Labels: Type: Enhancement

#2348 Rename state screening to need screening.
  hypha/apply/funds/workflow.py
Labels: Type: Enhancement

#2350 Make use of RESOLVED_VERSION in release drafter action.
  .github/release-drafter.yml
Labels: Type: Maintenance, Type: Patch

#2351 Update webpack packages to ssri can be updated.
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Patch
