Repository HyphaApp/hypha, pull requests merged in 2021-10, with the labels that each got.

#2558 Add new contracting role and rename team admin to staff admin.
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/users/groups.py
  hypha/apply/users/migrations/0017_rename_staff_admin.py
  hypha/apply/users/migrations/0018_add_contracting_group.py
  hypha/apply/users/models.py
Labels: Type: Enhancement, Type: Minor

#2569 Add an extra choice to available outcomes(determination)
  hypha/apply/api/v1/determination/utils.py
  hypha/apply/determinations/forms.py
  hypha/apply/determinations/views.py
Labels: Type: Enhancement, Type: Minor

#2588 String changes in project after workflow walk through.
  hypha/apply/activity/migrations/0060_contracting_name_update.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/vendor_setup_needed.html
  hypha/apply/activity/templates/messages/email/vendor_updated.html
  hypha/apply/funds/templates/funds/applicationsubmission_simplified_detail.html
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/templates/application_projects/paymentrequest_confirm_delete.html
  hypha/apply/projects/templates/application_projects/paymentrequest_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
  hypha/apply/projects/templates/application_projects/vendor_form.html
  hypha/apply/projects/views/vendor.py
Labels: Type: Enhancement, Type: Patch

#2602 Improve language on the invalid activation template.
  hypha/apply/users/templates/users/activation/invalid.html
Labels: Type: Bug, Type: Patch
