Repository HyphaApp/hypha, pull requests merged in 2021-09, with the labels that each got.

#2528 Update runtime to python-3.8.12.
  runtime.txt
Labels: Type: Maintenance, Type: Patch

#2520 Implement a TRANSITION_AFTER_REVIEWS settings.
  hypha/apply/review/views.py
  hypha/settings/base.py
  hypha/settings/test.py
Labels: Type: Enhancement, Type: Minor

#2524 Maintenance/pip packages august 2021
  hypha/settings/base.py
  requirements-dev.txt
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2538 Updated the sandbox db with Hypha logos.
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch

#2539 Wrap modified_time in a try for local development where files might not always exist
  hypha/apply/stream_forms/files.py
Labels: Type: Maintenance, Type: Patch

#2534 Emails reviewers when they are assigned
  hypha/apply/activity/messaging.py
  hypha/apply/activity/tests/test_messaging.py
Labels: Type: Enhancement, Status: RTBC, Type: Minor

#2443 Embed pdf inline on invoice detail page.
  hypha/apply/projects/templates/application_projects/paymentrequest_detail.html
  hypha/static_src/src/sass/apply/components/_wrapper.scss
Labels: Type: Enhancement, Type: Minor

#2540 Fix tinymce word count issue
  hypha/static_src/src/javascript/apply/tinymce-word-count.js
  hypha/static_src/src/sass/apply/components/_rich-text.scss
  hypha/static_src/src/sass/public/components/_rich-text.scss
Labels: Type: Bug, Type: Patch

#2544 Add lead filter and column to round view.
  hypha/apply/funds/views.py
Labels: Type: Enhancement, Type: Minor

#2546 Make flag sidebar box more compact and translateble.
  hypha/apply/flags/templates/flags/flags.html
Labels: Type: Enhancement, Type: Patch

#2543 Make projects new code translateble.
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/forms/report.py
  hypha/apply/projects/forms/vendor.py
  hypha/apply/projects/migrations/0038_project_translateble.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/models/report.py
Labels: Type: Enhancement, Type: Minor

#2545 Make more templates translateble
  hypha/apply/activity/templates/activity/include/action_list.html
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/activity/templates/messages/email/vendor_setup_needed.html
  hypha/apply/activity/templates/messages/email/vendor_updated.html
  hypha/apply/categories/templates/categories/admin/includes/meta_term_list_header.html
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/community_dashboard.html
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/flagged.html
  hypha/apply/dashboard/templates/dashboard/includes/waiting-for-review.html
  hypha/apply/dashboard/templates/dashboard/partner_dashboard.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/determinations/templates/determinations/determination_form.html
  hypha/apply/determinations/templates/determinations/includes/applicant_determination_block.html
  hypha/apply/determinations/templates/determinations/includes/batch_determination_confirmation.html
  hypha/apply/determinations/templates/determinations/includes/determination_block.html
  hypha/apply/determinations/templates/determinations/includes/determination_button.html
  hypha/apply/home/templates/apply_home/apply_home_page.html
  hypha/apply/home/templates/apply_home/includes/apply_listing.html
  hypha/apply/review/templates/review/includes/review_button.html
  hypha/apply/review/templates/review/review_confirm_delete.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/review/templates/review/review_edit_form.html
  hypha/apply/review/templates/review/review_form.html
  hypha/apply/review/templates/review/review_list.html
  hypha/apply/review/views.py
Labels: Type: Enhancement, Type: Minor

#2521 Update message for empty rounds and labs
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/funds/templates/funds/includes/no_round_block_dashboard.html
  hypha/apply/funds/templates/funds/includes/round-block-listing.html
  hypha/apply/funds/templates/funds/includes/round-block.html
  hypha/apply/funds/templates/funds/submissions_overview.html
Labels: Type: Bug, Type: Patch

#2550 Remove gulp-load-plugins usage.
  gulpfile.js
  package.json
Labels: Type: Maintenance, Type: Patch

#2549 Make projects templates translatable.
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/projects/templates/application_projects/filters/widgets/date_range_input_widget.html
  hypha/apply/projects/templates/application_projects/includes/funding_block.html
  hypha/apply/projects/templates/application_projects/includes/invoice_block.html
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/includes/payment_requests.html
  hypha/apply/projects/templates/application_projects/includes/paymentrequest_admin_detail.html
  hypha/apply/projects/templates/application_projects/includes/report_line.html
  hypha/apply/projects/templates/application_projects/includes/reports.html
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/templates/application_projects/overview.html
  hypha/apply/projects/templates/application_projects/payment_request_list.html
  hypha/apply/projects/templates/application_projects/paymentrequest_admin_detail.html
  hypha/apply/projects/templates/application_projects/paymentrequest_confirm_delete.html
  hypha/apply/projects/templates/application_projects/paymentrequest_detail.html
  hypha/apply/projects/templates/application_projects/paymentrequest_form.html
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/projects/templates/application_projects/project_applicant_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/project_form.html
  hypha/apply/projects/templates/application_projects/project_list.html
  hypha/apply/projects/templates/application_projects/project_simplified_detail.html
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/templates/application_projects/report_list.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
  hypha/apply/projects/templates/application_projects/vendor_form.html
  hypha/apply/projects/templates/application_projects/vendor_success.html
Labels: Type: Enhancement, Type: Minor

#2552 Update package-lock after gulp-load-plugins removal.
  package-lock.json
Labels: Type: Maintenance, Type: Patch

#2554 Add a setting to make it possible to exclude filters/columns from submission tables.
  hypha/apply/funds/views.py
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#2547 Remove staff reviewers for a submission
  hypha/apply/funds/forms.py
Labels: Type: Enhancement, Type: Minor

#2555 Add options for SUBMISSIONS_TABLE_EXCLUDED_FIELDS variable.
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#2560 Make review options translatable.
  hypha/apply/review/options.py
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Enhancement, Type: Patch

#2563 In no determinations, hide the block for applicants.
  hypha/apply/determinations/templates/determinations/includes/applicant_determination_block.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
Labels: Type: Enhancement, Type: Patch

#2561 Update @svgr/webpack.
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Patch

#2567 Add an api to list all open rounds and labs
  hypha/apply/api/v1/serializers.py
  hypha/apply/api/v1/views.py
Labels: Type: Enhancement, Type: Minor
