Repository HyphaApp/hypha, pull requests merged in 2021-11, with the labels that each got.

#2593 Add contracting info action button.
  hypha/apply/projects/templates/application_projects/project_detail.html
Labels: Type: Enhancement, Type: Patch

#2609 Cleanup code related to payment requests
  hypha/apply/activity/messaging.py
  hypha/apply/activity/migrations/0061_payment_requests_cleanup.py
  hypha/apply/activity/migrations/0062_remove_payment_requests_activities.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/payment_request_status_updated.html
  hypha/apply/activity/templates/messages/email/payment_request_updated.html
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/activity/tests/test_models.py
  hypha/apply/api/v1/screening/tests/test_views.py
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/tests/test_views.py
  hypha/apply/dashboard/views.py
  hypha/apply/projects/filters.py
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/migrations/0041_payment_requests_cleanup.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/includes/payment_requests.html
  hypha/apply/projects/templates/application_projects/includes/paymentrequest_admin_detail.html
  hypha/apply/projects/templates/application_projects/overview.html
  hypha/apply/projects/templates/application_projects/payment_request_list.html
  hypha/apply/projects/templates/application_projects/paymentrequest_admin_detail.html
  hypha/apply/projects/templates/application_projects/paymentrequest_confirm_delete.html
  hypha/apply/projects/templates/application_projects/paymentrequest_detail.html
  hypha/apply/projects/templates/application_projects/paymentrequest_form.html
  hypha/apply/projects/templatetags/payment_request_tools.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/tests/test_templatetags.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/settings/base.py
  hypha/static_src/src/sass/apply/components/_projects-table.scss
Labels: Type: Enhancement, Type: Patch

#2616 Bypass django forms widget templates
  hypha/templates/wagtailadmin/widgets/date_input.html
  hypha/templates/wagtailadmin/widgets/datetime_input.html
Labels: Type: Enhancement, Type: Patch

#2598 Remove Edit button if there is no permission
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
Labels: Type: Enhancement, Type: Patch

#2617 Updates to sidebar ordering.
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/static_src/src/sass/apply/base/_base.scss
  hypha/static_src/src/sass/apply/components/_sidebar.scss
Labels: Type: Enhancement, Type: Patch

#2620 Send out vendor setup mail only after lead has been set on a project.
  hypha/apply/activity/templates/messages/email/vendor_setup_needed.html
  hypha/apply/api/v1/determination/views.py
  hypha/apply/determinations/views.py
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/includes/create_project_form.html
  hypha/apply/funds/views.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/views/project.py
  hypha/static_src/src/javascript/apply/toggle-proposal-info.js
Labels: Type: Enhancement, Type: Minor

#2638 Only allow API token access for round API endpoint.
  hypha/apply/api/v1/determination/views.py
  hypha/apply/api/v1/projects/views.py
  hypha/apply/api/v1/reminder/views.py
  hypha/apply/api/v1/review/views.py
  hypha/apply/api/v1/screening/views.py
  hypha/apply/api/v1/views.py
Labels: Type: Enhancement, Type: Minor

#2639 Fix project status view
  hypha/apply/projects/views/project.py
Labels: Type: Bug, Type: Patch

#2651 Rename summery to summary
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Bug, Type: Patch

#2650 Delete errant bracket in meta row
  hypha/apply/funds/templates/funds/tables/table.html
Labels: Type: Bug, Type: Patch

#2610 PM can request modifications to fixed-price invoice
  hypha/apply/activity/messaging.py
  hypha/apply/activity/templates/messages/email/invoice_status_updated.html
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/tests/test_templatetags.py
  hypha/apply/projects/views/payment.py
  hypha/apply/users/models.py
Labels: Type: Enhancement, Type: Minor

#2635 Remove all parts of ProjectApproval StreamForm
  hypha/apply/funds/migrations/0089_remove_project_approval_form_refrences.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/tests/factories/models.py
  hypha/apply/funds/tests/test_admin_form.py
  hypha/apply/home/migrations/0002_add_apply_homepage.py
  hypha/apply/projects/admin.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/migrations/0042_delete_project_approval_form.py
  hypha/apply/projects/migrations/0043_remove_project_approval_form.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/views/project.py
Labels: Type: Maintenance, Type: Minor

#2636 Add login redirect for private pages
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/views.py
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Minor

#2654 codeql-analysis - Update branch to main and remove scheduling.
  .github/workflows/codeql-analysis.yml
Labels: Type: Maintenance, Type: Patch
