Repository HyphaApp/hypha, pull requests merged in 2021-05, with the labels that each got.

#2353 Updated to Django 2.2.21.
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2126 Add investments table and partners page
  hypha/apply/funds/tables.py
  hypha/public/partner/__init__.py
  hypha/public/partner/admin.py
  hypha/public/partner/admin_view.py
  hypha/public/partner/apps.py
  hypha/public/partner/migrations/0001_add_investments_table_and_partners_page.py
  hypha/public/partner/migrations/__init__.py
  hypha/public/partner/models.py
  hypha/public/partner/tables.py
  hypha/public/partner/templates/partner/base_investments_table.html
  hypha/public/partner/templates/partner/includes/table_filter_and_search.html
  hypha/public/partner/templates/partner/investments.html
  hypha/public/partner/templates/partner/partner_page.html
  hypha/public/partner/templates/partner/table.html
  hypha/public/partner/views.py
  hypha/public/urls.py
  hypha/settings/base.py
  hypha/static_src/src/javascript/public/all-investments-table.js
  hypha/static_src/src/javascript/public/investment-filters.js
  hypha/static_src/src/javascript/public/investment-tooltips.js
  hypha/static_src/src/sass/public/abstracts/_mixins.scss
  hypha/static_src/src/sass/public/abstracts/_variables.scss
  hypha/static_src/src/sass/public/components/_actions-bar.scss
  hypha/static_src/src/sass/public/components/_all-investments-table.scss
  hypha/static_src/src/sass/public/components/_button.scss
  hypha/static_src/src/sass/public/components/_filters.scss
  hypha/static_src/src/sass/public/components/_form.scss
  hypha/static_src/src/sass/public/components/_input.scss
  hypha/static_src/src/sass/public/components/_investment-meta.scss
  hypha/static_src/src/sass/public/components/_table.scss
  hypha/static_src/src/sass/public/main.scss
Labels: Type: Feature, Type: Minor

#2357 Updated to Django 2.2.22.
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2376 Updated to Django 2.2.23.
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2380 Node package updates.
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Patch

#2334 Add Reminders in React
  hypha/apply/activity/templates/messages/email/ready_to_review.html
  hypha/apply/api/v1/reminder/serializers.py
  hypha/apply/api/v1/reminder/views.py
  hypha/apply/api/v1/urls.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/migrations/0088_auto_20210423_1257.py
  hypha/apply/funds/models/reminders.py
  hypha/apply/funds/templates/funds/includes/create_reminder_form.html
  hypha/apply/funds/templates/funds/includes/reminders_block.html
  hypha/static_src/src/app/src/common/components/DateTime/index.js
  hypha/static_src/src/app/src/common/components/TextBox/index.js
  hypha/static_src/src/app/src/common/components/Textarea/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/common/components/Textarea/index.js
  hypha/static_src/src/app/src/common/containers/FormContainer/components/FormField/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/common/containers/FormContainer/components/FormField/index.js
  hypha/static_src/src/app/src/common/containers/FormContainer/index.js
  hypha/static_src/src/app/src/containers/DisplayPanel/index.js
  hypha/static_src/src/app/src/containers/FlagContainer/style.scss
  hypha/static_src/src/app/src/containers/ReminderContainer/actions.js
  hypha/static_src/src/app/src/containers/ReminderContainer/components/ReminderList.js
  hypha/static_src/src/app/src/containers/ReminderContainer/components/style.scss
  hypha/static_src/src/app/src/containers/ReminderContainer/constants.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/actions.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/constants.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/index.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/models.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/reducer.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/sagas.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/selectors.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/styles.scss
  hypha/static_src/src/app/src/containers/ReminderContainer/index.js
  hypha/static_src/src/app/src/containers/ReminderContainer/models.js
  hypha/static_src/src/app/src/containers/ReminderContainer/reducer.js
  hypha/static_src/src/app/src/containers/ReminderContainer/sagas.js
  hypha/static_src/src/app/src/containers/ReminderContainer/selectors.js
  hypha/static_src/src/app/src/containers/ReminderContainer/styles.scss
  hypha/static_src/src/sass/apply/components/_reminder-sidebar.scss
  package-lock.json
  package.json
Labels: Type: Enhancement, Type: Minor

#2386 Update python runtime to 3.8.10.
  runtime.txt
Labels: Type: Maintenance, Type: Minor

#2377 Percentage in determined applications.
  hypha/apply/funds/templates/funds/includes/round-block-listing.html
Labels: Type: Enhancement, Type: Patch

#2340 Improve performance of right side column in the React
  hypha/apply/api/v1/serializers.py
  hypha/apply/flags/views.py
  hypha/static_src/src/app/src/containers/ByRoundListing.js
  hypha/static_src/src/app/src/containers/DisplayPanel/index.js
  hypha/static_src/src/app/src/containers/FlagContainer/WithFlagType.js
  hypha/static_src/src/app/src/containers/FlagContainer/actions.js
  hypha/static_src/src/app/src/containers/FlagContainer/index.js
  hypha/static_src/src/app/src/containers/FlagContainer/reducer.js
  hypha/static_src/src/app/src/containers/FlagContainer/sagas.js
  hypha/static_src/src/app/src/containers/ReminderContainer/actions.js
  hypha/static_src/src/app/src/containers/ReminderContainer/components/ReminderList.js
  hypha/static_src/src/app/src/containers/ReminderContainer/constants.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/actions.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/index.js
  hypha/static_src/src/app/src/containers/ReminderContainer/containers/ReminderForm/sagas.js
  hypha/static_src/src/app/src/containers/ReminderContainer/index.js
  hypha/static_src/src/app/src/containers/ReminderContainer/models.js
  hypha/static_src/src/app/src/containers/ReminderContainer/reducer.js
  hypha/static_src/src/app/src/containers/ReminderContainer/sagas.js
  hypha/static_src/src/app/src/containers/ReminderContainer/selectors.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/actions.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/index.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/models.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/sagas.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/action.test.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/index.test.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/reducer.test.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/saga.test.js
  hypha/static_src/src/app/src/redux/actions/submissions.js
  hypha/static_src/src/app/src/redux/reducers/submissions.js
  hypha/static_src/src/app/src/redux/selectors/submissions.js
Labels: Type: Minor

#2393 Create webpack.static.dev config file for local dev
  gulpfile.js
  hypha/static_src/src/app/webpack.static.dev.config.js
Labels: Type: Maintenance, Type: Patch

#2397 enhance: Use is_apply_staff in replacement of is_staff for users
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/approval_tools.py
Labels: Type: Bug, Type: Minor
