Repository HyphaApp/hypha, pull requests merged in 2021-06, with the labels that each got.

#2405 Downgrade python runtime to 3.8.9
  .circleci/config.yml
  runtime.txt
Labels: Type: Maintenance, Type: Patch

#2406 Updated to Django 2.2.24.
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2402 fix: Project table filter's broken dropdown
  hypha/apply/projects/filters.py
Labels: Type: Bug, Type: Patch

#2412 Implement HandleProtectionErrorMiddleware.
  hypha/apply/middleware.py
  hypha/settings/base.py
Labels: Type: Maintenance, Type: Patch

#2413 updating l18n strings in models.py
  hypha/public/funds/models.py
Labels: Type: Maintenance, Type: Patch

#2418 Make labels, help_text etc. strings i18n aware
  hypha/apply/api/v1/filters.py
  hypha/apply/categories/blocks.py
  hypha/apply/categories/models.py
  hypha/apply/determinations/forms.py
  hypha/apply/determinations/models.py
  hypha/apply/determinations/views.py
  hypha/apply/funds/admin_views.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/reviewer_role.py
  hypha/apply/funds/models/screening.py
  hypha/apply/funds/models/utils.py
  hypha/apply/funds/tables.py
  hypha/apply/middleware.py
  hypha/apply/projects/filters.py
  hypha/apply/projects/forms.py
  hypha/apply/projects/tables.py
  hypha/apply/review/templatetags/review_tags.py
  hypha/apply/users/forms.py
  hypha/apply/users/models.py
  hypha/apply/utils/models.py
  hypha/public/forms/models.py
  hypha/public/funds/models.py
  hypha/public/home/blocks.py
  hypha/public/home/models.py
  hypha/public/mailchimp/forms.py
  hypha/public/mailchimp/models.py
  hypha/public/navigation/models.py
  hypha/public/news/blocks.py
  hypha/public/news/models.py
  hypha/public/partner/models.py
  hypha/public/partner/tables.py
  hypha/public/people/models.py
  hypha/public/projects/models.py
  hypha/public/standardpages/models.py
  hypha/public/utils/models.py
Labels: Type: Maintenance, Type: Patch

#2407 Add locale files.
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/settings/base.py
Labels: Type: Maintenance, Type: Patch

#2421 Update Wagtail version 2.13 to 2.13.1
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2422 Add a CURRENCY_SYMBOL setting
  hypha/apply/funds/blocks.py
  hypha/apply/funds/templates/funds/includes/submission_stats.html
  hypha/apply/projects/forms.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/funding_block.html
  hypha/apply/projects/templates/application_projects/includes/payment_requests.html
  hypha/apply/projects/templates/application_projects/paymentrequest_confirm_delete.html
  hypha/apply/projects/templates/application_projects/paymentrequest_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/project_simplified_detail.html
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/public/partner/migrations/0002_currency_symbol_setting.py
  hypha/public/partner/models.py
  hypha/public/partner/tables.py
  hypha/public/partner/templates/partner/partner_page.html
  hypha/public/utils/context_processors.py
  hypha/public/utils/templates/utils/includes/funding.html
  hypha/settings/base.py
Labels: Type: Maintenance, Type: Minor

#2419 Add Timestamp for Upload Documents in Submission Details
  hypha/apply/stream_forms/files.py
  hypha/apply/stream_forms/templates/stream_forms/includes/file_field.html
Labels: Type: Enhancement, Type: Minor

#2410 Add meta terms in react
  hypha/apply/api/v1/serializers.py
  hypha/apply/api/v1/urls.py
  hypha/apply/api/v1/views.py
  hypha/static_src/src/app/src/components/SubmissionMetaTerms/index.js
  hypha/static_src/src/app/src/components/SubmissionMetaTerms/styles.scss
  hypha/static_src/src/app/src/containers/DisplayPanel/index.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/actions.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/components/MetaTermTreeView/index.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/components/MetaTermTreeView/styleTreeView.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/components/MetaTermTreeView/styles.scss
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/constants.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/index.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/models.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/reducer.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/saga.js
  hypha/static_src/src/app/src/containers/MetaTerm/containers/MetaTermForm/selectors.js
  hypha/static_src/src/app/src/containers/MetaTerm/index.js
  hypha/static_src/src/app/src/containers/StatusActions.js
  hypha/static_src/src/app/src/redux/actions/submissions.js
  hypha/static_src/src/app/src/redux/reducers/submissions.js
  hypha/static_src/src/app/src/redux/selectors/submissions.js
Labels: Type: Enhancement, Type: Minor

#2425 Make the workflow state display names translateble.
  hypha/apply/funds/workflow.py
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Enhancement, Type: Minor

#2434 Move currency symbol to table header instead of displaying in every s…
  hypha/apply/funds/templates/funds/includes/submission_stats.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/payment_requests.html
Labels: Type: Enhancement, Type: Patch

#2428 Make messages strings translateble.
  hypha/apply/activity/messaging.py
  hypha/apply/activity/templates/messages/email/applicant_base.html
  hypha/apply/activity/templates/messages/email/base.html
  hypha/apply/activity/templates/messages/email/batch_ready_to_review.html
  hypha/apply/activity/templates/messages/email/comment.html
  hypha/apply/activity/templates/messages/email/contract_uploaded.html
  hypha/apply/activity/templates/messages/email/determination.html
  hypha/apply/activity/templates/messages/email/edit.html
  hypha/apply/activity/templates/messages/email/invited_to_proposal.html
  hypha/apply/activity/templates/messages/email/partners_update_applicant.html
  hypha/apply/activity/templates/messages/email/partners_update_partner.html
  hypha/apply/activity/templates/messages/email/payment_request_status_updated.html
  hypha/apply/activity/templates/messages/email/payment_request_updated.html
  hypha/apply/activity/templates/messages/email/ready_to_review.html
  hypha/apply/activity/templates/messages/email/report_frequency.html
  hypha/apply/activity/templates/messages/email/report_notify.html
  hypha/apply/activity/templates/messages/email/report_skipped.html
  hypha/apply/activity/templates/messages/email/report_submitted.html
  hypha/apply/activity/templates/messages/email/sent_to_compliance.html
  hypha/apply/activity/templates/messages/email/transition.html
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Enhancement, Type: Minor

#2439 fix: Correct slack message for determination
  hypha/apply/activity/messaging.py
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Enhancement, Type: Minor

#2442 Update sandbox db.
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch
