Repository HyphaApp/hypha, pull requests merged in 2021-08, with the labels that each got.

#2467 Update sandbox db.
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch

#2469 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type: Maintenance, Type: Patch

#2466 Fix Applicant Activity Feed(Review)
  hypha/apply/activity/messaging.py
  hypha/apply/activity/models.py
Labels: Type: Bug, Type: Minor

#2474 Always show submission filters. Remove the Filter button in these cases.
  hypha/apply/dashboard/static/js/django_select2-checkboxes.js
  hypha/apply/funds/templates/funds/base_submissions_table.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/projects/templates/application_projects/project_list.html
Labels: Type: Enhancement, Type: Patch

#2483 fix: Submission Filter TypeError: 'classList' of undefined
  hypha/static_src/src/javascript/apply/submission-filters.js
Labels: Type: Bug, Type: Patch

#2450 Update Project Invoicing
  hypha/apply/activity/messaging.py
  hypha/apply/activity/migrations/0057_add_invoices.py
  hypha/apply/activity/migrations/0058_add_project_invoicing.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/invoice_status_updated.html
  hypha/apply/activity/templates/messages/email/invoice_updated.html
  hypha/apply/projects/filters.py
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/migrations/0037_add_project_invoicing.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/models/vendor.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/payment.py
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Feature, Type: Minor

#2494 Allow PASSWORD_RESET_TIMEOUT_DAYS to be set as an enviroment variable…
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#2499 Change Send/Save button to Submit for Determination
  hypha/apply/determinations/templates/determinations/base_determination_form.html
Labels: Type: Enhancement, Type: Patch

#2497 Add h1 to BLEACH_ALLOWED_TAGS.
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#2489 Traffic light recomendation in submission table
  hypha/apply/review/templatetags/review_tags.py
Labels: Type: Enhancement, Type: Patch

#2486 Make the submission comment form more compact.
  hypha/apply/activity/forms.py
  hypha/apply/activity/migrations/0059_rename_team_staff.py
  hypha/apply/activity/models.py
  hypha/apply/activity/templates/activity/include/comment_form.html
  hypha/apply/templates/forms/includes/field.html
  hypha/static_src/src/javascript/apply/submission-filters.js
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/apply/components/_grid.scss
Labels: Type: Enhancement, Type: Patch

#2490 Change dataformat to relative and sort to date descending for determination block.
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/determinations/models.py
  hypha/apply/determinations/templates/determinations/includes/applicant_determination_block.html
  hypha/apply/determinations/templates/determinations/includes/determination_block.html
  hypha/apply/funds/templates/funds/includes/review_sidebar_item.html
  hypha/apply/funds/templates/funds/includes/round-block-listing.html
  hypha/apply/funds/templates/funds/tables/table.html
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/public/news/templates/news/news_index.html
Labels: Type: Enhancement, Type: Minor

#2504 Remove order_by from get query for draft determinations.
  hypha/apply/determinations/models.py
Labels: Type: Bug, Type: Patch

#2508 Use Invalid elements attribute of tinymce to validate input
  hypha/apply/utils/options.py
Labels: Type: Bug, Type: Patch

#2518 Disable tinymce contextmenu
  hypha/apply/utils/options.py
Labels: Type: Enhancement, Type: Patch
