Repository HyphaApp/hypha, pull requests merged in 2022-02, with the labels that each got.

#2700 Update to Django 2.2.27.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2702 Update to latest django-hijack and remove loading of removed hijack-styles.css
  hypha/templates/base-apply.html
  requirements.txt
Labels: Type: Bug, Type: Patch

#2715 Correctly validate Slack field as optional
  hypha/apply/users/views.py
Labels: Type: Bug, Type: Patch

#2713 Parse locale for currency lookup with dash separator
  hypha/apply/projects/forms/vendor.py
Labels: Type: Bug, Type: Patch

#2711 Upgrade jest to latest version
  hypha/static_src/src/app/src/common/components/CheckBox/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/common/components/DropDown/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/common/components/FilterDropDown/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/common/components/Radio/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/common/components/TextBox/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/common/components/Textarea/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/common/containers/FormContainer/components/FormField/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/components/MessageBar/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/components/NoteListingItem/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/components/Select/__tests__/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/components/__tests__/__snapshots__/ListingItem.test.js.snap
  hypha/static_src/src/app/src/containers/DeterminationForm/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/GeneralInfo/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/ReviewForm/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/SubmissionFilters/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/__tests__/__snapshots__/MessagesContainer.test.js.snap
  jest.config.js
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Minor

#2710 Add Finance flow fixes and notifications
  hypha/apply/activity/messaging.py
  hypha/apply/api/v1/permissions.py
  hypha/apply/api/v1/projects/views.py
  hypha/apply/dashboard/views.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/includes/deliverables_block.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/views/project.py
  hypha/apply/users/forms.py
  hypha/apply/users/models.py
Labels: Type: Feature, Type: Minor

#2719 Ensure errors are on top
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/public/components/_form.scss
Labels: Type: Bug, Type: Patch

#2727 Add collectstatic step to CI.
  .circleci/config.yml
Labels: Type: Maintenance, Type: Patch

#2701 Use environs package to parse .env variables.
  hypha/settings/base.py
  hypha/settings/production.py
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2732 Environs env.url() returns a URL object so replace with env.str()
  hypha/settings/base.py
  hypha/settings/production.py
Labels: Type: Bug, Type: Patch

#2728 Hide admin button for users without admin access
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/tests/test_views.py
  hypha/apply/users/tests/factories.py
Labels: Type: Enhancement, Type: Minor

#2730 Fix review sidebar item widths
  hypha/static_src/src/app/src/components/ReviewBlock/index.js
  hypha/static_src/src/sass/apply/components/_reviews-sidebar.scss
Labels: Type: Enhancement, Type: Patch

#2737 Replace reviewer toggle label
  hypha/apply/funds/templates/funds/includes/review_sidebar.html
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/static_src/src/javascript/apply/toggle-reviewers.js
Labels: Type: Enhancement, Type: Patch

#2739 Upgrade to mistune2.0.2
  hypha/apply/api/v1/serializers.py
  hypha/apply/funds/templatetags/markdown_tags.py
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2705 Add tests for invoice finance flow
  hypha/apply/api/v1/projects/views.py
  hypha/apply/api/v1/tests/test_serializers.py
  hypha/apply/api/v1/tests/test_views.py
  hypha/apply/api/v1/urls.py
  hypha/apply/projects/migrations/0014_add_payment_related_models.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/users/tests/factories.py
Labels: Type: Maintenance, Type: Patch

#2741 Fix column orders
  hypha/apply/funds/tables.py
Labels: Type: Enhancement, Type: Patch

#2678 Update to Django 3.2.12
  hypha/apply/activity/models.py
  hypha/apply/categories/admin.py
  hypha/apply/categories/apps.py
  hypha/apply/dashboard/apps.py
  hypha/apply/determinations/admin.py
  hypha/apply/determinations/apps.py
  hypha/apply/determinations/forms.py
  hypha/apply/determinations/migrations/0011_auto_20220111_1314.py
  hypha/apply/determinations/models.py
  hypha/apply/flags/views.py
  hypha/apply/funds/admin.py
  hypha/apply/funds/apps.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/migrations/0090_auto_20220111_1314.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/utils.py
  hypha/apply/funds/widgets.py
  hypha/apply/projects/migrations/0047_alter_project_form_data.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/models/project.py
  hypha/apply/review/admin.py
  hypha/apply/review/apps.py
  hypha/apply/review/migrations/0024_auto_20220111_1314.py
  hypha/apply/review/models.py
  hypha/apply/stream_forms/apps.py
  hypha/apply/stream_forms/fields.py
  hypha/apply/users/admin_views.py
  hypha/apply/users/utils.py
  hypha/apply/users/views.py
  hypha/apply/users/wagtail_hooks.py
  hypha/cookieconsent/apps.py
  hypha/public/mailchimp/apps.py
  hypha/public/partner/apps.py
  hypha/public/people/wagtail_hooks.py
  hypha/public/projects/apps.py
  hypha/public/utils/wagtail_hooks.py
  hypha/settings/base.py
  hypha/urls.py
  requirements.txt
Labels: Type: Maintenance, Type: Major
