Repository HyphaApp/hypha, pull requests merged in 2022-05, with the labels that each got.

#2833 Add env variable to turn hijack/become feature on/off
  hypha/apply/users/tests/test_views.py
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
  hypha/settings/base.py
  hypha/settings/test.py
Labels: Type: Enhancement, Type: Minor

#2840 Update overridden users index view to support groups/[gid]/users/ view.
  hypha/apply/users/admin_views.py
  hypha/apply/users/templates/wagtailusers/users/results.html
  hypha/apply/users/wagtail_hooks.py
Labels: Type: Bug, Type: Minor

#2831 Add 'External Reviewer' picklist option to the batch action
  hypha/apply/funds/forms.py
Labels: Type: Enhancement, Type: Minor

#2844 Populate Determination message from Detemination message template
  hypha/apply/determinations/migrations/0012_auto_20220509_1136.py
  hypha/apply/determinations/models.py
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/determinations/views.py
  hypha/static_src/src/javascript/apply/determination-template.js
Labels: Type: Enhancement, Type: Minor

#2843 Add a feature in wagtail admin to reset 2fa for a user
  hypha/apply/users/templates/two_factor/admin/disable.html
  hypha/apply/users/templates/wagtailusers/users/edit.html
  hypha/apply/users/templatetags/users_tags.py
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
Labels: Type: Enhancement, Type: Minor

#2845 Implement setting GIVE_STAFF_LEAD_PERMS so staff can be given permiss…
  hypha/apply/funds/forms.py
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Minor

#2849 Exclude draft submissions from submissions results.
  hypha/apply/funds/management/commands/export_submissions_csv.py
  hypha/apply/funds/views.py
Labels: Type: Bug, Type: Patch

#2859 Install npm global so not replaced with volume mount.
  docker/Dockerfile.dev
Labels: Type: Bug, Type: Patch

#2860 Move npm install command to entrypoint script.
  docker/Dockerfile.dev
  docker/entrypoint.dev.sh
Labels: Type: Bug, Type: Patch

#2866 Update resource_class to large for CircleCI jobs
  .circleci/config.yml
Labels: Type: Maintenance, Type: Patch

#2863 Fix e-mail variables that got mangled during the translation push
  hypha/apply/activity/templates/messages/email/applicant_base.html
  hypha/apply/activity/templates/messages/email/base.html
  hypha/apply/activity/templates/messages/email/invited_to_proposal.html
  hypha/apply/funds/templates/funds/email/confirmation.html
  hypha/apply/users/templates/users/activation/email.txt
  hypha/apply/users/templates/users/email_change/confirm_email.txt
  hypha/apply/users/templates/users/password_reset/email.txt
  hypha/apply/users/utils.py
  hypha/public/utils/context_processors.py
Labels: Type: Bug, Type: Minor
