Repository HyphaApp/hypha, pull requests merged in 2022-09, with the labels that each got.

#2969 Updated the sandbox db.
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch

#2970 Update the po files.
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#2974 Remove reviewers from list who opinionated but didn't submit review
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/tests/test_models.py
Labels: Type: Bug, Type: Patch

#2944 Add correction and amendments link to contracting phase
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/static_src/src/sass/apply/components/_icon.scss
  hypha/templates/includes/sprites.html
Labels: Type: Enhancement, Type: Patch

#2952 Upgrade to python 3.10.
  .circleci/config.yml
  docker/Dockerfile.dev
  runtime.txt
Labels: Type: Maintenance, Type: Patch

#2966 Make project approval form similar like ApplicationForms or Reviews Forms
  hypha/apply/funds/migrations/0102_add_projectapprovalform_to_fundbase_labbase.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/forms.py
  hypha/apply/funds/models/utils.py
  hypha/apply/funds/tests/factories/models.py
  hypha/apply/funds/tests/test_admin_form.py
  hypha/apply/funds/tests/test_admin_views.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Type: Minor

#2977 Attached forms displayed in the rounds admin page fix
  hypha/apply/funds/edit_handlers.py
  hypha/apply/funds/models/applications.py
  hypha/core/__init__.py
  hypha/core/templates/core/wagtail/panels/inline_panel_readonly.html
  hypha/core/wagtail/__init__.py
  hypha/core/wagtail/admin/panels.py
  hypha/settings/base.py
Labels: Type: Bug, Type: Minor

#2984 Upgrade django-file-field to 3.4.1
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2979 Fix PAF admin's related forms issues
  hypha/apply/projects/admin.py
Labels: Type: Bug, Type: Patch

#2983 Add a SUBMISSIONS_DRAFT_ACCESS_STAFF to control if staff can see application draft or not
  hypha/apply/funds/views.py
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#2978 Rename Screening Status to Screening Decision
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/api/v1/screening/tests/test_views.py
  hypha/apply/api/v1/screening/views.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/migrations/0103_alter_screeningstatus.py
  hypha/apply/funds/models/screening.py
  hypha/apply/funds/templates/funds/includes/screening_form.html
  hypha/apply/funds/templates/funds/includes/screening_status_block.html
  hypha/apply/funds/templates/funds/tables/table.html
  hypha/apply/funds/tests/test_forms.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/utils.py
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/static_src/src/app/src/containers/ScreeningStatus/index.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/__snapshots__/index.test.js.snap
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/action.test.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/index.test.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/reducer.test.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/saga.test.js
  hypha/static_src/src/app/src/containers/ScreeningStatus/tests/selectors.test.js
  hypha/static_src/src/javascript/apply/screening-status.js
Labels: Type: Enhancement, Type: Patch

#2976 Notify final Approver when PAF is ready for final Approval
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/migrations/0064_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
  hypha/apply/users/models.py
Labels: Type: Enhancement, Type: Patch

#2990 Move django settings to seperate file and reorder settings in base file.
  hypha/settings/base.py
  hypha/settings/django.py
Labels: Type: Maintenance, Type: Patch
