Repository HyphaApp/hypha, pull requests merged in 2022-10, with the labels that each got.

#2980 Move SendNoticeBlock to required blocks
  hypha/apply/determinations/blocks.py
  hypha/apply/determinations/migrations/0014_alter_determination_formfield_send_notice.py
  hypha/apply/determinations/tests/test_admin_views.py
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#2993 Improve the look of SingleIncludeBlock's static field
  hypha/apply/funds/blocks.py
  hypha/apply/utils/blocks.py
Labels: Type: Enhancement, Type: Patch

#2963 Add error message for PAF not configured condition
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Type: Patch

#2997 Updated to Django 3.2.16.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2998 Fix some strings that was not translateble.
  hypha/apply/activity/templates/activity/include/comment_form.html
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/activity/templates/activity/include/notifications_dropdown.html
  hypha/apply/dashboard/templates/dashboard/partner_dashboard.html
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/determinations/templates/determinations/determination_form.html
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/funds/templates/funds/includes/no_round_block_dashboard.html
  hypha/apply/funds/templates/funds/includes/revision_diff_table.html
  hypha/apply/funds/templates/funds/includes/round-block-listing.html
  hypha/apply/funds/templates/funds/includes/screening_status_block.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/reviewer_leaderboard.html
  hypha/apply/funds/templates/funds/revisions_compare.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/includes/report_line.html
  hypha/apply/projects/templates/application_projects/includes/required_checks_block.html
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/project_simplified_detail.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/review/templates/review/review_edit_form.html
  hypha/apply/templates/forms/includes/field.html
  hypha/apply/users/templates/two_factor/admin/disable.html
  hypha/apply/users/templates/two_factor/core/setup.html
  hypha/apply/users/templates/two_factor/core/setup_complete.html
  hypha/apply/users/templates/users/account.html
  hypha/apply/users/templates/users/login.html
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/templates/blocks/more_block.html
  hypha/templates/includes/relatedcontent_card.html
Labels: Type: Bug, Type: Patch

#3000 Add a templates_custom dir to make it easy to override templates.
  hypha/settings/base.py
  hypha/templates_custom/.gitkeep
Labels: Type: Enhancement, Type: Patch

#3002 Fix missing i18n tag in the fund template
  hypha/templates/blocks/more_block.html
Labels: Type: Bug, Type: Patch

#2942 Add a settings to make finance2 workflow optional
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/users/models.py
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#2989 Make user e-mail field case insensitive to prevent multiple account with same email
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/stream_forms/forms.py
  hypha/apply/users/backends.py
  hypha/apply/users/models.py
  hypha/apply/users/tests/test_utils.py
  hypha/apply/users/urls.py
  hypha/apply/users/utils.py
  hypha/apply/users/views.py
  hypha/settings/django.py
Labels: Type: Bug, Type: Minor

#2995 Enhance Supporting Documents upload
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/migrations/0056_packetfile_created_at.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
Labels: Type: Enhancement, Type: Minor

#2991 Send email digest for activities in Hypha for org level staff
  .vscode/extensions.json
  .vscode/settings.json
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/management/commands/send_staff_email_digest.py
  hypha/apply/activity/migrations/0065_auto_20221006_1115.py
  hypha/apply/activity/models.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/activity_summary.md
  hypha/apply/activity/templates/messages/email/base.html
  hypha/apply/activity/tests/factories.py
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/api/v1/serializers.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templatetags/markdown_tags.py
  hypha/apply/users/wagtail_hooks.py
  hypha/apply/utils/notifications.py
  hypha/core/mail.py
  hypha/core/tests/test_utils.py
  hypha/core/utils.py
  hypha/settings/base.py
  hypha/settings/local.py.example
Labels: Type: Feature, Type: Minor

#3015 Add author name to new submission notification.
  hypha/apply/activity/adapters/slack.py
Labels: Type: Enhancement, Type: Patch
