Repository HyphaApp/hypha, pull requests merged in 2022-04, with the labels that each got.

#2787 Update error messages z-index(css)
  hypha/static_src/src/sass/apply/components/_messages.scss
  hypha/static_src/src/sass/public/components/_messages.scss
Labels: Type: Bug, Type: Patch

#2735 Make duration field optional and set required None for existing data
  hypha/apply/funds/blocks.py
  hypha/apply/funds/migrations/0092_auto_20220308_0827.py
  hypha/apply/funds/migrations/0093_set_duration_false.py
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
Labels: Type: Enhancement, Type: Patch

#2772 Populate "E-mail" and "Full name" on submissions and disable input for the logged in users
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/tests/test_models.py
  hypha/apply/funds/views.py
  hypha/apply/stream_forms/models.py
  hypha/static_src/src/sass/public/components/_form.scss
Labels: Type: Maintenance, Type: Patch

#2797 Remove obsolete information from the application project detail page.
  hypha/apply/projects/templates/application_projects/includes/funding_block.html
  hypha/apply/projects/templates/application_projects/project_detail.html
Labels: Type: Enhancement, Type: Patch

#2796 Hide the status section on public project pages.
  hypha/public/projects/templates/projects/project_page.html
  hypha/static_src/src/sass/apply/components/_icon.scss
  hypha/static_src/src/sass/public/components/_icon.scss
Labels: Type: Enhancement, Type: Patch

#2782 Update required fields error message
  .circleci/config.yml
  hypha/apply/determinations/admin.py
  hypha/apply/determinations/admin_views.py
  hypha/apply/determinations/tests/test_admin_views.py
  hypha/apply/funds/admin.py
  hypha/apply/funds/admin_views.py
  hypha/apply/funds/blocks.py
  hypha/apply/funds/migrations/0094_auto_20220406_0800.py
  hypha/apply/funds/tests/test_admin_views.py
  hypha/apply/review/admin.py
  hypha/apply/review/admin_views.py
  hypha/apply/review/tests/test_admin_views.py
  hypha/apply/utils/blocks.py
Labels: Type: Enhancement, Type: Minor

#2801 Update to Django 3.2.13.
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2802 Pin the bleach package to 4.1.0.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2799 Add filters for role and status, customize templates and add bulk action feature for users
  hypha/apply/users/admin_views.py
  hypha/apply/users/templates/wagtailusers/users/index.html
  hypha/apply/users/templates/wagtailusers/users/list.html
  hypha/apply/users/templates/wagtailusers/users/results.html
  hypha/static_src/src/sass/apply/wagtail_users_list.scss
Labels: Type: Enhancement, Type: Patch

#2795 Invoice flow improvements
  hypha/apply/activity/messaging.py
  hypha/apply/dashboard/views.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/migrations/0050_add_new_invoice_status.py
  hypha/apply/projects/migrations/0051_remove_unnecessary_fields_from_invoice.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
Labels: Status: Needs testing

#2806 Add a check for blocks without child blocks like groups end block
  hypha/apply/utils/blocks.py
Labels: Type: Bug, Type: Patch

#2808 Password reset timeout in seconds but show in days
  hypha/apply/users/utils.py
  hypha/apply/users/views.py
Labels: Type: Bug, Type: Patch

#2804 Enforce 2FA for all users: add env variable and middleware
  hypha/apply/users/middleware.py
  hypha/apply/users/templates/two_factor/core/two_factor_required.html
  hypha/apply/users/tests/test_middleware.py
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
  hypha/settings/base.py
Labels: Type: Feature, Type: Minor

#2826 Use trimmed on blocktrans
  hypha/apply/users/templates/two_factor/core/backup_tokens.html
  hypha/apply/users/templates/two_factor/core/backup_tokens_password.html
  hypha/apply/users/templates/two_factor/profile/disable.html
  hypha/apply/users/templates/two_factor/profile/profile.html
  hypha/apply/users/templates/users/change_password.html
  hypha/apply/users/templates/users/email_change/confirm_password.html
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/templates/users/password_reset/confirm.html
Labels: Type: Enhancement, Type: Patch

#2813 Improve External reviewers label
  hypha/apply/funds/forms.py
Labels: Type: Enhancement, Type: Patch

#2818 Add option to allow reviewers to only see submissions in external review status
  hypha/apply/funds/migrations/0095_only_external_review_option.py
  hypha/apply/funds/models/reviewer_role.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/workflow.py
Labels: Type: Enhancement, Status: RTBC, Type: Minor

#2810 Update node packages. Update sass-loader options after update.
  hypha/static_src/src/app/webpack.base.config.js
  package-lock.json
  package.json
Labels: Status: RTBC, Type: Maintenance, Type: Minor

#2827 Filter reviewer dashboard tables by ReviewerSettings
  hypha/apply/dashboard/views.py
Labels: Type: Bug, Status: RTBC, Type: Minor
