Repository HyphaApp/hypha, pull requests merged in 2022-06, with the labels that each got.

#2851 Add External Review Form block to fund, for external reviewers
  hypha/apply/funds/admin_forms.py
  hypha/apply/funds/migrations/0097_applicationbaseexternalreviewform_labbaseexternalreviewform_roundbaseexternalreviewform.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/forms.py
  hypha/apply/funds/models/utils.py
  hypha/apply/funds/tests/test_admin_form.py
  hypha/apply/funds/tests/test_admin_views.py
  hypha/apply/review/views.py
Labels: Type: Feature, Type: Minor

#2857 Exclude draft submissions from API calls
  hypha/apply/api/v1/filters.py
  hypha/apply/api/v1/views.py
Labels: Type: Enhancement, Type: Patch

#2872 Improve the text on the password reset form
  hypha/apply/users/templates/users/password_reset/form.html
Labels: Type: Enhancement, Type: Patch

#2879 Make the form help link text translateble.
  hypha/apply/templates/forms/includes/field.html
Labels: Type: Bug, Type: Patch

#2885 Add a extra sass file for easy variable override
  hypha/static_src/src/sass/apply/custom/_extra.scss
  hypha/static_src/src/sass/apply/main.scss
  hypha/static_src/src/sass/public/custom/_extra.scss
  hypha/static_src/src/sass/public/main.scss
Labels: Type: Enhancement, Type: Patch

#2773 Update notifications to applicants
  hypha/apply/activity/templates/messages/email/applicant_base.html
  hypha/apply/activity/templates/messages/email/invited_to_proposal.html
  hypha/apply/activity/templates/messages/email/transition.html
  hypha/apply/funds/templates/funds/email/confirmation.html
  hypha/apply/users/templates/users/activation/email.txt
  hypha/public/utils/context_processors.py
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Minor

#2865 Improve 2FA workflow usability
  hypha/apply/users/templates/two_factor/_wizard_actions.html
  hypha/apply/users/templates/two_factor/core/backup_tokens.html
  hypha/apply/users/templates/two_factor/core/backup_tokens_password.html
  hypha/apply/users/templates/two_factor/core/setup.html
  hypha/apply/users/templates/two_factor/core/setup_complete.html
  hypha/apply/users/templates/two_factor/core/two_factor_required.html
  hypha/apply/users/templates/two_factor/profile/disable.html
  hypha/apply/users/templates/two_factor/profile/profile.html
  hypha/apply/users/templates/users/account.html
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/templatetags/users_tags.py
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
  hypha/settings/base.py
  hypha/static_src/src/sass/apply/components/_button.scss
  hypha/static_src/src/sass/apply/components/_two-factor.scss
  hypha/static_src/src/sass/public/components/_link.scss
  requirements.txt
Labels: Type: Enhancement, Type: Minor

#2867 Integrate django-slack for direct slack messaging from hypha
  hypha/apply/activity/messaging.py
  hypha/apply/activity/templates/messages/slack_message.html
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/utils/notifications.py
  hypha/settings/base.py
  requirements.txt
Labels: Type: Feature, Type: Minor

#2894 Remove period and add missing link in Slack templates
  hypha/apply/activity/messaging.py
Labels: Type: Enhancement, Type: Patch

#2893 Move confirmation mail template to where all other mail templates are…
  hypha/apply/activity/messaging.py
  hypha/apply/activity/migrations/0063_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/submission_confirmation.html
  hypha/apply/activity/templates/messages/email/submission_edit.html
  hypha/apply/funds/views.py
Labels: Type: Maintenance, Type: Patch
