Repository HyphaApp/hypha, pull requests merged in 2022-03, with the labels that each got.

#2750 Remove old Vagrant files. Not updated in years since no one is using …
  Vagrantfile
  hypha/settings/dev.py
  vagrant/provision.sh
Labels: Type: Maintenance, Type: Patch

#2749 Update to Wagtail 2.16.1.
  hypha/apply/funds/tests/test_admin_views.py
  hypha/settings/base.py
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#2763 Correcting the label and help text on category block/field.
  hypha/apply/categories/blocks.py
  hypha/apply/funds/migrations/0091_category_block_label.py
Labels: Type: Bug, Type: Patch

#2762 Make the option "Leave blank to use the default Category label" working on view
  hypha/apply/categories/blocks.py
Labels: Type: Bug, Type: Patch

#2748 Remove gulp and upgrade webpack
  .circleci/config.yml
  docker/Dockerfile.dev
  docker/entrypoint.dev.sh
  gulpfile.js
  hypha/static_src/src/app/webpack.base.config.js
  hypha/static_src/src/app/webpack.dev.config.js
  hypha/static_src/src/app/webpack.prod.config.js
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Minor

#2776 Add missing concurrently npm dev package.
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Patch

#2778 Restrict the html tags in mistune by setting escape as False
  hypha/apply/api/v1/serializers.py
  hypha/apply/funds/templatetags/markdown_tags.py
Labels: Type: Bug, Type: Patch

#2568 Sage IntAcct Integration
  .gitignore
  hypha/apply/projects/migrations/0049_add_fields_for_finance_integrations.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/services/sageintacct/__init__.py
  hypha/apply/projects/services/sageintacct/exceptions.py
  hypha/apply/projects/services/sageintacct/sageintacctsdk.py
  hypha/apply/projects/services/sageintacct/utils.py
  hypha/apply/projects/services/sageintacct/wrapper/__init__.py
  hypha/apply/projects/services/sageintacct/wrapper/api_base.py
  hypha/apply/projects/services/sageintacct/wrapper/constants.py
  hypha/apply/projects/services/sageintacct/wrapper/invoice.py
  hypha/apply/projects/services/sageintacct/wrapper/project.py
  hypha/apply/projects/services/sageintacct/wrapper/purchasing.py
  hypha/apply/projects/templates/application_projects/includes/deliverables_block.html
  hypha/apply/projects/templates/application_projects/includes/required_checks_block.html
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/payment.py
  hypha/settings/base.py
  requirements.txt
Labels: Type: Feature, Type: Minor

#2779 Matomo settings was by mistake made in to bool, revert them back to str.
  hypha/settings/base.py
Labels: Type: Bug, Type: Patch

#2781 USe both requirements-dev and requirements for cache key.
  .circleci/config.yml
Labels: Type: Maintenance, Type: Patch

#2785 Fix change email error
  hypha/apply/users/forms.py
  hypha/apply/users/tests/test_forms.py
Labels: Type: Bug, Type: Patch
