Repository HyphaApp/hypha, pull requests merged in 2022-11, with the labels that each got.

#3006 Show invoices in seperate tabs to finance for their review and conversion
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/projects/models/payment.py
Labels: Type: Enhancement, Type: Patch

#3007 Add PAF awaiting approval table to staff dashboard
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/tests/test_views.py
  hypha/apply/dashboard/views.py
Labels: Type: Enhancement, Type: Patch

#3012 Add PAF final approval table to contracting-approver dashboard
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/users/models.py
Labels: Type: Enhancement, Type: Patch

#3014 Add setting to allow staff admins to view submission drafts.
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/views.py
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#3008 Create “Public Site” setting menu and restructure apply/project menu
  hypha/apply/determinations/admin.py
  hypha/apply/determinations/models.py
  hypha/apply/funds/admin.py
  hypha/apply/funds/models/__init__.py
  hypha/apply/projects/admin.py
  hypha/apply/projects/models/__init__.py
  hypha/cookieconsent/models.py
  hypha/core/wagtail/admin/__init__.py
  hypha/core/wagtail/admin/options.py
  hypha/core/wagtail/admin/registry.py
  hypha/core/wagtail_hooks.py
  hypha/public/mailchimp/models.py
  hypha/public/navigation/models.py
  hypha/public/news/models.py
  hypha/public/partner/models.py
  hypha/public/utils/models.py
Labels: Type: Enhancement, Type: Minor

#3043 Code style fixes and missing migrations
  hypha/apply/determinations/admin.py
  hypha/apply/determinations/migrations/0015_alter_determinationformsettings_options.py
  hypha/apply/funds/admin.py
  hypha/apply/funds/models/__init__.py
  hypha/apply/projects/admin.py
  hypha/core/wagtail/admin/registry.py
  hypha/public/navigation/models.py
  hypha/public/news/models.py
  hypha/public/utils/migrations/0006_alter_systemmessagessettings_options.py
  hypha/public/utils/models.py
Labels: Type: Maintenance, Type: Patch

#3044 Update api tests for Invoice extended workflow
  hypha/apply/api/v1/tests/test_views.py
Labels: Type: Bug, Type: Patch

#3025 Improving table titles on dashboard and overview
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/submissions-waiting-for-review.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/tests/test_views.py
  hypha/apply/funds/templates/funds/submissions_awaiting_review.html
Labels: Type: Enhancement, Type: Patch

#3037 Add PDF template, with custom styling and context
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
  requirements.txt
Labels: Type: Enhancement, Type: Minor

#3063 Node: [hash] is now [fullhash]
  hypha/static_src/src/app/webpack.base.config.js
Labels: Type: Bug, Type: Patch

#3061 Fix permission view for wagtail user groups
  hypha/core/wagtail/admin/options.py
Labels: Type: Bug, Type: Patch

#3039 Add feature to download paf as docx file
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/templates/application_projects/project_simplified_detail.html
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project.py
  hypha/static_src/src/javascript/apply/dropdown.js
  hypha/static_src/src/sass/apply/components/_dropdown.scss
  hypha/static_src/src/sass/apply/components/_simplified.scss
  hypha/static_src/src/sass/apply/main.scss
  hypha/static_src/src/sass/apply/styleguide.scss
  requirements.txt
Labels: Type: Feature, Type: Minor

#3054 Add show deadline setting to Funds. Hide deadline on all public pages.
  hypha/apply/funds/migrations/0104_show_deadline.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/home/templates/apply_home/includes/apply_listing.html
  hypha/public/funds/templates/public_funds/includes/fund_apply_cta.html
  hypha/public/utils/templates/utils/listing_index.html
  hypha/templates/includes/relatedcontent_card.html
Labels: Type: Enhancement, Type: Minor

#3068 Updating to jQuery 3.6.1.
  hypha/static_src/src/javascript/jquery.min.js
Labels: Type: Maintenance, Type: Patch
