Repository HyphaApp/hypha, pull requests merged in 2022-08, with the labels that each got.

#2939 Add conf file for DSLR (spiritual successor to Stellar).
  dslr.toml
Labels: Type: Maintenance, Type: Patch

#2941 Update to Django 3.2.15.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2945 Fix adaptors * imports, make values of __all__ string
  hypha/apply/activity/adapters/__init__.py
Labels: Type: Bug, Type: Patch

#2947 Improve sample generator for help_text in factories
  hypha/apply/stream_forms/testing/factories.py
Labels: Type: Maintenance, Type: Patch

#2950 Fix duplicate comments in in-app feed
  hypha/apply/activity/context_processors.py
  hypha/apply/activity/views.py
  hypha/apply/projects/templates/application_projects/project_detail.html
Labels: Type: Bug, Type: Patch

#2951 Add js validation for acceptable file types for all uploads
  hypha/apply/funds/files.py
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/templates/application_projects/vendor_form.html
  hypha/apply/projects/templates/application_projects/vendor_success.html
  hypha/static_src/src/javascript/apply/list-input-files.js
  requirements.txt
Labels: Type: Bug, Type: Minor

#2956 Upgrade sentry-sdk to v1.9.5
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2954 Improve testing and development experience
  .circleci/config.yml
  .gitignore
  .nvmrc
  Makefile
  hypha/settings/test.py
  requirements-dev.txt
  setup.cfg
Labels: Type: Maintenance, Type: Patch

#2961 Rename Forms to Application forms.
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/utils.py
Labels: Type: Bug, Type: Patch

#2962 Replace stellar with dslr for fast postgres snapshots.
  requirements-dev.txt
Labels: Type: Maintenance, Type: Patch
