Repository HyphaApp/hypha, pull requests merged in 2022-07, with the labels that each got.

#2900 Update to Django 3.2.14.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2905 Check if related page exist before trying to render it.
  hypha/templates/includes/relatedcontent_card.html
Labels: Type: Bug, Type: Patch

#2800 Fix Group field's bugs
  hypha/apply/funds/migrations/0099_auto_20220629_1339.py
  hypha/apply/projects/migrations/0052_alter_project_form_fields.py
  hypha/apply/stream_forms/blocks.py
Labels: Type: Bug, Type: Patch

#2903 Align the ordering of the filterns with the columns on submission table
  hypha/apply/funds/tables.py
Labels: Type: Enhancement, Type: Patch

#2888 Upgrade Django bleach to 3.x and bleach to 5.x
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#2896 Improvements to form fields
  hypha/apply/templates/forms/includes/field.html
  hypha/static_src/src/javascript/apply/application-form.js
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/normalize.scss
  hypha/static_src/src/sass/public/components/_form.scss
  hypha/static_src/src/sass/public/components/_link.scss
Labels: Type: Enhancement, Type: Patch

#2674 Give finance and contracting roles access to the submission detail views
  hypha/apply/funds/views.py
Labels: Type: Enhancement, Type: Patch

#2892 Implementing in-app notification
  hypha/apply/activity/context_processors.py
  hypha/apply/activity/filters.py
  hypha/apply/activity/models.py
  hypha/apply/activity/templates/activity/include/notifications_dropdown.html
  hypha/apply/activity/templates/activity/notifications.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/activity/urls.py
  hypha/apply/activity/views.py
  hypha/settings/base.py
  hypha/static_src/src/javascript/apply/notifications.js
  hypha/static_src/src/sass/apply/components/_activity-notifications.scss
  hypha/static_src/src/sass/apply/components/_feed.scss
  hypha/static_src/src/sass/apply/main.scss
  hypha/templates/base-apply.html
  hypha/templates/includes/sprites.html
Labels: Type: Feature, Type: Minor

#2928 Remove project settings from dev.
  hypha/settings/dev.py
Labels: Type: Bug, Type: Patch

#2931 Add gitignores for VSCode Editor
  .gitignore
  .vscode/settings.json
Labels: Type: Maintenance, Type: Patch

#2933 Fix .editorconfig for Makefile & markdown
  .editorconfig
Labels: Type: Maintenance, Type: Patch

#2932 Refractor to serve JS locally
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/base_submissions_table.html
  hypha/apply/funds/templates/funds/grouped_application_list.html
  hypha/apply/funds/templates/funds/rounds.html
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/overview.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/public/partner/templates/partner/base_investments_table.html
  hypha/static_src/src/javascript/apply/jquery.fancybox.min.js
  hypha/static_src/src/javascript/apply/symbol-es6.min.js
  hypha/static_src/src/javascript/apply/url-search-params.js
Labels: Type: Maintenance, Type: Patch
