Repository HyphaApp/hypha, pull requests merged in 2023-03, with the labels that each got.

#3264 [Docs] Re-write the local setup guide, remove the gunicorn/nginx setup
  .vscode/launch.json
  docs/getting-started/development/manual.md
  docs/setup/deployment/index.md
  mkdocs.yml
Labels: Type: Patch, Type: Documentation

#3257 Improve number input field validation
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/public/components/_form.scss
  hypha/templates/base-apply.html
  hypha/templates/base.html
  hypha/templates/django/forms/widgets/number.html
Labels: Type: Enhancement, Type: Patch

#3249 Restructured Paf reviewer roles flow with actual user groups and actual users as approvers
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/migrations/0070_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/paf_for_approval.html
  hypha/apply/dashboard/tests/test_views.py
  hypha/apply/dashboard/views.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/migrations/0062_auto_20230228_1218.py
  hypha/apply/projects/migrations/0063_projectsettings_paf_approval_sequential.py
  hypha/apply/projects/migrations/0064_alter_pafapprovals_options.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templatetags/approval_tools.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
Labels: Type: Feature, Type: Minor

#3182 Add contracting projects to contracting members dashboard
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/templates/messages/email/ready_for_contracting.html
  hypha/apply/activity/templates/messages/email/ready_for_invoicing.html
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/projects_in_contracting.html
  hypha/apply/dashboard/views.py
  hypha/apply/projects/models/project.py
Labels: Type: Enhancement, Type: Minor

#3241 Remove old unused stuff
  .gitignore
  .test_durations
  docs/getting-started/architecture.md
  docs/index.md
  docs/setup/administrators/configuration.md
  hypha/apply/projects/forms/report.py
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/public/utils/context_processors.py
  hypha/settings/base.py
  hypha/settings/django.py
  hypha/static_src/src/javascript/tracking.js
  hypha/templates/base-apply.html
  hypha/templates/base.html
  requirements.txt
  stellar.yaml
Labels: Type: Maintenance, Type: Patch

#3211 Notify applicant on project creation
  hypha/apply/funds/views.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Type: Minor

#3262 Email on admin account creation
  hypha/apply/users/wagtail_hooks.py
Labels: Status: RTBC, Type: Feature, Type: Patch

#3252 Fix user objects not linked in slack and email messages
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/users/models.py
Labels: Type: Bug, Type: Patch

#3274 Refractor models/submissions.py
  hypha/apply/funds/files.py
  hypha/apply/funds/models/__init__.py
  hypha/apply/funds/models/application_revisions.py
  hypha/apply/funds/models/assigned_reviewers.py
  hypha/apply/funds/models/mixins.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/stream_forms/models.py
Labels: Type: Maintenance, Type: Minor

#3279 Add sentry guide + sentry performance monitoring setup
  docs/setup/administrators/configuration.md
  docs/setup/administrators/setup-error-performance-monitoring.md
  hypha/core/context_processors.py
  hypha/settings/base.py
  hypha/settings/dev.py
  hypha/settings/production.py
  hypha/templates/base-apply.html
  hypha/templates/base.html
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3268 Use bulk_create_reviewers() on submission creation to save some queries.
  hypha/apply/funds/models/assigned_reviewers.py
  hypha/apply/funds/models/submissions.py
Labels: Type: Bug, Type: Patch

#3284 Links in tables changed to blue color with underline
  hypha/static_src/src/sass/apply/components/_all-submissions-table.scss
  hypha/static_src/src/sass/apply/components/_table.scss
Labels: Type: Enhancement, Type: Patch

#3156 Add alternate optional flow where users need to create account and login before applying
  docs/setup/administrators/configuration.md
  hypha/apply/funds/models/applications.py
  hypha/apply/templates/forms/includes/field.html
  hypha/apply/users/forms.py
  hypha/apply/users/models.py
  hypha/apply/users/templates/users/register.html
  hypha/apply/users/tests/test_registration.py
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
  hypha/public/home/templates/home/home_page.html
  hypha/public/utils/context_processors.py
  hypha/public/utils/templates/utils/includes/logout_button.html
  hypha/public/utils/templates/utils/includes/profile_button.html
  hypha/public/utils/templates/utils/includes/register_button.html
  hypha/settings/base.py
  hypha/templates/base.html
Labels: Status: RTBC, Type: Feature, Type: Minor

#3276 Fix editing of review after review form is updated
  hypha/apply/review/models.py
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/review/views.py
Labels: Type: Bug, Type: Minor
