Repository HyphaApp/hypha, pull requests merged in 2023-06, with the labels that each got.

#3425 Add proposal form field to concept determination
  hypha/apply/determinations/forms.py
  hypha/apply/determinations/views.py
  hypha/static_src/src/javascript/apply/determination-template.js
Labels: Type: Enhancement, Type: Patch

#3426 Exclude draft for round submissions on determination % calculation
  hypha/apply/funds/models/applications.py
Labels: Type: Enhancement, Type: Patch

#3429 Filter only active user for user's queryset
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/adapters/utils.py
  hypha/apply/users/models.py
Labels: Type: Bug, Type: Patch

#3438 The open in a new tab SVG icon should be inline on forms
  hypha/static_src/src/sass/apply/components/_form.scss
Labels: Type: Bug, Type: Patch

#3390 Upload button for each project and contract documents categories, Add template to both type of categories
  hypha/apply/projects/admin.py
  hypha/apply/projects/migrations/0076_alter_projectdocument_and_contractdocument_category.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project.py
  hypha/static_src/src/javascript/apply/document-category.js
  hypha/static_src/src/sass/apply/components/_icon.scss
Labels: Type: Feature, Type: Minor

#3453 Advise that docker is not for prod
  docs/setup/deployment/docker.md
Labels: Type: Patch, Type: Documentation

#3451 Read WAGTAILADMIN_BASE_URL from env
  hypha/settings/base.py
Labels: Type: Bug, Type: Patch

#3456 Add question on the register page, if user already have an account
  hypha/apply/users/templates/users/register.html
Labels: Type: Enhancement, Type: Patch
