Repository HyphaApp/hypha, pull requests merged in 2023-04, with the labels that each got.

#3309 Add inline-icon component and add it to svg icon on in listing_base.h…
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/stream_forms/templates/stream_forms/heading_field.html
  hypha/static_src/src/sass/apply/components/_button.scss
  hypha/static_src/src/sass/apply/components/_icon.scss
  hypha/static_src/src/sass/apply/components/_rich-text.scss
Labels: Type: Bug, Type: Patch

#3337 Remove 'Toggle Sidear' button from application submission detail
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_community_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_reviewer_detail.html
  hypha/static_src/src/javascript/apply/toggle-sidebar.js
Labels: Type: Enhancement, Type: Patch

#3338 Refractor reviewer toggle, from jquery to apline js
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_community_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_reviewer_detail.html
  hypha/apply/funds/templates/funds/includes/review_sidebar.html
  hypha/apply/funds/templates/funds/includes/review_sidebar_item.html
  hypha/static_src/src/javascript/apply/toggle-reviewers.js
Labels: Type: Enhancement, Type: Patch

#3113 Upgrade to python 3.11, node 18 and Postgres 14.
  .github/workflows/hypha-ci.yml
  .nvmrc
  .python-version
  docker/Dockerfile.dev
  docker/entrypoint.dev.sh
  docs/getting-started/development/manual.md
  hypha/apply/funds/tests/test_views.py
  hypha/apply/projects/tests/test_views.py
  package.json
  runtime.txt
Labels: Type: Maintenance, Type: Minor

#3354 3353::Deleting Reviews:Allow reviewer to delete review in review phase
  hypha/apply/review/views.py
Labels: Type: Bug, Type: Patch

#3220 Fix Permissions for Project access(detail view)
  hypha/apply/projects/permissions.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Type: Minor

#3358 Fix report-frequency.js and report-calculator.js
  hypha/static_src/src/javascript/apply/report-calculator.js
  hypha/static_src/src/javascript/apply/report-frequency.js
Labels: Type: Bug, Type: Patch

#3360 Make the spacing around buttons and section consistent
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/static_src/src/sass/apply/components/_wrapper.scss
Labels: Type: Enhancement, Type: Patch

#3365 Set margin-block on p-tags since TailWind resets margins.
  hypha/static_src/src/sass/apply/base/_base.scss
Labels: Type: Bug, Type: Patch

#3369 Change 'My [org]' button to 'Login'
  hypha/public/utils/templates/utils/includes/login_button.html
Labels: Type: Enhancement, Type: Patch

#3346 Fixed filter presentation on small screens
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/static_src/src/javascript/apply/submission-filters.js
  hypha/static_src/src/sass/apply/components/_filters.scss
Labels: Type: Enhancement, Type: Patch

#3308 Export user list
  hypha/apply/users/admin_views.py
  hypha/apply/users/templates/wagtailusers/users/results.html
  hypha/static_src/src/sass/apply/wagtail_users_list.scss
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3341 Average total score in review and assignee box
  hypha/apply/funds/templates/funds/includes/review_sidebar.html
  hypha/apply/review/templatetags/review_tags.py
  hypha/static_src/src/sass/apply/components/_reviews-sidebar.scss
Labels: Type: Enhancement, Type: Patch

#3378 Accessibility: Color contrasts corrected for application deadline.
  hypha/static_src/src/sass/apply/abstracts/_variables.scss
  hypha/static_src/src/sass/public/abstracts/_variables.scss
Labels: Type: Enhancement, Type: Patch

#3350 Security and accessibility docs
  docs/getting-started/contributing/contribute-to-documentation.md
  docs/references/accessibility.md
  docs/references/security.md
Labels: Type: Patch, Type: Documentation
