Repository HyphaApp/hypha, pull requests merged in 2023-02, with the labels that each got.

#3147 Updating to Django 3.2.17.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3144 Hide deadline on home page blocks.
  hypha/public/home/templates/home/includes/list_block.html
Labels: Type: Enhancement, Type: Patch

#3141 Make collectstatic command in npm script use settings hypha.settings.…
  package.json
Labels: Type: Maintenance, Type: Patch

#3133 Fix text alignment within a button
  hypha/static_src/src/sass/apply/components/_button.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3132 Use system fonts for apply site
  hypha/static_src/src/sass/apply/abstracts/_variables.scss
  hypha/static_src/src/sass/apply/base/_typography.scss
  hypha/static_src/src/sass/apply/components/_simplified.scss
  hypha/static_src/src/sass/apply/components/_stat-block.scss
Labels: Type: Enhancement, Type: Minor

#3117 Introduce “manage.py initialize” interactive command
  docs/developers/localdevelscratch.md
  hypha/core/management/commands/initialize.py
  hypha/core/management/commands/wagtailsiteupdate.py
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3129 Fix email digest - group the emails at Fund/Lab level
  hypha/apply/activity/management/commands/send_staff_email_digest.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3168 Disable pillow png qr code for 2FA to see if that fixes OTF issue.
  hypha/settings/base.py
Labels: Type: Bug, Type: Patch

#3185 Updating to Django 3.2.18.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3184 Add hypha square logo to the header of documentation
  docs/assets/extra.css
  mkdocs.yml
  requirements-docs.txt
Labels: Type: Patch, Type: Documentation

#3160 Fix that user_count was missing from groups/n/users view so it broke.
  hypha/apply/users/admin_views.py
  hypha/apply/users/templates/wagtailusers/users/results.html
  hypha/apply/users/wagtail_hooks.py
Labels: Type: Bug, Type: Patch

#3157 Fix draft submissions admin setting for all submissions table
  hypha/apply/funds/views.py
Labels: Type: Bug, Status: RTBC, Type: Patch

#3224 Add django browser reload (Only in development)
  hypha/settings/dev.py
  hypha/urls.py
  requirements-dev.txt
Labels: Type: Maintenance, Type: Patch

#3130 Upgrade pip packages
  requirements-dev.txt
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#3142 Update outdated npm packages
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Patch

#3232 Add lead field as required to create project form
  hypha/apply/funds/templates/funds/includes/create_project_form.html
  hypha/apply/funds/tests/test_views.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/models/project.py
Labels: Type: Feature, Type: Minor

#3214 Remove fund allocation from Project dashboard tables
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/projects/tables.py
Labels: Type: Enhancement, Type: Minor

#3218 Show contract corrections only if contract to sign or to approve
  hypha/apply/projects/templates/application_projects/project_detail.html
Labels: Type: Enhancement, Type: Minor

#3215 Remove red banner from applicant dashboard
  hypha/apply/projects/templates/application_projects/project_applicant_detail.html
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Type: Minor

#3145 Remove invoice Valid checks and valid checks link
  hypha/apply/api/v1/permissions.py
  hypha/apply/api/v1/projects/serializers.py
  hypha/apply/api/v1/projects/views.py
  hypha/apply/api/v1/tests/test_serializers.py
  hypha/apply/api/v1/tests/test_views.py
  hypha/apply/api/v1/urls.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/migrations/0061_remove_checks.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/templates/application_projects/includes/required_checks_block.html
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_models.py
  hypha/static_src/src/javascript/apply/invoice-required-checks.js
Labels: Type: Enhancement, Type: Minor

#3170 Fix Contract file url
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/views/project.py
Labels: Type: Bug, Type: Patch

#3231 Use consistent table hover state and borders
  hypha/static_src/src/sass/apply/components/_all-submissions-table.scss
  hypha/static_src/src/sass/apply/components/_table.scss
Labels: Type: Enhancement, Type: Patch

#3230 Hide section header for section showing status summary
  hypha/apply/funds/templates/funds/includes/status-block.html
Labels: Type: Enhancement, Type: Patch

#3229 Fix spacing in the add communications page
  hypha/static_src/src/sass/apply/components/_editor.scss
  hypha/static_src/src/sass/apply/components/_form.scss
Labels: Type: Enhancement, Type: Patch

#3236 Add a get_streamfield_as_raw function to the export command.
  hypha/public/home/management/commands/export_public_pages_json.py
Labels: Type: Maintenance, Type: Patch

#3228 Fix spacing between two sections, also update spacing of tab nav
  hypha/apply/funds/templates/funds/includes/round-block-listing.html
  hypha/static_src/src/sass/apply/components/_round-block.scss
  hypha/static_src/src/sass/apply/components/_tabs.scss
  hypha/static_src/src/sass/apply/components/_wrapper.scss
Labels: Type: Enhancement, Type: Patch

#3238 Use AlpineJS for dashboard rounds/lab tab
  hypha/apply/funds/templates/funds/includes/round-block.html
Labels: Type: Maintenance, Type: Patch

#3239 Add a RELOAD setting so devs can turn on/off reloading when needed.
  hypha/settings/dev.py
Labels: Type: Maintenance, Type: Patch

#3226 Add htmx and hx-boost for header navs
  hypha/apply/dashboard/templates/dashboard/includes/submissions-waiting-for-review.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/users/templates/two_factor/_base.html
  hypha/apply/users/templates/two_factor/_base_focus.html
  hypha/apply/users/templates/users/account.html
  hypha/public/navigation/templates/navigation/primarynav-apply.html
  hypha/settings/django.py
  hypha/static_src/src/javascript/apply/vendor/htmx.min.js
  hypha/static_src/src/javascript/apply/vendor/nprogress-2.0.0.min.js
  hypha/static_src/src/sass/apply/components/_nprogress.scss
  hypha/static_src/src/sass/apply/main.scss
  hypha/templates/base-apply.html
  package.json
  requirements.txt
Labels: Type: Enhancement, Type: Minor

#3183 Similar UI for Upload contract as supporting documents
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/tests/test_forms.py
Labels: Type: Enhancement, Type: Minor

#3155 Add a 'Update Project Status' button to change project status in between 'in-progress, closing and complete' state
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/includes/reports.html
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/report.py
  hypha/static_src/src/sass/apply/components/_banner.scss
Labels: Type: Enhancement, Status: RTBC, Type: Minor

#3235 Make the 2FA setup url more visible
  hypha/apply/users/templates/two_factor/core/setup.html
Labels: Status: Tested - approved for live ✅

#3245 Add numbered section titles when coping form and add a animation on copy.
  hypha/static_src/src/javascript/apply/submission-form-copy.js
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/public/components/_form.scss
Labels: Type: Bug, Type: Patch

#3251 Render blocks in public export script
  hypha/public/home/management/commands/export_public_pages_json.py
Labels: Type: Maintenance, Type: Patch
