Repository HyphaApp/hypha, pull requests merged in 2023-05, with the labels that each got.

#3373 Use UserQuerySet in get_compliance_email() to exclude inactive users.
  hypha/apply/activity/adapters/utils.py
  hypha/apply/users/models.py
Labels: Type: Bug, Type: Patch

#3386 Fix ruff bugbear issues
  hypha/apply/api/v1/determination/serializers.py
  hypha/apply/api/v1/review/serializers.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/projects/services/sageintacct/wrapper/api_base.py
  hypha/public/people/management/commands/migrate_people.py
  hypha/public/projects/management/commands/migrate_projects.py
Labels: Type: Maintenance, Type: Patch

#3223 Rename project status committed to draft
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/migrations/0073_alter_project_status.py
  hypha/apply/projects/migrations/0074_update_projects_status_committed_to_draft.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/tests/test_templatetags.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Type: Minor

#3392 Updating to Django 3.2.19.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3393 Upgrade ruff to 0.0.263
  requirements-dev.txt
Labels: Type: Maintenance, Type: Patch

#3403 Fix link to documentation on how to contribute
  CONTRIBUTING.md
Labels: Type: Patch, Type: Documentation

#3406 Update locale files and test_durations file.
  .test_durations
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#3416 Fix max recursion error on vendor setup page
  requirements.txt
Labels: Type: Bug, Type: Patch

#3294 Add search by application number
  hypha/apply/funds/tables.py
Labels: Type: Feature, Type: Patch

#3420 Fixed country field type in application form to match state field
  addressfield/widgets.py
Labels: Type: Enhancement, Type: Patch

#3422 Fix permission error on double click on submit determination
  hypha/apply/determinations/templates/determinations/base_determination_form.html
Labels: Type: Bug, Type: Minor
