Repository HyphaApp/hypha, pull requests merged in 2023-11, with the labels that each got.

#3637 Update to django-3.2.23.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3638 Update the query text on all.html
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Enhancement, Type: Patch

#3641 docs: update the links to images and some references to pages
  docs/getting-started/contributing/code-contributions.md
  docs/index.md
  docs/references/user-roles.md
  docs/user-guides/applications/creating-submisison-application.md
  docs/user-guides/creating-a-user-account.md
  docs/user-guides/login.md
Labels: Type: Patch, Type: Documentation

#3398 Upgrade to Django 4.1.x
  hypha/apply/funds/views.py
  hypha/apply/projects/views/payment.py
  hypha/apply/review/views.py
  hypha/apply/users/views.py
  hypha/settings/base.py
  requirements.txt
Labels: Status: Needs testing, Type: Maintenance, Type: Minor

#3627 Upgrade wagtail to 5x
  hypha/apply/categories/blocks.py
  hypha/apply/funds/admin.py
  hypha/apply/funds/blocks.py
  hypha/apply/projects/admin.py
  hypha/apply/stream_forms/blocks.py
  hypha/apply/utils/blocks.py
  hypha/public/utils/wagtail_hooks.py
  hypha/static_src/src/sass/apply/wagtail_editor.scss
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Major

#3587 Custom applicant dashboard header
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/static_src/src/sass/apply/components/_button.scss
  hypha/static_src/src/sass/apply/components/_wrapper.scss
  hypha/templates/base-apply.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3657 Update test duration file and locale files. Also lock Faker to v19.x.
  .test_durations
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  requirements-dev.txt
Labels: Type: Maintenance, Type: Patch

#3656 Fix visibility of last item of status bar on submission detail page
  hypha/static_src/src/sass/apply/components/_status-bar.scss
Labels: Type: Bug, Type: Patch

#3600 Add invoices rows to applicant dashboard with different kind of invoice statuses
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/projects/constants.py
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/utils.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#3658 Added migration to remove NEW_SUBMISSION events without a submission
  hypha/apply/activity/migrations/0077_remove_deleted_submission_actions.py
Labels: Type: Maintenance, Type: Patch

#3602 Add grey background for applicant dashboard
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  tailwind.config.js
Labels: Type: Enhancement, Type: Patch

#3633 Show error if htmx ajax request fails with server error
  hypha/templates/base-apply.html
Labels: Type: Maintenance, Type: Patch

#3661 Remove unused ‘report-frequency.js’
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/static_src/src/javascript/apply/report-frequency.js
Labels: Type: Maintenance, Type: Patch

#3664 Add a CustomWagtailUserCreationForm to fix issue with creating users …
  hypha/apply/users/forms.py
  hypha/settings/base.py
Labels: Type: Bug, Type: Patch

#3665 Remove reference of public site from docs
  docs/getting-started/architecture.md
Labels: Type: Patch, Type: Documentation

#3668 Update runtime to python-3.11.6.
  runtime.txt
Labels: Type: Maintenance, Type: Patch
