Repository HyphaApp/hypha, pull requests merged in 2023-01, with the labels that each got.

#3092 Maintainance fix depreciation warnings
  hypha/apply/activity/__init__.py
  hypha/apply/activity/tests/test_tasks.py
  hypha/apply/determinations/tests/test_views.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/home/__init__.py
  hypha/apply/projects/tables.py
  hypha/apply/utils/__init__.py
  hypha/apply/utils/apps.py
  hypha/public/forms/__init__.py
  hypha/public/funds/__init__.py
  hypha/settings/django.py
  requirements-dev.txt
  requirements.txt
Labels: Status: RTBC, Type: Maintenance, Type: Patch

#3099 Remove and fix unsed imports
  hypha/apply/funds/models/__init__.py
  hypha/public/funds/migrations/0007_add_rfp_models_for_public.py
  hypha/public/people/migrations/0001_initial.py
Labels: Type: Maintenance, Type: Patch

#3098 Fix undefined 'user' object in the reviewdraft permission check API
  hypha/apply/api/v1/review/permissions.py
Labels: Type: Bug, Type: Patch

#3100 Make use of 'from' in except clause
  addressfield/fields.py
  hypha/apply/api/v1/projects/serializers.py
  hypha/apply/api/v1/screening/serializers.py
  hypha/apply/api/v1/views.py
  hypha/apply/funds/views.py
  hypha/apply/users/views.py
  hypha/public/news/feeds.py
  hypha/public/projects/models.py
Labels: Type: Maintenance, Type: Patch

#3095 Fix function call `AnonymousUser` performed in argument defaults
  hypha/apply/funds/tests/test_models.py
  hypha/apply/utils/testing/tests.py
Labels: Type: Bug, Type: Patch

#3096 Fix loop control variable overriding iterable it iterates
  hypha/apply/activity/adapters/utils.py
  hypha/public/home/models.py
Labels: Type: Bug, Type: Patch

#3097 Update 'getattr' calls that use constants with normal property access
  hypha/apply/api/v1/reminder/views.py
  hypha/apply/api/v1/stream_serializers.py
  hypha/apply/categories/admin_helpers.py
  hypha/apply/funds/admin_helpers.py
  hypha/apply/projects/views/vendor.py
Labels: Type: Maintenance, Type: Minor

#3106 Only build and deploy the docs when content in the docs dir is updated.
  .github/workflows/deploy-docs.yml
Labels: Type: Maintenance, Type: Patch

#3035 Add activity e-mail digest for each Fund and Lab
  hypha/apply/activity/management/commands/send_staff_email_digest.py
  hypha/apply/funds/migrations/0105_applicationbase_activity_digest_recipient_emails.py
  hypha/apply/funds/models/applications.py
Labels: Type: Enhancement, Status: RTBC, Type: Patch

#3003 Introduce archive feature for the submissions(in batch actions)
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/migrations/0066_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/migrations/0106_applicationsubmission_is_archive.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/includes/batch_archive_submission_form.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/submissions.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/views.py
  hypha/apply/users/decorators.py
  hypha/settings/base.py
  hypha/static_src/src/sass/apply/components/_actions-bar.scss
  hypha/static_src/src/sass/apply/components/_all-submissions-table.scss
  hypha/templates/includes/sprites.html
Labels: Status: RTBC, Type: Feature, Type: Minor

#3108 Remove stale webpack config from settings
  hypha/settings/base.py
  hypha/settings/dev.py
Labels: Type: Maintenance, Type: Patch

#3107 Also build docs when docs conf is changed.
  .github/workflows/deploy-docs.yml
Labels: Type: Maintenance, Type: Patch

#3075 Add a separate DRAFT_SUBMISSION event
  .test_durations
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/migrations/0067_add_draft_submission.py
  hypha/apply/activity/options.py
  hypha/apply/funds/models/utils.py
Labels: Type: Enhancement, Status: RTBC, Type: Patch

#3111 Add documentation section to the release drafter template.
  .github/release-drafter.yml
Labels: Type: Maintenance, Type: Patch

#3109 Update local setup docs
  docs/developers/localdevelscratch.md
Labels: Type: Patch, Type: Documentation

#3053 Unarchive the archived Submissions
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/migrations/0068_add_archive_unarchive.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/activity/include/comment_list.html
  hypha/apply/api/v1/determination/permissions.py
  hypha/apply/api/v1/screening/permissions.py
  hypha/apply/api/v1/screening/views.py
  hypha/apply/determinations/permissions.py
  hypha/apply/determinations/templatetags/determination_tags.py
  hypha/apply/determinations/utils.py
  hypha/apply/determinations/views.py
  hypha/apply/flags/templates/flags/flags.html
  hypha/apply/funds/forms.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/archive_submission_form.html
  hypha/apply/funds/templates/funds/includes/screening_status_block.html
  hypha/apply/funds/templates/funds/includes/unarchive_submission_form.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/templatetags/workflow_tags.py
  hypha/apply/funds/views.py
  hypha/static_src/src/sass/apply/components/_banner.scss
  hypha/static_src/src/sass/apply/main.scss
Labels: Type: Feature, Type: Minor

#3071 Add onetime, yearly and no frequency status to reporting
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/django_messages.py
  hypha/apply/activity/migrations/0069_alter_event_type_add_disable_reporting.py
  hypha/apply/activity/options.py
  hypha/apply/projects/forms/report.py
  hypha/apply/projects/migrations/0057_alter_report_config.py
  hypha/apply/projects/models/report.py
  hypha/apply/projects/templates/application_projects/includes/report_frequency_config.html
  hypha/apply/projects/templates/application_projects/includes/reports.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/report.py
  hypha/static_src/src/javascript/apply/report-frequency.js
  hypha/static_src/src/sass/apply/components/_form.scss
Labels: Type: Enhancement, Type: Patch

#3057 Add script to export public content to json.
  hypha/public/home/management/commands/export_public_pages_json.py
Labels: Type: Feature, Type: Minor

#3103 Replace flake8 & isort with ruff
  .github/workflows/hypha-ci.yml
  Makefile
  addressfield/tests.py
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/messaging.py
  hypha/apply/api/v1/filters.py
  hypha/apply/api/v1/stream_serializers.py
  hypha/apply/categories/models.py
  hypha/apply/determinations/forms.py
  hypha/apply/determinations/tests/factories.py
  hypha/apply/funds/admin_helpers.py
  hypha/apply/funds/edit_handlers.py
  hypha/apply/funds/management/commands/migration_base.py
  hypha/apply/funds/migrations/0062_data_migrate_type_for_assigned_reviewers.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/tests/factories/blocks.py
  hypha/apply/funds/tests/test_admin_form.py
  hypha/apply/funds/tests/test_admin_views.py
  hypha/apply/funds/tests/test_forms.py
  hypha/apply/funds/tests/test_models.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/tests/views/test_batch_reviewers.py
  hypha/apply/funds/views.py
  hypha/apply/funds/workflow.py
  hypha/apply/home/migrations/0002_add_apply_homepage.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/forms/report.py
  hypha/apply/projects/utils.py
  hypha/apply/review/admin_helpers.py
  hypha/apply/review/fields.py
  hypha/apply/review/forms.py
  hypha/apply/review/migrations/0018_migrate_author_data.py
  hypha/apply/review/migrations/0020_review_score_calc_update.py
  hypha/apply/review/tests/factories/blocks.py
  hypha/apply/review/tests/test_views.py
  hypha/apply/stream_forms/models.py
  hypha/apply/stream_forms/testing/factories.py
  hypha/apply/users/migrations/0017_rename_staff_admin.py
  hypha/apply/users/models.py
  hypha/apply/utils/testing/tests.py
  hypha/images/migrations/0001_initial.py
  hypha/public/home/migrations/0004_add_related_models_to_homepage.py
  hypha/public/partner/tables.py
  pyproject.toml
  requirements-dev.txt
  setup.cfg
Labels: Type: Maintenance, Type: Minor

#2669 Add Rate limit sensitive forms
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
  hypha/public/mailchimp/views.py
  hypha/settings/base.py
  requirements.txt
Labels: Type: Enhancement, Type: Minor

#3122 Add full changelog to release drafter template.
  .github/release-drafter.yml
Labels: Type: Maintenance, Type: Patch

#3123 Fix search on all submission failing if show_archive is false
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
Labels: Type: Bug, Type: Patch

#3125 Fix search issue on submission list page with none archived value
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
Labels: Type: Bug, Type: Patch

#3119 Improve the layout of the README intro
  README.md
Labels: Type: Maintenance, Type: Patch

#3124 Show the per-page selection/display at the bottom of the table
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/templates/funds/tables/table.html
  hypha/apply/funds/templatetags/table_tags.py
  hypha/apply/funds/views.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/project_list.html
  hypha/apply/projects/templates/application_projects/tables/table.html
  hypha/static_src/src/sass/apply/components/_pagination.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3126 Use current round for draft submissions at the time of submissions
  hypha/apply/funds/views.py
Labels: Type: Enhancement, Type: Minor
