Repository HyphaApp/hypha, pull requests merged in 2023-07, with the labels that each got.

#3460 Update to django-3.2.20.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3463 Update text for 'Back to project' link
  hypha/apply/funds/templates/funds/applicationsubmission_simplified_detail.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/templates/application_projects/project_sow_detail.html
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
Labels: Type: Enhancement, Type: Patch

#3466 Fix manage.py initialize command
  hypha/core/management/commands/initialize.py
Labels: Type: Maintenance, Type: Patch

#3464 Replace custom css for form elements on apply with Tailwind
  hypha/static_src/src/sass/apply/abstracts/_mixins.scss
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/apply/components/_input.scss
  hypha/static_src/src/sass/apply/main.scss
  hypha/static_src/src/sass/apply/styleguide.scss
  hypha/static_src/src/tailwind/base/forms.css
  hypha/static_src/src/tailwind/main.css
  tailwind.config.js
Labels: Type: Maintenance, Type: Patch

#3473 Update node packages July 2023.
  .stylelintrc.yaml
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Patch

#3471 Remove unused header-admin-height
  hypha/static_src/src/javascript/main.js
  hypha/static_src/src/sass/apply/abstracts/_mixins.scss
  hypha/static_src/src/sass/apply/abstracts/_variables.scss
Labels: Type: Maintenance, javascript

#3482 Use `wagtailsiteupdate` to set hosts and port
  docs/getting-started/development/manual.md
Labels: Type: Patch, Type: Documentation

#3483 Fix application form submit button remaining disabled
  hypha/static_src/src/javascript/apply/application-form.js
Labels: Type: Bug, Type: Patch

#3484 Remove hx-boot from the primary nav
  hypha/public/navigation/templates/navigation/primarynav-apply.html
Labels: Type: Bug, Type: Patch

#3437 Hide everything for no role user
  hypha/apply/funds/models/submissions.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/project_partials.py
  hypha/apply/utils/views.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3481 Fix alignment of upload icon
  hypha/static_src/src/sass/apply/components/_form.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Status: RTBC, Type: Patch

#3468 Update Paf status selection from dropdown to radio buttons
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/models/project.py
  hypha/static_src/src/sass/apply/components/_grid.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3472 Update UI, and text for Contracting documents section
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/static_src/src/sass/apply/components/_icon.scss
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#3470 Remove submission-tooltips.js
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/base_submissions_table.html
  hypha/apply/funds/templates/funds/grouped_application_list.html
  hypha/apply/funds/templates/funds/rounds.html
  hypha/apply/projects/templates/application_projects/overview.html
  hypha/public/partner/tables.py
  hypha/static_src/src/javascript/apply/batch-actions.js
  hypha/static_src/src/javascript/apply/submission-tooltips.js
  hypha/static_src/src/sass/apply/components/_all-reviews-table.scss
  hypha/static_src/src/sass/apply/components/_all-submissions-table.scss
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch, javascript

#3476 Update PAF and SOW UI
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_sow_detail.html
  hypha/static_src/src/sass/apply/components/_simplified.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3485 Rebuild comment visible to option for Staff and hide for everyone except
  hypha/apply/activity/forms.py
  hypha/apply/activity/migrations/0075_alter_activity_visibility.py
  hypha/apply/activity/models.py
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/api/v1/tests/test_views.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3493 Add RateLimit to registrations
  hypha/apply/users/views.py
Labels: Type: Enhancement, Type: Patch

#3450 Fixes noticed during user testing(part-1)
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/dashboard/views.py
  hypha/apply/funds/blocks.py
  hypha/apply/funds/templates/funds/includes/submission_stats.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/forms/vendor.py
  hypha/apply/projects/migrations/0077_alter_invoice_status.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/templates/application_projects/includes/deliverables_block.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/approval_tools.py
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
  hypha/apply/utils/templatetags/apply_tags.py
  hypha/core/context_processors.py
  hypha/public/partner/models.py
  hypha/public/partner/tables.py
  hypha/public/partner/templates/partner/partner_page.html
  hypha/public/utils/templates/utils/includes/funding.html
  hypha/settings/base.py
  hypha/static_src/src/sass/apply/components/_icon.scss
  hypha/templates/includes/sprites.html
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#3488 Update Project statuses 'Waiting for approval' to 'Internal approval' and 'In progress' to 'Invoicing and reporting'
  hypha/apply/activity/adapters/emails.py
  hypha/apply/dashboard/templates/dashboard/includes/paf_waiting_for_approval.html
  hypha/apply/dashboard/tests/test_views.py
  hypha/apply/dashboard/views.py
  hypha/apply/projects/filters.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/migrations/0078_update_project_statuses.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_templatetags.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3475 Add status history section to invoice detail page
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/views/payment.py
  hypha/static_src/src/sass/apply/components/_icon.scss
  hypha/templates/includes/sprites.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3503 Add alt tag for site logo in the header for accessibility/failback
  hypha/templates/base-apply.html
Labels: Type: Enhancement, Type: Minor
