Repository HyphaApp/hypha, pull requests merged in 2023-09, with the labels that each got.

#3551 Update to django-3.2.21.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3552 Add SESSION_COOKIE_AGE Django setting to base.py setting file
  docs/setup/administrators/configuration.md
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#3564 Add code-style checks to Github CI Actions
  .github/workflows/hypha-ci.yml
  Makefile
  hypha/apply/templates/forms/includes/multi_input_field.html
  package.json
Labels: Type: Maintenance, Type: Patch

#3548 Add colour to review outcome displays and do not show "Avg. Score" if it is zero (0)
  hypha/apply/funds/templates/funds/includes/review_sidebar.html
  hypha/apply/funds/templates/funds/includes/review_sidebar_item.html
  hypha/apply/review/models.py
  hypha/apply/review/templatetags/review_tags.py
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/apply/components/_grid.scss
  hypha/static_src/src/sass/apply/components/_reviews-sidebar.scss
  hypha/static_src/src/sass/public/components/_form.scss
  hypha/static_src/src/sass/public/components/_grid.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3561 Make it possible to control who, none/staff/staff admins, can export submissions
  .test_durations
  docs/setup/administrators/configuration.md
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/includes/round-block-listing.html
  hypha/apply/funds/templates/funds/includes/round-block.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/views.py
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Patch

#3570 Fix proposal_form field disable or wrong proposal_form issue
  hypha/apply/determinations/views.py
  hypha/static_src/src/javascript/apply/determination-template.js
Labels: Type: Bug, Status: Needs testing, Type: Patch

#3565 Add ReviewOpinion delete functionality to review sidebar
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/migrations/0076_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/funds/templates/funds/includes/review_sidebar_item.html
  hypha/apply/review/models.py
  hypha/apply/review/templates/review/reviewopinion_confirm_delete.html
  hypha/apply/review/urls.py
  hypha/apply/review/views.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3433 Add slack notification for reviewers on review submit by the role reviewers
  hypha/apply/activity/adapters/slack.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3582 Fix layout of primary navigation on ipad/medium screen
  hypha/public/navigation/templates/navigation/primarynav-apply.html
  hypha/static_src/src/sass/apply/components/_nav.scss
Labels: Type: Bug, Type: Patch

#3573 Fix "Save as Draft" for lab Funds
  hypha/apply/funds/models/applications.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3557 Fix save as draft and allow saving without required fields
  hypha/apply/funds/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅

#3574 For logged in applicant, update messaging on saving draft
  hypha/apply/funds/templates/funds/application_base_landing.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3490 Update activities visibility, hide a few activities for applicant
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#3533 Add assign approver option to paf detail page
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/views/project.py
Labels: Status: Needs testing, Type: Feature, Type: Minor

#3585 Add payment failed status, and add user roles to statuses, and update finance1 to finance
  docs/references/notifications.md
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/adapters/utils.py
  hypha/apply/api/v1/tests/test_views.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/migrations/0080_alter_invoice_status.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/payment.py
  hypha/apply/templates/forms/includes/field.html
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/apply/components/_icon.scss
  hypha/static_src/src/sass/apply/components/_simplified.scss
  hypha/templates/includes/sprites.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch
