Repository HyphaApp/hypha, pull requests merged in 2023-10, with the labels that each got.

#3571 Show activity feed after the page load
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3577 Performance improvement on application form
  hypha/static_src/src/javascript/apply/application-form.js
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3598 Update to django-3.2.22.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3603 Move eslintingore config to eslintrc.yml
  .eslintignore
  .eslintrc.yaml
Labels: Type: Maintenance, Type: Patch

#3613 Fix wagtail user view pagination
  hypha/apply/users/templates/wagtailusers/users/results.html
Labels: Type: Bug, Type: Patch

#3586 Update status bar to show statuses without hover
  hypha/static_src/src/sass/apply/components/_status-bar.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3595 Fix the layout and styling of the upload button and file drop zone
  hypha/apply/templates/forms/includes/field.html
  hypha/static_src/src/sass/apply/abstracts/_mixins.scss
  hypha/static_src/src/sass/apply/components/_file-form.scss
  hypha/static_src/src/sass/apply/components/_form.scss
  hypha/static_src/src/sass/apply/main.scss
  hypha/static_src/src/tailwind/components/django-file-field.css
  hypha/static_src/src/tailwind/main.css
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3593 Add status bar to projects, use same UI for submissions and projects on applicant dashboard
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/project_status_bar.html
  hypha/apply/dashboard/templatetags/dashboard_statusbar_tags.py
  hypha/apply/dashboard/views.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3592 Increase font-weights of page heading
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/funds/templates/funds/applicationsubmission_confirm_delete.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/submission_sealed.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/project_form.html
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
  hypha/apply/projects/templates/application_projects/vendor_form.html
  hypha/apply/projects/templates/application_projects/vendor_success.html
  hypha/apply/review/templates/review/review_confirm_delete.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/review/templates/review/review_edit_form.html
  hypha/apply/review/templates/review/review_form.html
  hypha/apply/review/templates/review/reviewopinion_confirm_delete.html
  hypha/core/templates/components/admin_bar.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3601 Update typography of rendered rich text answers
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/stream_forms/templates/stream_forms/render_field.html
  hypha/static_src/src/sass/apply/components/_rich-text.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3623 Update mkdocs version + update header color
  docs/assets/extra.css
  requirements-docs.txt
Labels: Type: Maintenance, Type: Patch, Type: Documentation

#3622 Fix rendering of stream form fields
  hypha/apply/categories/blocks.py
Labels: Type: Bug, Type: Patch

#3626 Remove depreciation warning for mkdocs material emoji support
  mkdocs.yml
Labels: Type: Maintenance, Type: Patch

#3618 Fix draft determination disabled proposal form issue
  hypha/static_src/src/javascript/apply/determination-template.js
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3617 Update activity feed for paf assignment action
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/adapters/emails.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3616 Fix invoice status visibility and payment failed public message
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/utils.py
  hypha/apply/projects/utils.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3614 Staff can upload the contract
  hypha/apply/activity/adapters/emails.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/apply/projects/templatetags/contract_tools.py
  hypha/settings/base.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3604 Add customizable Header content field
  hypha/public/utils/migrations/0008_systemmessagessettings_nav_content.py
  hypha/public/utils/models.py
  hypha/templates/base-apply.html
  hypha/templates/base.html
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#3632 Add comment count to the communications tab.
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
Labels: Type: Enhancement, Type: Patch
