Repository HyphaApp/hypha, pull requests merged in 2023-08, with the labels that each got.

#3492 Provide project overview page access to Finance and Contracting team
  hypha/apply/projects/permissions.py
  hypha/apply/projects/views/project.py
  hypha/public/navigation/templates/navigation/primarynav-apply.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3501 Add public statuses for invoices
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/utils.py
  hypha/apply/activity/templates/messages/email/invoice_status_updated.html
  hypha/apply/activity/templates/messages/email/invoice_updated.html
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/payment.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3489 Avail PAF Update status option to non-assigned approvers as well.
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3295 Add Organization Name Column
  docs/setup/administrators/configuration.md
  hypha/apply/funds/blocks.py
  hypha/apply/funds/migrations/0112_add_organization_name.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/settings/base.py
  hypha/static_src/src/sass/apply/components/_all-submissions-table.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3510 Rename db in manual dev setup to hypha from hypha-db.
  docs/getting-started/development/manual.md
Labels: Type: Patch, Type: Documentation

#3511 Updated the sandbox db.
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch

#3523 Do not display mailchimp in footer if not enabled
  hypha/public/mailchimp/templates/mailchimp/newsletter_signup.html
  hypha/templates/base.html
Labels: Type: Enhancement, Type: Patch

#3496 Add fields to invoice form and fixed view project page link
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/migrations/0079_alter_invoice_add_fields.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/payment.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3515 Use org long name as author in staff activities for applicants/vendors
  hypha/apply/activity/templatetags/activity_tags.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3524 Update the locale files.
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#3516 Updated paf request changes display string, and put comments in quotes
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#3542 Add word-break: break-word to revision diff table to make long links etc. fit on small screens
  hypha/static_src/src/sass/apply/components/_revisions.scss
Labels: Type: Bug, Type: Patch

#3445 Delete submission creation event(NEW SUBMISSION) on submission deletion
  hypha/apply/funds/services.py
  hypha/apply/funds/views.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3504 Add proposal attachments list(files from submissions) to PAF edit form
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3509 Fixed upload Field issue for PAF form
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/views/project.py
  hypha/apply/stream_forms/forms.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3519 Add require login decorator to AwaitingReviewSubmissionsListView
  hypha/apply/funds/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3522 Add project public statuses for applicant
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/emails.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3521 Update register flow to redirect back to application form
  hypha/apply/users/models.py
  hypha/apply/users/templates/users/change_password.html
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/templates/users/password_reset/confirm.html
  hypha/apply/users/templates/users/password_reset/email.txt
  hypha/apply/users/templates/users/password_reset/form.html
  hypha/apply/users/templates/users/register.html
  hypha/apply/users/urls.py
  hypha/apply/users/utils.py
  hypha/apply/users/views.py
  hypha/public/utils/templates/utils/includes/login_button.html
  hypha/public/utils/templates/utils/includes/register_button.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3520 Remove custom fields from paf and hide paf & sow attachments in their downloaded versions
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch
