Repository HyphaApp/hypha, pull requests merged in 2023-12, with the labels that each got.

#3667 Add scroll to top button
  hypha/core/components.py
  hypha/core/templates/components/scroll-to-top.html
  hypha/templates/base-apply.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3662 Fix the layout of the action buttons on the invoice listing table
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/static_src/src/sass/apply/components/_data-block.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3652 Upgrade to Django 4.2 LTS
  .github/workflows/hypha-ci.yml
  hypha/apply/users/models.py
  hypha/images/migrations/0006_alter_rendition_file.py
  requirements-dev.txt
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Minor

#3646 Show who can see archived submissions
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templatetags/archive_tags.py
  hypha/apply/funds/views.py
  hypha/apply/funds/views_beta.py
  hypha/apply/urls.py
  hypha/apply/users/groups.py
  hypha/apply/utils/templates/apply/403.html
  hypha/apply/utils/views.py
  hypha/public/utils/migrations/0009_systemmessagessettings_body_403_and_more.py
  hypha/public/utils/models.py
  hypha/settings/base.py
  hypha/templates/403.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3654 Break title in max three lines with expandable on hover
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/static_src/src/sass/apply/components/_status-bar.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3677 Removed hard-coded lang and make html lang attribute dynamic
  hypha/templates/base-apply.html
  hypha/templates/base.html
Labels: Type: Enhancement, Type: Patch

#3678 Inline JS detection logic, one less js file to load
  hypha/static_src/src/javascript/main-top.js
  hypha/templates/base-apply.html
  hypha/templates/base.html
Labels: Type: Maintenance, Type: Patch

#3682 Upgrade babel to 2.13.1
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3684 Upgrade minor dependencies
  .github/workflows/hypha-ci.yml
  .nvmrc
  .pre-commit-config.yaml
  .python-version
  hypha/static_src/src/javascript/apply/vendor/alpine-focus.min.js
  hypha/static_src/src/javascript/apply/vendor/alpine.min.js
  hypha/static_src/src/javascript/apply/vendor/htmx.min.js
  package-lock.json
  package.json
  requirements-dev.txt
  requirements.txt
  runtime.txt
Labels: Type: Maintenance, Type: Patch

#3683 Update django-bleech to 3.1.0 remove bleach
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3673 Fix typography for submission diff
  hypha/apply/funds/differ.py
  hypha/apply/funds/templates/funds/includes/revision_diff_table.html
  hypha/apply/funds/templates/funds/revisions_compare.html
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#3636 Added descriptions to group selections in Wagtail admin
  hypha/apply/funds/migrations/0113_alter_assignedreviewers_reviewer.py
  hypha/apply/funds/migrations/0114_alter_assignedreviewers_reviewer.py
  hypha/apply/users/admin_views.py
  hypha/apply/users/forms.py
  hypha/apply/users/groups.py
  hypha/apply/users/migrations/0021_groupdesc.py
  hypha/apply/users/migrations/0023_merge_0021_groupdesc_0022_confirmaccesstoken.py
  hypha/apply/users/models.py
  hypha/apply/users/templates/wagtailusers/groups/index.html
  hypha/apply/users/templates/wagtailusers/users/create.html
  hypha/apply/users/templates/wagtailusers/users/edit.html
  hypha/apply/users/views.py
  hypha/settings/base.py
  hypha/static_src/src/sass/apply/wagtail_groups_list.scss
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#3645 Add "PAFs for review" table for paf approvers
  hypha/apply/dashboard/services.py
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/paf_waiting_for_approval.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/projects/tables.py
  hypha/static_src/src/sass/apply/components/_dashboard-table.scss
  hypha/static_src/src/sass/apply/main.scss
  hypha/static_src/src/sass/apply/styleguide.scss
Labels: Type: Enhancement, Status: Needs testing, Type: Patch

#3692 Allow project for a project's requested funding value to be a decimal
  hypha/apply/projects/migrations/0081_alter_project_value.py
  hypha/apply/projects/models/project.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3690 Remove dependency of invoice delete on PROJECT_ENABLED Flag
  hypha/apply/projects/models/project.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3418 #3417: Configured default visibility for review
  docs/setup/administrators/configuration.md
  hypha/apply/review/blocks.py
  hypha/settings/base.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch
