Repository HyphaApp/hypha, pull requests merged in 2024-05, with the labels that each got.

#3611 Project Reports as stream field forms
  hypha/apply/funds/files.py
  hypha/apply/funds/migrations/0118_labbaseprojectreportform_and_more.py
  hypha/apply/funds/models/forms.py
  hypha/apply/funds/models/mixins.py
  hypha/apply/funds/models/utils.py
  hypha/apply/funds/tests/test_admin_form.py
  hypha/apply/funds/views.py
  hypha/apply/projects/admin.py
  hypha/apply/projects/admin_views.py
  hypha/apply/projects/blocks.py
  hypha/apply/projects/forms/report.py
  hypha/apply/projects/migrations/0082_projectreportform_and_more.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/models/report.py
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/report.py
  hypha/apply/stream_forms/testing/factories.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3898 Refractor primary nav and dashboard, hide projects info if not enabled
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/utils/templatetags/apply_tags.py
  hypha/core/navigation.py
  hypha/core/templates/core/navigation/primarynav-apply.html
  hypha/core/templatetags/applynav_tags.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3904 Fix results page when all submissions lack "Requested amount" field
  hypha/apply/funds/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3901 Add icons to list and grid buttons. Rename grid to table.
  hypha/apply/funds/templates/funds/submissions.html
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3859 Review draft in todo list on staff dashboard
  hypha/apply/determinations/views.py
  hypha/apply/review/views.py
  hypha/apply/todo/migrations/0003_alter_task_code.py
  hypha/apply/todo/options.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#3914 Fixed PR template typos
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Maintenance, Type: Patch

#3893 Visibility fixes for partners that are also applicants
  hypha/apply/activity/models.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3921 Update sandbox database
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch

#3935 Update locale files and test_durations file.
  .test_durations
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#3926 Add a Remeber me checkbox to login that extend session time.
  docs/setup/administrators/configuration.md
  hypha/apply/dashboard/templates/dashboard/includes/my-tasks.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/templates/forms/includes/multi_input_field.html
  hypha/apply/users/forms.py
  hypha/apply/users/migrations/0025_remove_authsettings_register_extra_text.py
  hypha/apply/users/models.py
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/templates/users/partials/confirmation_code_sent.html
  hypha/apply/users/templates/users/password_reset/form.html
  hypha/apply/users/templates/users/passwordless_login_signup.html
  hypha/apply/users/views.py
  hypha/public/news/templates/news/news_index.html
  hypha/settings/base.py
  hypha/static_src/javascript/submission-form-copy.js
  hypha/static_src/javascript/toggle-related.js
  hypha/static_src/sass/abstracts/_mixins.scss
  hypha/static_src/sass/abstracts/_variables.scss
  hypha/static_src/sass/components/_button.scss
  hypha/static_src/sass/components/_link.scss
  hypha/static_src/sass/components/_status-bar.scss
  hypha/templates/base-apply.html
  hypha/templates/includes/login_button.html
  hypha/templates/includes/org_login_button.html
  hypha/templates/includes/password_login_button.html
  hypha/templates/includes/passwordless_login_button.html
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#3920 Disable project related functionality if PROJECTS_ENABLED=False
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/funds/models/utils.py
  hypha/apply/funds/urls.py
  hypha/apply/projects/wagtail_hooks.py
  hypha/apply/utils/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3917 Fix alignment of expand icon + make it accessible
  hypha/static_src/javascript/all-submissions-table.js
  hypha/static_src/sass/components/_all-submissions-table.scss
  hypha/static_src/sass/components/_table.scss
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3881 Skip PAF Approval process if no PAFReviewerRole assigned
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/projects/templatetags/approval_tools.py
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/project_partials.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3942 Developer related tips page
  docs/getting-started/contributing/developer-tips.md
  docs/getting-started/contributing/submitting-changes.md
  docs/setup/deployment/development/stand-alone.md
Labels: Type: Patch, Type: Documentation

#3931 Allow staff to edit project title
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/migrations/0081_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/views/project.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#3938 Add Signed and Approved option to contract upload for staff and Contracting team
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/migrations/0084_contract_signed_and_approved.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/apply/projects/views/project.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3905 Add draft submission of an applicant to their todo list
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/models/utils.py
  hypha/apply/todo/migrations/0004_alter_task_code.py
  hypha/apply/todo/options.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3698 PDF stamping of approved invoices
  hypha/apply/projects/templates/application_projects/pdf_invoce_approved_page.html
  hypha/apply/projects/views/payment.py
  hypha/apply/utils/pdfs.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch
