Repository HyphaApp/hypha, pull requests merged in 2024-07, with the labels that each got.

#3924 Make paf and vendors details editable for active projects
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
  hypha/apply/projects/templatetags/approval_tools.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/vendor.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4039 Update Django to 4.2.14. Fix some test cases and update test_durations.
  .test_durations
  hypha/apply/projects/tests/test_views.py
  hypha/core/templatetags/tests/test_query_params.py
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#4028 Fix: Internal approval projects with no Project reviewer roles
  hypha/apply/projects/apps.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/signals.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4021 Remove None reviewers from validation
  hypha/apply/funds/forms.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4047 Small user menu improvements
  hypha/templates/includes/user_menu.html
Labels: Type: Enhancement, Type: Patch

#4008 Rename PAF Reviewer Roles to Project Reviewer Roles in admin UI
  hypha/apply/projects/migrations/0085_alter_projectsettings_paf_approval_sequential.py
  hypha/apply/projects/models/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4052 Wagtail image tags got mangled, this fix them.
  hypha/templates/includes/header-logo.html
Labels: Type: Bug, Type: Patch

#4024 Update the django-tinymce package, now includes TinyMCE 6.
  hypha/apply/utils/options.py
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4033 Add missing submission export to submission list view & update styling
  docs/setup/administrators/configuration.md
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/views_beta.py
  hypha/settings/base.py
  hypha/static_src/sass/components/_form.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3948 Hide staff identities from applicants & partners
  docs/setup/administrators/configuration.md
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/migrations/0082_change_staff_pii_visibility.py
  hypha/apply/activity/templates/messages/email/comment.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/determinations/templates/determinations/includes/applicant_determination_block.html
  hypha/apply/determinations/templates/determinations/includes/determination_block.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/tests/test_views.py
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/vendor_success.html
  hypha/apply/projects/tests/test_views.py
  hypha/apply/users/forms.py
  hypha/apply/users/models.py
  hypha/core/context_processors.py
  hypha/settings/base.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4042 No longer look at WAGTAILUSERS_PASSWORD_ENABLED and ENABLE_PUBLIC_SIGNUP in activation
  hypha/apply/users/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4066 Fix dependencies, freeze python-bidi to 0.4.2, v5 breaks installation
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#4070 Clean test files from disk after test are finished
  Makefile
  hypha/apply/funds/tests/test_models.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/stream_forms/testing/factories.py
Labels: Type: Maintenance, Type: Patch

#3980 Sanitize database script
  hypha/apply/funds/management/commands/sanitize_database.py
Labels: Type: Maintenance, Type: Patch
