Repository HyphaApp/hypha, pull requests merged in 2024-01, with the labels that each got.

#3704 Updated to Django 4.2.9.
  requirements.txt
Labels: Type: Maintenance, Type: Minor

#3634 Add todo app with task model and integrate todo app APIs with projects part(including PAF process, contracting and invoicing)
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/funds/views.py
  hypha/apply/projects/services.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
  hypha/apply/todo/__init__.py
  hypha/apply/todo/apps.py
  hypha/apply/todo/migrations/0001_initial.py
  hypha/apply/todo/migrations/__init__.py
  hypha/apply/todo/models.py
  hypha/apply/todo/options.py
  hypha/apply/todo/services.py
  hypha/apply/todo/tests.py
  hypha/apply/todo/views.py
  hypha/settings/django.py
  hypha/static_src/src/sass/apply/components/_icon.scss
  hypha/templates/includes/sprites.html
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3687 Remove newsletter/mailchimp application
  docs/setup/deployment/stand-alone.md
  hypha/locale/django.pot
  hypha/public/mailchimp/__init__.py
  hypha/public/mailchimp/apps.py
  hypha/public/mailchimp/forms.py
  hypha/public/mailchimp/migrations/0001_add_newsletter_setting.py
  hypha/public/mailchimp/migrations/__init__.py
  hypha/public/mailchimp/models.py
  hypha/public/mailchimp/templates/mailchimp/newsletter_signup.html
  hypha/public/mailchimp/tests/__init__.py
  hypha/public/mailchimp/tests/test_views.py
  hypha/public/mailchimp/urls.py
  hypha/public/mailchimp/views.py
  hypha/public/urls.py
  hypha/public/utils/context_processors.py
  hypha/settings/base.py
  hypha/settings/django.py
  hypha/templates/base.html
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#3689 Remove public search module
  hypha/public/home/templates/home/home_page.html
  hypha/public/search/__init__.py
  hypha/public/search/templates/search/includes/search_result.html
  hypha/public/search/templates/search/search.html
  hypha/public/search/views.py
  hypha/public/urls.py
  hypha/settings/django.py
  hypha/static_src/src/javascript/main.js
  hypha/templates/base.html
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#3691 Fix projects, invoices and reports tables headers for small size screens
  hypha/apply/dashboard/views.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/tables/table.html
  hypha/static_src/src/sass/apply/components/_projects-table.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3699 Add support for file uploads in communication
  hypha/apply/activity/forms.py
  hypha/apply/activity/migrations/0078_activityattachment.py
  hypha/apply/activity/models.py
  hypha/apply/activity/templates/activity/include/comment_form.html
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/activity/urls.py
  hypha/apply/activity/views.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/delegated_form_base.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/utils/templatetags/apply_tags.py
  hypha/static_src/src/javascript/apply/edit-comment.js
  hypha/static_src/src/sass/apply/components/_feed.scss
  hypha/static_src/src/sass/apply/components/_form.scss
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3707 Enabled validation of determination draft saving
  hypha/apply/determinations/forms.py
  hypha/apply/determinations/templates/determinations/base_determination_form.html
Labels: Type: Bug, Status: Needs testing, Type: Patch

#3708 Fix admin 2FA disable flow
  hypha/apply/users/forms.py
  hypha/apply/users/templates/two_factor/admin/disable.html
  hypha/apply/users/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3688 Replace black with ruff formatter
  .github/workflows/hypha-ci.yml
  .pre-commit-config.yaml
  .prettierignore
  Makefile
  hypha/apply/activity/messaging.py
  hypha/apply/activity/options.py
  hypha/apply/categories/admin_helpers.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/tests/test_models.py
  hypha/apply/funds/views_beta.py
  requirements-dev.txt
Labels: Type: Maintenance, Type: Patch

#3672 Restyle the status bar
  hypha/apply/funds/templates/funds/includes/status_bar.html
  hypha/apply/funds/templates/funds/includes/status_bar_item.html
  hypha/static_src/src/sass/apply/components/_status-bar.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3723 docs: update fetch-depth=0 and update copyright year
  .github/workflows/deploy-docs.yml
  mkdocs.yml
Labels: Type: Patch, Type: Documentation

#3724 Remove public "search promotions" app
  hypha/settings/django.py
Labels: Type: Maintenance, Type: Patch

#3729 Updated PR template to reflect testing practices
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Maintenance, Type: Patch

#3730 docs: remove duplicate info at references > workflows
  docs/references/workflows.md
Labels: Type: Patch, Type: Documentation

#3728 Add dir attribute to the html tag, ltr/rtl.
  hypha/templates/base-apply.html
  hypha/templates/base.html
Labels: Status: Needs testing, Type: Feature, Type: Patch

#3727 Fix errors for compare revisions page(JSONDecodeError and Invalid literal int error)
  hypha/apply/funds/blocks.py
  hypha/apply/stream_forms/blocks.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3715 Remove public primary nav (db) and "news" app
  hypha/public/funds/templates/public_funds/fund_page.html
  hypha/public/funds/templates/public_funds/lab_page.html
  hypha/public/home/management/commands/export_public_pages_json.py
  hypha/public/home/templates/home/home_page.html
  hypha/public/navigation/migrations/0004_delete_navigationsettings.py
  hypha/public/navigation/models.py
  hypha/public/navigation/templates/navigation/primarynav.html
  hypha/public/navigation/templatetags/__init__.py
  hypha/public/navigation/templatetags/navigation_tags.py
  hypha/public/news/blocks.py
  hypha/public/news/feeds.py
  hypha/public/news/management/commands/__init__.py
  hypha/public/news/management/commands/migrate_news.py
  hypha/public/news/migrations/0016_remove_newsindex_header_image_and_more.py
  hypha/public/news/models.py
  hypha/public/news/templates/news/blocks/awesome_table_widget_block.html
  hypha/public/news/templates/news/news_index.html
  hypha/public/news/templates/news/news_page.html
  hypha/public/standardpages/templates/standardpages/index_page.html
  hypha/public/standardpages/templates/standardpages/information_page.html
  hypha/public/urls.py
  hypha/public/utils/wagtail_hooks.py
  hypha/templates/base-apply.html
  hypha/templates/base.html
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Minor, Winter Sprint 2024, Status: Needs dev testing 🧑‍💻

#3716 Remove public "partners" app
  docs/references/wagtail-admin.md
  hypha/public/partner/admin.py
  hypha/public/partner/admin_view.py
  hypha/public/partner/migrations/0001_add_investments_table_and_partners_page.py
  hypha/public/partner/migrations/0004_remove_investmentcategory_investment_and_more.py
  hypha/public/partner/models.py
  hypha/public/partner/tables.py
  hypha/public/partner/templates/partner/base_investments_table.html
  hypha/public/partner/templates/partner/includes/table_filter_and_search.html
  hypha/public/partner/templates/partner/investments.html
  hypha/public/partner/templates/partner/partner_page.html
  hypha/public/partner/templates/partner/table.html
  hypha/public/partner/views.py
  hypha/public/urls.py
  hypha/urls.py
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Minor, Winter Sprint 2024

#3739 Remove "people" app
  hypha/public/people/management/commands/__init__.py
  hypha/public/people/management/commands/migrate_people.py
  hypha/public/people/migrations/0017_remove_fundreviewers_page_and_more.py
  hypha/public/people/models.py
  hypha/public/people/static/people/admin/js/update_person_title.js
  hypha/public/people/templates/people/includes/person_listing.html
  hypha/public/people/templates/people/person_index_page.html
  hypha/public/people/templates/people/person_page.html
  hypha/public/people/wagtail_hooks.py
Labels: Type: Maintenance, Type: Patch, Winter Sprint 2024

#3718 Remove public "projects" app
  hypha/public/projects/management/commands/migrate_projects.py
  hypha/public/projects/migrations/0012_remove_projectfunding_page_and_more.py
  hypha/public/projects/models.py
  hypha/public/projects/templates/projects/includes/project_status.html
  hypha/public/projects/templates/projects/project_index_page.html
  hypha/public/projects/templates/projects/project_page.html
  hypha/public/projects/templates/projects/widgets/categories_widget.html
  hypha/public/projects/templates/projects/widgets/options_option.html
  hypha/public/projects/templates/projects/widgets/options_widget.html
  hypha/public/projects/tests.py
  hypha/public/projects/views.py
  hypha/public/projects/widgets.py
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Minor, Winter Sprint 2024

#3719 Remove public "forms" pages app
  hypha/public/forms/migrations/0006_remove_formpage_header_image_and_more.py
  hypha/public/forms/models.py
  hypha/public/forms/templates/public_forms/form_page.html
  hypha/public/forms/templates/public_forms/form_page_landing.html
  hypha/public/forms/wagtail_hooks.py
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Minor, Winter Sprint 2024

#3740 Update github actions.
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/hypha-ci.yml
Labels: Type: Maintenance, Type: Patch

#3720 Remove public "funds" app
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/views.py
  hypha/apply/home/models.py
  hypha/apply/home/templates/apply_home/includes/apply_listing.html
  hypha/public/funds/admin.py
  hypha/public/funds/blocks.py
  hypha/public/funds/migrations/0001_initial.py
  hypha/public/funds/migrations/0002_labindex_labpage.py
  hypha/public/funds/migrations/0009_allow_mailto_in_linkfield.py
  hypha/public/funds/migrations/0012_add_box_apply_link_fields.py
  hypha/public/funds/migrations/0013_add_more_block.py
  hypha/public/funds/migrations/0014_auto_20220722_0844.py
  hypha/public/funds/migrations/0016_remove_baseapplicationrelatedpage_page_and_more.py
  hypha/public/funds/models.py
  hypha/public/funds/templates/public_funds/blocks/related_projects.html
  hypha/public/funds/templates/public_funds/blocks/related_reviewers.html
  hypha/public/funds/templates/public_funds/fund_index.html
  hypha/public/funds/templates/public_funds/fund_page.html
  hypha/public/funds/templates/public_funds/includes/fund_apply_cta.html
  hypha/public/funds/templates/public_funds/includes/lab_apply_cta.html
  hypha/public/funds/templates/public_funds/includes/project_listing.html
  hypha/public/funds/templates/public_funds/includes/reviewer_listing.html
  hypha/public/funds/templates/public_funds/lab_index.html
  hypha/public/funds/templates/public_funds/lab_page.html
  hypha/public/funds/templates/public_funds/open_call_index_page.html
  hypha/public/funds/tests.py
  hypha/public/funds/views.py
  hypha/public/home/blocks.py
  hypha/public/home/migrations/0015_alter_promotedlabs_unique_together_and_more.py
  hypha/public/home/models.py
  hypha/public/home/templates/home/blocks/our_work.html
  hypha/public/home/templates/home/home_page.html
  hypha/public/home/templates/home/includes/list_block.html
  hypha/public/home/templatetags/__init__.py
  hypha/public/home/templatetags/home_tags.py
  hypha/public/standardpages/migrations/0008_remove_indexpage_listing_image_and_more.py
  hypha/public/utils/blocks.py
  hypha/public/utils/migrations/0011_delete_calltoactionsnippet.py
  hypha/public/utils/models.py
  hypha/static_src/src/sass/public/components/_listing.scss
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Minor, Winter Sprint 2024

#3721 Remove public "standard_pages" app
  docs/getting-started/architecture.md
  hypha/public/forms/models.py
  hypha/public/funds/models.py
  hypha/public/navigation/models.py
  hypha/public/navigation/templates/navigation/breadcrumbs.html
  hypha/public/news/models.py
  hypha/public/partner/models.py
  hypha/public/people/models.py
  hypha/public/standardpages/migrations/0009_remove_informationpage_header_image_and_more.py
  hypha/public/standardpages/models.py
  hypha/public/standardpages/templates/standardpages/index_page.html
  hypha/public/standardpages/templates/standardpages/information_page.html
  hypha/public/utils/blocks.py
  hypha/public/utils/models.py
  hypha/static_src/src/sass/public/components/_nav.scss
  hypha/templates/base.html
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Minor, Winter Sprint 2024

#3722 Move cookieconsent settings to generic settings
  .vscode/settings.json
  hypha/cookieconsent/migrations/0002_remove_cookieconsentsettings_site_and_more.py
  hypha/cookieconsent/models.py
  hypha/cookieconsent/templatetags/cookieconsent_tags.py
  hypha/core/wagtail_hooks.py
  hypha/static_src/src/sass/apply/components/_button.scss
  hypha/static_src/src/sass/apply/components/_wrapper.scss
Labels: Type: Maintenance, Type: Minor, Winter Sprint 2024

#3725 Add server side previews to the application workflow
  docs/setup/administrators/configuration.md
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/application_preview.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/views.py
  hypha/settings/base.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3736 User with Staff role can approve contracts
  hypha/apply/projects/permissions.py
Labels: Type: Enhancement, Type: Patch
