Repository HyphaApp/hypha, pull requests merged in 2024-12, with the labels that each got.

#4235 Translations update from Hosted Weblate
  hypha/locale/cs/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4237 Lock tandem install file to a commit hash
  Makefile
Labels: Type: Maintenance, Type: Patch

#4238 Add updated js files based on the package.json
  hypha/static_src/javascript/vendor/alpine.min.js
  hypha/static_src/javascript/vendor/htmx-ext-multi-swap.min.js
  hypha/static_src/javascript/vendor/htmx.min.js
Labels: Type: Maintenance, Type: Patch

#4232 Use uv to manage and generate dependencies
  .github/workflows/deploy-docs.yml
  .github/workflows/hypha-ci.yml
  .pre-commit-config.yaml
  Makefile
  docker/Dockerfile.dev
  docs/setup/administrators/machine-translations.md
  docs/setup/deployment/development/stand-alone.md
  docs/setup/deployment/production/stand-alone.md
  hypha/apply/funds/tests/test_views.py
  hypha/settings/base.py
  pyproject.toml
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  requirements/translate.txt
  uv.lock
Labels: Type: Maintenance, Type: Minor

#4244 Small typo fix
  hypha/apply/projects/templates/application_projects/pdf_invoice_approved_page.html
  hypha/apply/projects/views/payment.py
Labels: Type: Maintenance, Type: Patch

#4243 Fix exclaimation icon in project table
  hypha/apply/projects/tables.py
Labels: Type: Bug, Type: Patch

#4247 Removing break word style in data tables styles
  hypha/static_src/sass/components/_data-block.scss
Labels: Type: Bug, Type: Patch

#4188 Remove fancybox modal for invoicing and reporting
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/report_frequency_config.html
  hypha/apply/projects/templates/application_projects/includes/report_line.html
  hypha/apply/projects/templates/application_projects/includes/reports.html
  hypha/apply/projects/templates/application_projects/includes/update_invoice_form.html
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/templates/application_projects/modals/invoice_status_update.html
  hypha/apply/projects/templates/application_projects/modals/lead_update.html
  hypha/apply/projects/templates/application_projects/modals/project_status_update.html
  hypha/apply/projects/templates/application_projects/modals/project_title_update.html
  hypha/apply/projects/templates/application_projects/modals/report_frequency_config.html
  hypha/apply/projects/templates/application_projects/partials/project-lead.html
  hypha/apply/projects/templates/application_projects/partials/project_title.html
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/project_list.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/project_partials.py
  hypha/apply/projects/views/report.py
  hypha/static_src/javascript/report-calculator.js
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4196 Add application and project tabs.
  hypha/apply/activity/templates/messages/email/assign_paf_approvers.html
  hypha/apply/activity/templates/messages/email/paf_for_approval.html
  hypha/apply/activity/templates/messages/email/project_final_approval.html
  hypha/apply/activity/templates/messages/email/ready_for_contracting.html
  hypha/apply/activity/templates/messages/email/sent_to_compliance.html
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_simplified_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/project_block.html
  hypha/apply/funds/templates/funds/revisions_compare.html
  hypha/apply/funds/templates/submissions/partials/submission-title.html
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
  hypha/apply/projects/templates/application_projects/includes/project_documents.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/project_sow_detail.html
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/users/templates/two_factor/_base.html
  hypha/apply/users/templates/users/change_password.html
  hypha/apply/utils/pdfs.py
  hypha/static_src/sass/components/_simplified.scss
  hypha/static_src/sass/main.scss
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4240 Combine the reports/reporting nav items
  hypha/apply/projects/templates/application_projects/report_list.html
  hypha/apply/projects/templates/application_projects/reporting.html
  hypha/apply/projects/urls.py
  hypha/core/navigation.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4245 Enchancement to pdf rendering
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/templates/application_projects/pdf_invoice_approved_page.html
  hypha/apply/projects/templates/application_projects/sow_export.html
  hypha/apply/projects/views/project.py
  hypha/apply/utils/migrations/0002_remove_pdfpagesettings_site.py
  hypha/apply/utils/models.py
  hypha/apply/utils/pdfs.py
  hypha/templates/base-pdf.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4254 Rename PAF to project form in more places
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/migrations/0085_rename_paf.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/project_request_change.html
  hypha/apply/dashboard/templates/dashboard/staff_dashboard.html
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/modals/send_for_approval.html
  hypha/apply/projects/templates/application_projects/modals/update_pafapprovers.html
  hypha/apply/projects/views/project.py
  hypha/apply/users/roles.py
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4257 Fix adminbar miss alignment issue
  hypha/static_src/sass/components/_admin-bar.scss
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4251 Updated python packages December 2024.
  pyproject.toml
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  uv.lock
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Minor

#4262 Submission all table need position relative to remain.
  hypha/static_src/sass/components/_admin-bar.scss
Labels: Type: Bug, Type: Patch

#4264 Embed the sourcemaps, linking does not work
  hypha/static_src/tailwind/main.css
  package.json
Labels: Type: Maintenance, Type: Patch

#4268 Fix typos
  hypha/apply/api/v1/review/serializers.py
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/review/blocks.py
  hypha/apply/review/forms.py
  hypha/apply/review/management/commands/migration_review_base.py
  hypha/apply/review/options.py
  hypha/settings/base.py
Labels: Type: Maintenance, Type: Patch

#4267 Fix reporting period not visible in report form
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/projects/templates/application_projects/report_form.html
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4269 Translations update from Hosted Weblate
  hypha/locale/cs/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4281 Add reviews to project form exports. Set size to use PDFPageSettings …
  hypha/apply/activity/templates/messages/email/submission_confirmation.html
  hypha/apply/funds/views.py
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/sow_export.html
  hypha/apply/projects/views/project.py
  hypha/apply/utils/migrations/0003_alter_pdfpagesettings_download_page_size.py
  hypha/apply/utils/models.py
  hypha/apply/utils/pdfs.py
  hypha/templates/base-pdf.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4263 Set sass variables with css variables to allow easy overrides
  hypha/apply/funds/templates/funds/includes/review_sidebar_item.html
  hypha/apply/projects/templates/application_projects/includes/report_line.html
  hypha/apply/projects/templates/application_projects/partials/invoice_status_table.html
  hypha/static_src/javascript/submission-form-copy.js
  hypha/static_src/sass/abstracts/_mixins.scss
  hypha/static_src/sass/abstracts/_variables.scss
  hypha/static_src/sass/base/_typography.scss
  hypha/static_src/sass/components/_actions-bar.scss
  hypha/static_src/sass/components/_admin-bar.scss
  hypha/static_src/sass/components/_all-submissions-table.scss
  hypha/static_src/sass/components/_button.scss
  hypha/static_src/sass/components/_data-block.scss
  hypha/static_src/sass/components/_feed.scss
  hypha/static_src/sass/components/_filters.scss
  hypha/static_src/sass/components/_form.scss
  hypha/static_src/sass/components/_heading.scss
  hypha/static_src/sass/components/_list-reveal.scss
  hypha/static_src/sass/components/_messages.scss
  hypha/static_src/sass/components/_modal.scss
  hypha/static_src/sass/components/_reviews-sidebar.scss
  hypha/static_src/sass/components/_round-block.scss
  hypha/static_src/sass/components/_select2.scss
  hypha/static_src/sass/components/_stat-block.scss
  hypha/static_src/sass/components/_status-bar.scss
  hypha/static_src/sass/components/_status-block.scss
  hypha/static_src/sass/components/_tabs.scss
  hypha/static_src/sass/components/_wrapper.scss
  hypha/static_src/sass/custom/_extra.scss
  hypha/static_src/sass/layout/_header.scss
  hypha/static_src/sass/main.scss
  hypha/static_src/sass/print.scss
  hypha/static_src/tailwind/base/variables.css
  hypha/templates/base-apply.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4271 Make word count warnings work with leatest TinyMCE editor.
  hypha/static_src/javascript/tinymce-word-count.js
  hypha/static_src/sass/components/_rich-text.scss
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4266 Set dir auto via js on all p tags in applications.
  hypha/static_src/javascript/submission-text-cleanup.js
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4282 Fix minor lint issues.
  hypha/static_src/javascript/submission-text-cleanup.js
  hypha/static_src/javascript/tinymce-word-count.js
Labels: Type: Maintenance, Type: Patch

#4278 Add django-stubs as a project dependency + other patches
  pyproject.toml
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4284 Remove tomd and to_markdown() since they are not used anymore
  hypha/apply/funds/templatetags/markdown_tags.py
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4226 Remove old submissions table related code and removed fancybox
  eslint.config.mjs
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/determinations/templates/determinations/includes/batch_determination_confirmation.html
  hypha/apply/determinations/tests/test_views.py
  hypha/apply/determinations/views.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/base_submissions_table.html
  hypha/apply/funds/templates/funds/grouped_application_list.html
  hypha/apply/funds/templates/funds/includes/batch_archive_submission_form.html
  hypha/apply/funds/templates/funds/includes/batch_delete_submission_form.html
  hypha/apply/funds/templates/funds/includes/batch_progress_form.html
  hypha/apply/funds/templates/funds/includes/batch_update_lead_form.html
  hypha/apply/funds/templates/funds/includes/batch_update_reviewer_form.html
  hypha/apply/funds/templates/funds/includes/delegated_form_base.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/reviewer_leaderboard.html
  hypha/apply/funds/templates/funds/rounds.html
  hypha/apply/funds/templates/funds/submissions.html
  hypha/apply/funds/templates/funds/submissions_by_round.html
  hypha/apply/funds/templates/funds/submissions_by_status.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/tests/views/test_batch_progress.py
  hypha/apply/funds/tests/views/test_batch_reviewers.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/templates/application_projects/includes/batch_invoice_status_update.html
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/templates/application_projects/modals/batch_invoice_status_update.html
  hypha/apply/projects/templates/application_projects/project_list.html
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/payment.py
  hypha/apply/users/tests/test_middleware.py
  hypha/static_src/javascript/batch-actions.js
  hypha/static_src/javascript/fancybox-global.js
  hypha/static_src/javascript/jquery.fancybox.min.js
  hypha/static_src/javascript/translate-application.js
  hypha/static_src/sass/components/_list-reveal.scss
  hypha/static_src/sass/fancybox.scss
Labels: Type: Enhancement, Type: Minor

#4279 Move to indent_size = 2 for all js files. This is the prettier default.
  .editorconfig
  hypha/addressfield/static/address_form.js
  hypha/apply/dashboard/static/js/django_select2-checkboxes.js
  hypha/apply/dashboard/static/js/select2.multi-checkboxes.js
  hypha/cookieconsent/static/js/cookieconsent.js
  hypha/static_src/javascript/all-submissions-table.js
  hypha/static_src/javascript/application-form-links-new-window.js
  hypha/static_src/javascript/application-form.js
  hypha/static_src/javascript/batch-actions.js
  hypha/static_src/javascript/behaviours/collapse.js
  hypha/static_src/javascript/behaviours/review-score.js
  hypha/static_src/javascript/deliverables.js
  hypha/static_src/javascript/determination-template.js
  hypha/static_src/javascript/document-category.js
  hypha/static_src/javascript/file-uploads.js
  hypha/static_src/javascript/form-group-toggle.js
  hypha/static_src/javascript/multi-input-fields.js
  hypha/static_src/javascript/past-reports-pagination.js
  hypha/static_src/javascript/report-calculator.js
  hypha/static_src/javascript/review-form-actions.js
  hypha/static_src/javascript/submission-filters.js
  hypha/static_src/javascript/submission-form-copy.js
  hypha/static_src/javascript/submission-text-cleanup.js
  hypha/static_src/javascript/tabs.js
  hypha/static_src/javascript/tinymce-word-count.js
  hypha/static_src/javascript/toggle-payment-block.js
  hypha/static_src/javascript/translate-application.js
  tailwind.config.js
Labels: Type: Maintenance, Type: Patch

#4286 Temporarily move jQuery back to being loaded in the head until we have fixed all scripts getting loaded mid page
  hypha/templates/base.html
Labels: Type: Bug, Type: Patch

#4296 Update referrer-policy to strict-origin-when-cross-origin, remove django-referrer-policy packages, built in to Django 3 and later
  hypha/settings/base.py
  hypha/settings/django.py
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4292 Update gitignore
  .gitignore
Labels: Type: Maintenance, Type: Patch

#4298 When bumping version uv.lock needs to be updated as well.
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4300 Restore jQuery version of file-uploads.js
  hypha/static_src/javascript/file-uploads.js
Labels: Type: Bug, Type: Patch

#4277 Update permission for Project document upload button
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/partials/supporting_documents.html
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4303 Remove stylelint rules that are no longer needed with later versions.
  .stylelintrc.yaml
  hypha/static_src/sass/abstracts/_mixins.scss
  hypha/static_src/sass/abstracts/_variables.scss
  hypha/static_src/sass/base/_base.scss
  hypha/static_src/sass/components/_all-reviews-table.scss
  hypha/static_src/sass/components/_all-submissions-table.scss
  hypha/static_src/sass/components/_button.scss
  hypha/static_src/sass/components/_dashboard-table.scss
  hypha/static_src/sass/components/_feed.scss
  hypha/static_src/sass/components/_form.scss
  hypha/static_src/sass/components/_nprogress.scss
  hypha/static_src/sass/components/_projects-table.scss
  hypha/static_src/sass/components/_reviews-sidebar.scss
  hypha/static_src/sass/components/_select2.scss
  hypha/static_src/sass/components/_submission-meta.scss
  hypha/static_src/sass/components/_table.scss
  hypha/static_src/sass/components/_tabs.scss
  hypha/static_src/sass/components/_two-factor.scss
  hypha/static_src/sass/print.scss
  hypha/static_src/sass/wagtail_users_list.scss
Labels: Type: Maintenance, Type: Patch

#4301 Replace wrapper--cookieconsent with tailwind classes
  hypha/cookieconsent/templates/includes/banner.html
  hypha/static_src/sass/components/_card.scss
  hypha/static_src/sass/components/_wrapper.scss
Labels: Type: Maintenance, Type: Patch

#4309 Implement RUNSERVERPLUS_SERVER_ADDRESS_PORT and add console logging for werkzeug/runserver_plus
  Makefile
  hypha/settings/dev.py
Labels: Type: Maintenance, Type: Patch

#4307 Replace eslint and prettier with Biome
  .github/workflows/hypha-ci.yml
  .pre-commit-config.yaml
  .prettierignore
  biome.json
  eslint.config.mjs
  package-lock.json
  package.json
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
Labels: Type: Maintenance, Type: Patch
