Repository HyphaApp/hypha, pull requests merged in 2024-04, with the labels that each got.

#3843 Fix user and staff flagg views. Add staff flag view to main menu.
  docs/user-guides/applications/submission-search.md
  hypha/apply/dashboard/templates/dashboard/includes/flagged.html
  hypha/apply/dashboard/views.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/base_submissions_table.html
  hypha/apply/funds/templates/funds/reviewer_leaderboard.html
  hypha/apply/funds/templates/funds/reviewer_leaderboard_detail.html
  hypha/apply/funds/templates/funds/staff_assignments.html
  hypha/apply/funds/templates/funds/submissions.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/templates/funds/submissions_search.html
  hypha/apply/funds/templates/funds/submissions_staff_flagged.html
  hypha/apply/funds/templates/funds/submissions_user_flagged.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/views.py
  hypha/apply/funds/views_beta.py
  hypha/core/navigation.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3866 Rename the beta and old submission all views to list and grid.
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/submission-list-item.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/submissions.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/templates/submissions/submenu/category.html
  hypha/apply/funds/templates/submissions/submenu/funds.html
  hypha/apply/funds/templates/submissions/submenu/leads.html
  hypha/apply/funds/templates/submissions/submenu/meta-terms.html
  hypha/apply/funds/templates/submissions/submenu/reviewers.html
  hypha/apply/funds/templates/submissions/submenu/rounds.html
  hypha/apply/funds/urls.py
  hypha/core/templates/components/admin_bar.html
  hypha/static_src/sass/abstracts/_variables.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3862 Handle missing related object in task for todo list
  hypha/apply/todo/options.py
  hypha/apply/todo/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3860 Fix beta submission view dropdown for long list, make them scroll
  hypha/apply/funds/templates/submissions/submenu/bulk-update-lead.html
  hypha/apply/funds/templates/submissions/submenu/category.html
  hypha/apply/funds/templates/submissions/submenu/change-status.html
  hypha/apply/funds/templates/submissions/submenu/funds.html
  hypha/apply/funds/templates/submissions/submenu/leads.html
  hypha/apply/funds/templates/submissions/submenu/meta-terms.html
  hypha/apply/funds/templates/submissions/submenu/reviewers.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3847 Update Ui for task list: Add border to my task item
  hypha/apply/dashboard/templates/dashboard/dashboard.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3795 Fixes to application previews and draft refactoring
  hypha/apply/funds/migrations/0117_applicationrevision_is_draft.py
  hypha/apply/funds/models/application_revisions.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/application_preview.html
  hypha/apply/funds/templates/funds/applicationrevision_list.html
  hypha/apply/funds/tests/test_models.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/views.py
  hypha/settings/base.py
  hypha/static_src/sass/components/_revision.scss
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3870 Hide Submission status count summary for reviewers
  hypha/apply/funds/templates/funds/submissions.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3868 Fix error message alignment for change password form
  hypha/apply/templates/forms/includes/field.html
  hypha/apply/users/templates/users/change_password.html
  hypha/static_src/sass/components/_form.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3874 Remove the Hypha styleguide.
  hypha/settings/base.py
  hypha/settings/dev.py
  hypha/settings/local.py.example
  hypha/static_src/sass/styleguide.scss
  hypha/templates/styleguide.html
  hypha/urls.py
Labels: Type: Maintenance, Type: Patch

#3878 Update styling of the opinion info message
  hypha/apply/review/templates/review/review_detail.html
Labels: Type: Enhancement, Status: RTBC, Type: Patch

#3876 Changed order of `Past Submissions` in the detailed submission view
  hypha/apply/funds/views.py
Labels: Type: Bug, Type: Patch

#3846 Add draft determinations to todo list
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/determinations/views.py
  hypha/apply/todo/migrations/0002_alter_task_code.py
  hypha/apply/todo/options.py
  hypha/apply/todo/views.py
  hypha/templates/includes/sprites.html
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#3879 Update styling of My Tasks section
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/my-tasks.html
  hypha/apply/dashboard/templates/dashboard/includes/submissions-waiting-for-review.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3880 Use less jQuery, alipinejs or vanillajs instead
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_sow_detail.html
  hypha/static_src/javascript/all-submissions-table.js
  hypha/static_src/javascript/application-form-links-new-window.js
  hypha/static_src/javascript/dropdown.js
  hypha/static_src/javascript/submission-text-cleanup.js
  hypha/static_src/javascript/toggle-related.js
  hypha/static_src/sass/components/_button.scss
  hypha/static_src/sass/components/_dropdown.scss
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#3903 Fix alignment of text in the plain-text emails
  hypha/apply/activity/templates/messages/email/applicant_base.html
  hypha/apply/activity/templates/messages/email/assign_paf_approvers.html
  hypha/apply/activity/templates/messages/email/batch_ready_to_review.html
  hypha/apply/activity/templates/messages/email/comment.html
  hypha/apply/activity/templates/messages/email/contract_uploaded.html
  hypha/apply/activity/templates/messages/email/determination.html
  hypha/apply/activity/templates/messages/email/invited_to_proposal.html
  hypha/apply/activity/templates/messages/email/invoice_approved.html
  hypha/apply/activity/templates/messages/email/invoice_status_updated.html
  hypha/apply/activity/templates/messages/email/invoice_updated.html
  hypha/apply/activity/templates/messages/email/paf_for_approval.html
  hypha/apply/activity/templates/messages/email/partners_update_applicant.html
  hypha/apply/activity/templates/messages/email/partners_update_partner.html
  hypha/apply/activity/templates/messages/email/project_final_approval.html
  hypha/apply/activity/templates/messages/email/project_request_change.html
  hypha/apply/activity/templates/messages/email/ready_for_contracting.html
  hypha/apply/activity/templates/messages/email/ready_for_invoicing.html
  hypha/apply/activity/templates/messages/email/ready_to_review.html
  hypha/apply/activity/templates/messages/email/report_frequency.html
  hypha/apply/activity/templates/messages/email/report_notify.html
  hypha/apply/activity/templates/messages/email/report_skipped.html
  hypha/apply/activity/templates/messages/email/report_submitted.html
  hypha/apply/activity/templates/messages/email/sent_to_compliance.html
  hypha/apply/activity/templates/messages/email/submission_confirmation.html
  hypha/apply/activity/templates/messages/email/submission_edit.html
  hypha/apply/activity/templates/messages/email/submit_contract_documents.html
  hypha/apply/activity/templates/messages/email/transition.html
  hypha/apply/activity/templates/messages/email/vendor_setup_needed.html
  hypha/apply/activity/templates/messages/email/vendor_updated.html
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch
