Repository HyphaApp/hypha, pull requests merged in 2024-10, with the labels that each got.

#4126 Fix 'Reminder Created' duplicate message, restrict duplicate toast messages
  hypha/apply/funds/views.py
  hypha/templates/includes/_toast-placeholder.html
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4161 Remove 'drf-yasg' swagger docs viewer
  hypha/apply/api/urls.py
  hypha/settings/django.py
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#4114 Improve cloned forms naming
  hypha/apply/funds/admin_views.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/tests/test_utils.py
  hypha/apply/funds/utils.py
  requirements-dev.txt
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4154 Upgrade to python 3.12.6.
  .python-version
  docker/Dockerfile.dev
  requirements.txt
  runtime.txt
Labels: Type: Maintenance, Type: Patch

#4152 Node package updates.
  .nvmrc
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Patch

#4163 Add "templates_custom" folder to tailwind search path
  tailwind.config.js
Labels: Type: Maintenance, Type: Patch

#4162 Updated ESLint to v9.12.0 & migrated to a flat config file
  .eslintrc.yaml
  eslint.config.mjs
  hypha/cookieconsent/static/js/cookieconsent.js
  hypha/static_src/javascript/all-reviews-table.js
  hypha/static_src/javascript/all-submissions-table.js
  hypha/static_src/javascript/application-form-links-new-window.js
  hypha/static_src/javascript/application-form.js
  hypha/static_src/javascript/batch-actions.js
  hypha/static_src/javascript/deliverables.js
  hypha/static_src/javascript/determination-template.js
  hypha/static_src/javascript/document-category.js
  hypha/static_src/javascript/edit-comment.js
  hypha/static_src/javascript/fancybox-global.js
  hypha/static_src/javascript/file-uploads.js
  hypha/static_src/javascript/form-group-toggle.js
  hypha/static_src/javascript/main.js
  hypha/static_src/javascript/multi-input-fields.js
  hypha/static_src/javascript/past-reports-pagination.js
  hypha/static_src/javascript/report-calculator.js
  hypha/static_src/javascript/submission-filters.js
  hypha/static_src/javascript/submission-form-copy.js
  hypha/static_src/javascript/submission-text-cleanup.js
  hypha/static_src/javascript/tabs.js
  hypha/static_src/javascript/tinymce-word-count.js
  hypha/static_src/javascript/toggle-payment-block.js
  hypha/static_src/javascript/toggle-related.js
  hypha/static_src/javascript/two-factor-focus.js
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Minor

#4086 Remove vendor feature code
  docs/references/wagtail-admin.md
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/migrations/0084_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/project_created.html
  hypha/apply/activity/templates/messages/email/vendor_updated.html
  hypha/apply/projects/admin.py
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/vendor.py
  hypha/apply/projects/migrations/0088_remove_duediligencedocument_vendor_and_more.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/models/vendor.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/invoice_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
  hypha/apply/projects/templates/application_projects/vendor_form.html
  hypha/apply/projects/templates/application_projects/vendor_success.html
  hypha/apply/projects/templatetags/approval_tools.py
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/vendor.py
  hypha/static_src/javascript/file-uploads.js
Labels: Type: Enhancement, Status: Needs testing, Type: Minor, Status: Needs dev testing 🧑‍💻

#4122 Remove all Finance 2 features
  docs/references/notifications.md
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/adapters/utils.py
  hypha/apply/api/v1/permissions.py
  hypha/apply/api/v1/projects/views.py
  hypha/apply/api/v1/tests/test_views.py
  hypha/apply/dashboard/views.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/migrations/0044_add_resubmitted_status.py
  hypha/apply/projects/migrations/0045_use_fsm_field_for_status.py
  hypha/apply/projects/migrations/0050_add_new_invoice_status.py
  hypha/apply/projects/migrations/0077_alter_invoice_status.py
  hypha/apply/projects/migrations/0080_alter_invoice_status.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/service_utils.py
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/payment.py
  hypha/apply/users/models.py
  hypha/apply/users/tests/factories.py
  hypha/settings/base.py
Labels: Type: Enhancement, Status: Needs testing, Type: Minor, Status: Needs dev testing 🧑‍💻

#4142 Submission data on determination and review form page
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/funds/templates/submissions/partials/applicationsubmission.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views_partials.py
  hypha/apply/review/templates/review/review_form.html
  hypha/templates/base.html
Labels: Status: Needs testing, Type: Feature, Type: Minor, Status: Needs user testing 👷

#4159 Do not send notification when author delete own draft.
  hypha/apply/funds/views.py
Labels: Type: Enhancement, Status: Needs testing, Type: Patch, Status: Needs user testing 👷

#3932 Rebuild communication and activity feed + assign a comment as task to user
  .vscode/settings.json
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/forms.py
  hypha/apply/activity/models.py
  hypha/apply/activity/services.py
  hypha/apply/activity/templates/activity/include/action_list.html
  hypha/apply/activity/templates/activity/include/all_activity_list.html
  hypha/apply/activity/templates/activity/include/comment_form.html
  hypha/apply/activity/templates/activity/include/comment_list.html
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/activity/templates/activity/partial_comment_message.html
  hypha/apply/activity/templates/activity/ui/activity-action-item.html
  hypha/apply/activity/templates/activity/ui/activity-comment-item.html
  hypha/apply/activity/templates/activity/ui/edit_comment_form.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/activity/tests/test_comments.py
  hypha/apply/activity/urls.py
  hypha/apply/activity/views.py
  hypha/apply/api/v1/filters.py
  hypha/apply/api/v1/serializers.py
  hypha/apply/api/v1/tests/test_views.py
  hypha/apply/api/v1/urls.py
  hypha/apply/api/v1/views.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/delegated_form_base.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/templates/forms/includes/field.html
  hypha/apply/todo/migrations/0006_alter_task_code.py
  hypha/apply/todo/options.py
  hypha/apply/todo/services.py
  hypha/apply/todo/views.py
  hypha/apply/users/identicon.py
  hypha/apply/users/models.py
  hypha/apply/users/templates/users/account.html
  hypha/apply/users/templatetags/users_tags.py
  hypha/static_src/javascript/edit-comment.js
  hypha/static_src/javascript/tabs.js
  hypha/static_src/sass/components/_editor.scss
  hypha/static_src/sass/components/_feed.scss
  hypha/static_src/sass/components/_form.scss
  hypha/static_src/sass/components/_wrapper.scss
  hypha/templates/includes/sprites.html
  requirements.txt
Labels: Status: Needs testing, Type: Feature, Type: Minor, Status: Needs user testing 👷

#4156 Fix submission search input
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/views_beta.py
Labels: Type: Enhancement, Type: Patch

#4168 Remove some code formatting rules from eslint. Prettier takes care of that.
  .test_durations
  eslint.config.mjs
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4127 Update homepage to not used wagtail pages
  hypha/apply/dashboard/wagtail_hooks.py
  hypha/core/migrations/0006_systemsettings_home_strapline_and_more.py
  hypha/core/migrations/0007_copy_homepage_title_strapline.py
  hypha/core/models/system_settings.py
  hypha/home/models.py
  hypha/home/templates/apply_home/apply_home_page.html
  hypha/home/templates/home/home.html
  hypha/home/templates/home/includes/fund-list-item.html
  hypha/home/tests.py
  hypha/home/views.py
  hypha/static_src/sass/wagtail_global_admin.css
  hypha/templates/base-apply.html
  hypha/templates/base.html
  hypha/urls.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4155 Basic project info in pyproject.toml.
  pyproject.toml
Labels: Type: Maintenance, Type: Patch

#4170 Updated the sandbox db.
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch

#4118 Add confirm message when exporting submission data as csv file
  hypha/apply/funds/templates/funds/includes/round-block-listing.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4164 Speed up CI
  .github/workflows/hypha-ci.yml
  .gitignore
  .pre-commit-config.yaml
  .python-version
  .test_durations
  Makefile
  hypha/addressfield/tests.py
  hypha/apply/api/v1/tests/__init__.py
  hypha/apply/api/v1/tests/test_serializers.py
  hypha/apply/api/v1/tests/test_views.py
  requirements-dev.txt
Labels: Type: Maintenance, Type: Patch

#4177 Add files conf to prettier pre-commit setup.
  .pre-commit-config.yaml
Labels: Type: Maintenance, Type: Patch

#4178 Make review form errors show as they should.
  hypha/apply/review/templates/review/review_form.html
  hypha/static_src/sass/components/_form.scss
Labels: Type: Bug, Type: Patch

#4184 Added tag to generate existing submission view params for pagination
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4182 Add back link to view activity related object.
  hypha/apply/activity/templates/activity/ui/activity-action-item.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4173 Adjust main padding on breakpoint xl.
  hypha/static_src/sass/components/_admin-bar.scss
  hypha/templates/base-apply.html
Labels: Type: Bug, Type: Patch

#4160 Remove Fancybox modal for PAF workflow
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/includes/project_documents.html
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/modals/assign_pafapprovers.html
  hypha/apply/projects/templates/application_projects/modals/pafstatus_update.html
  hypha/apply/projects/templates/application_projects/modals/send_for_approval.html
  hypha/apply/projects/templates/application_projects/modals/supporting_documents_upload.html
  hypha/apply/projects/templates/application_projects/modals/update_pafapprovers.html
  hypha/apply/projects/templates/application_projects/partials/supporting_documents.html
  hypha/apply/projects/templates/application_projects/project_admin_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/project_partials.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4169 Running total of score on review form
  eslint.config.mjs
  hypha/apply/review/blocks.py
  hypha/apply/review/fields.py
  hypha/apply/review/templates/review/review_edit_form.html
  hypha/apply/review/templates/review/review_form.html
  hypha/apply/review/views.py
  hypha/static_src/javascript/behaviours/review-score.js
  hypha/templates/base.html
Labels: Status: Tested - approved for live ✅
