Repository HyphaApp/hypha, pull requests merged in 2024-09, with the labels that each got.

#4123 Update Django to 4.2.16.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#4105 Set signed by applicant true when submit and approved
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4111 Fix no report form attached to fund
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/views/report.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4112 Fix my tasks title issue on dismissing all tasks
  hypha/apply/dashboard/templates/dashboard/includes/my-tasks.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4108 Add draft submission deletion feature for applicants
  hypha/apply/dashboard/templates/dashboard/partials/applicant_submissions.html
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/applicationsubmission_confirm_delete.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/views.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#4109 Update makefile, auto-help and better serve
  .gitignore
  Makefile
  package.json
Labels: Type: Maintenance, Type: Patch

#4080 New submission table view
  hypha/apply/dashboard/templates/dashboard/includes/flagged.html
  hypha/apply/dashboard/templates/dashboard/includes/submissions-waiting-for-review.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/templates/dashboard/staff_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/round-block-listing.html
  hypha/apply/funds/templates/funds/includes/round-block.html
  hypha/apply/funds/templates/funds/includes/submission-list-item.html
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/funds/includes/submission-table-row.html
  hypha/apply/funds/templates/funds/submissions.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/templates/submissions/partials/meta-terms-card.html
  hypha/apply/funds/templates/submissions/partials/submissions-inline.html
  hypha/apply/funds/templates/submissions/submenu/category.html
  hypha/apply/funds/templates/submissions/submenu/funds.html
  hypha/apply/funds/templates/submissions/submenu/leads.html
  hypha/apply/funds/templates/submissions/submenu/meta-terms.html
  hypha/apply/funds/templates/submissions/submenu/reviewers.html
  hypha/apply/funds/templates/submissions/submenu/rounds.html
  hypha/apply/funds/tests/views/test_batch_progress.py
  hypha/apply/funds/tests/views/test_batch_reviewers.py
  hypha/apply/funds/tests/views/test_rounds.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
  hypha/apply/funds/views_beta.py
  hypha/apply/funds/workflow.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/core/context_processors.py
  hypha/core/navigation.py
  hypha/core/templates/components/admin_bar.html
  hypha/core/templates/components/dropdown-menu.html
  hypha/templates/includes/user_menu.html
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4106 Added links & icons to wagtail form view `Used By` columns
  hypha/apply/categories/admin.py
  hypha/apply/determinations/admin.py
  hypha/apply/funds/admin.py
  hypha/apply/projects/admin.py
  hypha/apply/review/admin.py
  hypha/apply/utils/admin.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#4019 Add invoice date and paid date to invoice and invoices lists and tables
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/migrations/0086_invoice_invoice_date_invoice_paid_date.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/payment.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4104 Update PAF to Project Form in user facing strings
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/migrations/0087_alter_pafreviewersrole_user_roles.py
  hypha/apply/projects/models/project.py
  hypha/apply/todo/migrations/0005_alter_task_code.py
  hypha/apply/todo/options.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4132 Updated the sandbox db.
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch

#4135 Updated the sandbox db.
  public/sandbox_db.dump
Labels: Type: Maintenance, Type: Patch

#4133 Added command to delete drafts that haven't been modified in specified days
  docs/setup/administrators/cron-jobs.md
  hypha/apply/funds/management/commands/drafts_cleanup.py
Labels: Type: Feature, Type: Minor

#4137 Update micromatch.
  package-lock.json
Labels: Type: Maintenance, Type: Patch

#4138 Lock griffe version, breaking change in v1.x.
  requirements-docs.txt
Labels: Type: Maintenance, Type: Patch

#4139 Add content from Hypha site to docs front page.
  docs/index.md
Labels: Type: Patch, Type: Documentation

#4143 Rename past submission to other submissions
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Enhancement, Type: Patch
