Repository HyphaApp/hypha, pull requests merged in 2024-03, with the labels that each got.

#3780 Update overview sections to use them as filter
  hypha/apply/funds/templates/funds/includes/status-block.html
  hypha/apply/funds/templates/funds/submissions.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/utils.py
  hypha/apply/funds/views_partials.py
  hypha/apply/projects/constants.py
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/templates/application_projects/project_list.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project_partials.py
  hypha/static_src/sass/components/_status-block.scss
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3798 Fix templates to show base header on determination forms
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/determinations/templates/determinations/determination_form.html
Labels: Type: Bug, Status: Needs testing, Type: Patch, Status: Needs user testing 👷

#3803 Update to codecov-action v4 that uses node 20.x.
  .github/workflows/hypha-ci.yml
Labels: Type: Maintenance, Type: Patch

#3696 Replace bleach with nh3
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/activity/templates/activity/include/notifications_dropdown.html
  hypha/apply/activity/templates/activity/notifications.html
  hypha/apply/activity/templates/messages/email/determination.html
  hypha/apply/api/v1/serializers.py
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/determinations/models.py
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/funds/differ.py
  hypha/apply/funds/forms.py
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
  hypha/apply/review/templates/review/render_scored_answer_field.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/review/templates/review/review_list.html
  hypha/apply/stream_forms/blocks.py
  hypha/apply/stream_forms/templates/stream_forms/render_markdown_field.html
  hypha/apply/stream_forms/templates/stream_forms/render_unsafe_field.html
  hypha/apply/templates/forms/includes/field.html
  hypha/apply/utils/blocks.py
  hypha/home/templates/apply_home/includes/apply_listing.html
  hypha/public/news/templates/news/news_index.html
  hypha/settings/base.py
  hypha/settings/django.py
  requirements.txt
Labels: Status: Needs testing, Type: Maintenance, Type: Minor, Status: Needs dev testing 🧑‍💻

#3796 Let non-Staff (e.g. Admin) do batch determination
  hypha/apply/determinations/forms.py
Labels: Type: Enhancement, Type: Patch

#3792 Update applicant dashboard with all submissions into a section with pagination
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/partials/applicant_projects.html
  hypha/apply/dashboard/templates/dashboard/partials/applicant_submissions.html
  hypha/apply/dashboard/tests/test_views.py
  hypha/apply/dashboard/urls.py
  hypha/apply/dashboard/views.py
  hypha/apply/dashboard/views_partials.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3810 Hide wagtail admin > sidebar > search
  hypha/core/wagtail_hooks.py
  hypha/static_src/sass/wagtail_global_admin.css
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3801 Add valid number validation for Requested amount field
  hypha/apply/funds/blocks.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3805 Display "View Live" button only if round is live in admin
  hypha/apply/funds/models/applications.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3812 Swapped out hamburger menu for a `Login` button in mobile view
  hypha/templates/base-apply.html
Labels: Type: Bug, Type: Patch

#3809 Fix untranslateble strings.
  .github/PULL_REQUEST_TEMPLATE.md
  hypha/apply/activity/models.py
  hypha/apply/activity/templates/activity/notifications.html
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/reminders_block.html
  hypha/apply/funds/templates/funds/includes/submission-list-item.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/templates/submissions/submenu/rounds.html
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/forms/report.py
  hypha/apply/projects/forms/vendor.py
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/apply/projects/templates/application_projects/includes/deliverables_block.html
  hypha/apply/projects/templates/application_projects/includes/supporting_documents.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/paf_export.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/sow_export.html
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/project_partials.py
  hypha/apply/projects/views/vendor.py
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/templates/users/partials/passwordless_login_signup_sent.html
  hypha/apply/users/templates/users/password_reset/confirm.html
  hypha/apply/users/templates/users/passwordless_login_signup.html
  hypha/apply/users/templates/users/register.html
  hypha/apply/users/templates/wagtailusers/users/index.html
  hypha/core/templates/components/dropdown-menu.html
  hypha/templates/base-apply.html
  hypha/templates/includes/messages.html
Labels: Type: Maintenance, Type: Patch

#3815 Reduce the lazy load time for applicant submission on dashboard
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/views.py
Labels: Type: Enhancement, Type: Patch

#3816 Improve UI of applicant dashboard
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/dashboard/templates/dashboard/partials/applicant_projects.html
  hypha/apply/dashboard/templates/dashboard/partials/applicant_submissions.html
Labels: Type: Enhancement, Type: Patch

#3825 Minor fixes to submission all table and status bar on small screens
  hypha/static_src/sass/components/_status-block.scss
  hypha/static_src/sass/components/_table.scss
Labels: Type: Enhancement, Type: Patch

#3824 Fix project current status for applicant dashboard, mobile screen
  hypha/apply/dashboard/templates/dashboard/includes/project_status_bar.html
  hypha/apply/dashboard/templates/dashboard/partials/applicant_projects.html
  hypha/apply/dashboard/templates/dashboard/partials/applicant_submissions.html
  hypha/apply/dashboard/templatetags/dashboard_statusbar_tags.py
  hypha/apply/funds/templates/funds/includes/status_bar.html
Labels: Type: Enhancement, Type: Patch

#3820 Maintenance/pip packages mars 2024
  .pre-commit-config.yaml
  Makefile
  docs/scripts/doc_macros.py
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/wagtail_hooks.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/services/sageintacct/__init__.py
  hypha/apply/projects/services/sageintacct/wrapper/project.py
  hypha/apply/projects/services/sageintacct/wrapper/purchasing.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/vendor.py
  hypha/apply/stream_forms/models.py
  hypha/settings/example.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#3821 Removed registration form, cleaned up login flow
  hypha/apply/users/forms.py
  hypha/apply/users/services.py
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/templates/users/password_reset/form.html
  hypha/apply/users/templates/users/passwordless_login_signup.html
  hypha/apply/users/templates/users/register.html
  hypha/apply/users/tests/test_registration.py
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
  hypha/static_src/sass/components/_link.scss
  hypha/templates/base-apply.html
  hypha/templates/includes/login_button.html
  hypha/templates/includes/org_login_button.html
  hypha/templates/includes/password_login_button.html
  hypha/templates/includes/passwordless_login_button.html
  hypha/templates/includes/register_button.html
Labels: Type: Enhancement, Status: Needs testing, Type: Major, Status: Needs dev testing 🧑‍💻

#3804 Move systemsettings out of public + remove duplicate 404/403 template
  hypha/apply/funds/templates/funds/round.html
  hypha/apply/utils/templates/apply/403.html
  hypha/apply/utils/templates/apply/404.html
  hypha/apply/utils/views.py
  hypha/core/migrations/0003_initial.py
  hypha/core/migrations/0004_move_system_settings_data.py
  hypha/core/models/__init__.py
  hypha/core/models/system_settings.py
  hypha/home/templates/apply_home/apply_home_page.html
  hypha/public/utils/migrations/0013_delete_systemmessagessettings.py
  hypha/templates/403.html
  hypha/templates/404.html
  hypha/templates/base-apply.html
  hypha/templates/styleguide.html
  hypha/urls.py
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#3822 Use existing form_fields for determination edit form
  hypha/apply/determinations/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3823 Use existing form_fields for paf form and sow form for edit paf appro…
  hypha/apply/projects/views/project.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3807 Allow unassign staff reviewers only for inactive reviewers
  hypha/apply/funds/forms.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3832 Add `APPLICANT_PARTNER` visibility to staff comment visibility
  hypha/apply/activity/models.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3826 Replace django-pwned-passwords with pwned-passwords-django
  hypha/settings/django.py
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#3837 Fix table layout of Submissions Results page
  hypha/apply/funds/templates/funds/includes/submission_stats.html
  hypha/apply/funds/templates/funds/submissions_result.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3838 Fix applicant dashboard invoices table Ui for smaller screens
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3835 Add * to file field label instead of Upload button
  hypha/apply/templates/forms/includes/field.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3829 Make PAF form required for fund creation on Project settings enabled
  hypha/apply/funds/admin_forms.py
  hypha/apply/funds/tests/test_admin_form.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3836 Update the global notification dropdrown to use htmx
  hypha/apply/activity/context_processors.py
  hypha/apply/activity/templates/activity/include/notifications_dropdown.html
  hypha/apply/activity/views.py
  hypha/settings/base.py
  hypha/templates/base-apply.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3686 Upgrade Wagtail to 5.2.x LTS
  hypha/apply/categories/admin_helpers.py
  hypha/apply/funds/admin_helpers.py
  hypha/apply/review/admin_helpers.py
  hypha/apply/users/admin_views.py
  hypha/apply/users/templates/wagtailusers/users/index.html
  hypha/apply/users/templates/wagtailusers/users/list.html
  hypha/apply/users/templates/wagtailusers/users/results.html
  hypha/apply/users/wagtail_hooks.py
  hypha/static_src/sass/wagtail_users_list.scss
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Minor

#3756 Add status update batch action to invoices table
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/migrations/0080_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/payment.py
  hypha/apply/projects/service_utils.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/includes/batch_invoice_status_update.html
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/payment.py
  hypha/static_src/javascript/batch-actions.js
  hypha/static_src/sass/components/_projects-table.scss
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch
