Repository HyphaApp/hypha, pull requests merged in 2024-11, with the labels that each got.

#3990 Report reminders
  docs/setup/administrators/setup-notifications.md
  hypha/apply/projects/management/commands/notify_report_due.py
  hypha/apply/projects/migrations/0089_projectreminderfrequency.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/tests/test_commands.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4134 Add the ability to translate submissions
  hypha/apply/funds/fields.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/services.py
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/apply/funds/templates/funds/includes/translate_application_form.html
  hypha/apply/funds/templates/submissions/partials/submission-title.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/templatetags/translate_tags.py
  hypha/apply/funds/tests/test_services.py
  hypha/apply/funds/tests/test_tags.py
  hypha/apply/funds/tests/test_utils.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/utils.py
  hypha/apply/funds/views.py
  hypha/apply/funds/views_partials.py
  hypha/apply/translate/__init__.py
  hypha/apply/translate/management/__init__.py
  hypha/apply/translate/management/commands/__init__.py
  hypha/apply/translate/management/commands/install_languages.py
  hypha/apply/translate/management/commands/uninstall_languages.py
  hypha/apply/translate/tests/__init__.py
  hypha/apply/translate/tests/test_translate.py
  hypha/apply/translate/tests/test_utils.py
  hypha/apply/translate/translate.py
  hypha/apply/translate/utils.py
  hypha/settings/base.py
  hypha/settings/django.py
  hypha/static_src/javascript/translate-application.js
  requirements.txt
Labels: Type: Feature, Type: Minor

#4193 Fix sidebar width of comment form
  hypha/apply/activity/templates/activity/include/comment_form.html
  hypha/static_src/javascript/behaviours/review-score.js
Labels: Type: Enhancement, Type: Patch

#4195 Replace doc_title filter with existing title_text_display property
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/views_partials.py
Labels: Type: Bug, Type: Patch

#4191 Fix bug in submission-text-cleanup that made all tables display in the last field with a table
  hypha/static_src/javascript/submission-text-cleanup.js
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4194 Remove unused jscs config
  .jscsrc
Labels: Type: Maintenance, Type: Patch

#4197 Add SMEX and Lever for Change.
  docs/index.md
Labels: Type: Patch, Type: Documentation

#4185 Rebuild responsive-font-sizes mixin to use clamp
  hypha/static_src/sass/abstracts/_mixins.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4198 Update runtime to python-3.12.7.
  docker/Dockerfile.dev
  runtime.txt
Labels: Type: Maintenance, Type: Patch

#4200 Enhance look and feel of the submission results page
  hypha/apply/funds/templates/funds/submissions_result.html
Labels: Type: Enhancement, Type: Patch

#4199 Revert translations for now. Increase build size to much, Heroku has a 500 MB max
  hypha/apply/funds/fields.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/services.py
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/apply/funds/templates/funds/includes/translate_application_form.html
  hypha/apply/funds/templates/submissions/partials/submission-title.html
  hypha/apply/funds/templatetags/translate_tags.py
  hypha/apply/funds/tests/test_services.py
  hypha/apply/funds/tests/test_tags.py
  hypha/apply/funds/tests/test_utils.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/utils.py
  hypha/apply/funds/views.py
  hypha/apply/funds/views_partials.py
  hypha/apply/translate/__init__.py
  hypha/apply/translate/management/__init__.py
  hypha/apply/translate/management/commands/__init__.py
  hypha/apply/translate/management/commands/install_languages.py
  hypha/apply/translate/management/commands/uninstall_languages.py
  hypha/apply/translate/tests/__init__.py
  hypha/apply/translate/tests/test_translate.py
  hypha/apply/translate/tests/test_utils.py
  hypha/apply/translate/translate.py
  hypha/apply/translate/utils.py
  hypha/settings/base.py
  hypha/settings/django.py
  hypha/static_src/javascript/translate-application.js
  requirements.txt
Labels: Type: Bug, Type: Minor

#4151 Add rolespermissions module, refractor the group and delete submission to use it
  Procfile
  conftest.py
  docs/setup/deployment/development/docker.md
  docs/setup/deployment/development/stand-alone.md
  docs/setup/deployment/production/heroku.md
  docs/setup/deployment/production/stand-alone.md
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/adapters/utils.py
  hypha/apply/api/v1/serializers.py
  hypha/apply/dashboard/templates/dashboard/partials/applicant_submissions.html
  hypha/apply/determinations/tests/test_views.py
  hypha/apply/funds/management/commands/seed_community_lab_application.py
  hypha/apply/funds/management/commands/seed_concept_note.py
  hypha/apply/funds/management/commands/seed_fellowship.py
  hypha/apply/funds/management/commands/seed_rapid_response.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/models/utils.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/reviewers/services.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/tests/factories/models.py
  hypha/apply/funds/tests/test_admin_views.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/tests/views/test_submission_delete.py
  hypha/apply/funds/views.py
  hypha/apply/funds/views_partials.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/service_utils.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/project.py
  hypha/apply/review/models.py
  hypha/apply/users/admin_views.py
  hypha/apply/users/forms.py
  hypha/apply/users/groups.py
  hypha/apply/users/management/commands/migrate_users.py
  hypha/apply/users/migrations/0002_initial_data.py
  hypha/apply/users/migrations/0008_add_staff_permissions.py
  hypha/apply/users/migrations/0009_add_partner_group.py
  hypha/apply/users/migrations/0010_add_community_reviewer_group.py
  hypha/apply/users/migrations/0011_add_applicant_group.py
  hypha/apply/users/migrations/0012_set_applicant_group.py
  hypha/apply/users/migrations/0013_add_approver_group.py
  hypha/apply/users/migrations/0016_add_finance_group.py
  hypha/apply/users/migrations/0017_rename_staff_admin.py
  hypha/apply/users/migrations/0018_add_contracting_group.py
  hypha/apply/users/migrations/0021_groupdesc.py
  hypha/apply/users/migrations/0024_update_is_staff.py
  hypha/apply/users/migrations/0026_delete_groupdesc.py
  hypha/apply/users/models.py
  hypha/apply/users/roles.py
  hypha/apply/users/tests/factories.py
  hypha/apply/users/tests/test_oauth_access.py
  hypha/apply/users/tests/test_views.py
  hypha/apply/utils/testing/tests.py
  hypha/home/wagtail_hooks.py
  hypha/settings/django.py
  hypha/settings/test.py
  requirements.txt
Labels: Type: Enhancement, Type: Minor

#4206 Add missing jsdocs
  hypha/static_src/javascript/batch-actions.js
  hypha/static_src/javascript/behaviours/review-score.js
  hypha/static_src/javascript/document-category.js
  hypha/static_src/javascript/file-uploads.js
  hypha/static_src/javascript/past-reports-pagination.js
  hypha/static_src/javascript/review-form-actions.js
  hypha/static_src/javascript/submission-filters.js
  hypha/static_src/javascript/submission-form-copy.js
  hypha/static_src/javascript/tinymce-word-count.js
  hypha/static_src/javascript/toggle-payment-block.js
Labels: Type: Maintenance, Type: Patch

#4213 Add POSTGRESQL_REPLICATION_USE_PASSFILE env var after breaking change in bitnami/postgresql
  .github/workflows/hypha-ci.yml
Labels: Type: Maintenance, Type: Patch

#4214 Do not use personal shell alias in commands in the docs.
  docs/getting-started/contributing/localization-and-translation.md
Labels: Type: Patch, Type: Documentation

#4136 Hide contracting category documents from restricted users
  hypha/apply/projects/admin_forms.py
  hypha/apply/projects/migrations/0090_contractdocumentcategory_document_access_view.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/apply/projects/templatetags/contract_tools.py
  hypha/apply/projects/views/project.py
  hypha/apply/users/roles.py
Labels: Status: Needs testing, Type: Feature, Type: Minor, Status: Needs dev testing 🧑‍💻

#4216 Display the sealed message the same way as archived
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
Labels: Type: Bug, Type: Patch

#4208 Clean out unused css.
  hypha/apply/dashboard/templates/dashboard/partner_dashboard.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/determinations/templates/determinations/includes/applicant_determination_block.html
  hypha/apply/determinations/templates/determinations/includes/determination_block.html
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/review_sidebar.html
  hypha/apply/funds/templates/submissions/partials/submission-lead.html
  hypha/apply/projects/templates/application_projects/partials/invoice_status.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/todo/templates/todo/todolist_item.html
  hypha/static_src/sass/components/_activity-notifications.scss
  hypha/static_src/sass/components/_banner.scss
  hypha/static_src/sass/components/_heading.scss
  hypha/static_src/sass/components/_icon.scss
  hypha/static_src/sass/components/_link.scss
  hypha/static_src/sass/components/_related-sidebar.scss
  hypha/static_src/sass/components/_reviewer-dash-box.scss
  hypha/static_src/sass/components/_sidebar.scss
  hypha/static_src/sass/components/_wrapper.scss
  hypha/static_src/sass/main.scss
  hypha/static_src/sass/print.scss
Labels: Status: Needs testing, Type: Maintenance, Type: Patch, Status: Needs dev testing 🧑‍💻

#4174 Remove fancybox modal for Contracting
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/apply/projects/templates/application_projects/modals/approve_contract.html
  hypha/apply/projects/templates/application_projects/modals/contracting_documents_upload.html
  hypha/apply/projects/templates/application_projects/modals/submit_contracting_documents.html
  hypha/apply/projects/templates/application_projects/modals/upload_contract.html
  hypha/apply/projects/templates/application_projects/partials/contracting_category_documents.html
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/project_partials.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4209 Remove AwaitingReview view, give reviewer access to submission all
  docs/user-guides/applications/submission-search.md
  hypha/apply/dashboard/templates/dashboard/includes/submissions-waiting-for-review.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/funds/includes/submission-table-row.html
  hypha/apply/funds/templates/funds/submissions_awaiting_review.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/templates/submissions/partials/submissions-inline.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
  hypha/apply/funds/views_all.py
Labels: Type: Enhancement, Type: Minor

#4221 Only display `Show all` for reviewers previous reviews if there's more to show
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
Labels: Type: Enhancement, Type: Patch

#4219 Add the ability to translate submissions (redux)
  .github/workflows/hypha-ci.yml
  docs/setup/administrators/configuration.md
  docs/setup/administrators/machine-translations.md
  docs/setup/deployment/development/stand-alone.md
  docs/setup/deployment/production/stand-alone.md
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/apply/funds/templates/funds/includes/translate_application_form.html
  hypha/apply/funds/templates/submissions/partials/submission-title.html
  hypha/apply/funds/templatetags/translate_tags.py
  hypha/apply/funds/tests/test_tags.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
  hypha/apply/funds/views_partials.py
  hypha/apply/translate/__init__.py
  hypha/apply/translate/fields.py
  hypha/apply/translate/forms.py
  hypha/apply/translate/management/__init__.py
  hypha/apply/translate/management/commands/__init__.py
  hypha/apply/translate/management/commands/install_languages.py
  hypha/apply/translate/management/commands/uninstall_languages.py
  hypha/apply/translate/tests/__init__.py
  hypha/apply/translate/tests/test_translate.py
  hypha/apply/translate/tests/test_utils.py
  hypha/apply/translate/translate.py
  hypha/apply/translate/utils.py
  hypha/settings/base.py
  hypha/settings/django.py
  hypha/static_src/javascript/translate-application.js
  requirements-translate.txt
Labels: Type: Feature, Type: Minor

#4223 Remove `js/toggle-related.js` template line
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
Labels: Type: Bug, Type: Patch

#4227 Merged with weblate
  hypha/locale/cs/LC_MESSAGES/django.po
  hypha/locale/eng_GB/LC_MESSAGES/django.po
  hypha/locale/es/LC_MESSAGES/django.po
  hypha/locale/fr/LC_MESSAGES/django.po
  hypha/locale/ja/LC_MESSAGES/django.po
  hypha/locale/pl/LC_MESSAGES/django.po
  hypha/locale/ru/LC_MESSAGES/django.po
  hypha/locale/sv/LC_MESSAGES/django.po
  hypha/locale/zh_Hans/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4220 Fix submission with "invite to proposal" status stuck in draft if language is not english
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/views.py
  hypha/apply/funds/workflow.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4201 Implement DJP: Django Plugins.
  docs/references/plugins.md
  hypha/settings/base.py
  hypha/urls.py
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4229 Make the application view more printer friendly
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/static_src/sass/print.scss
  hypha/templates/base-apply.html
Labels: Type: Enhancement, Type: Patch

#4230 Removing some more old CSS.
  hypha/apply/activity/templates/activity/partial_comment_message.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/projects_in_contracting.html
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/funds/templates/funds/applicationrevision_list.html
  hypha/apply/funds/templates/funds/includes/round-block.html
  hypha/apply/funds/templates/funds/includes/status-block.html
  hypha/apply/funds/templates/funds/revisions_compare.html
  hypha/apply/users/templates/users/account.html
  hypha/apply/users/templates/wagtailusers/users/edit.html
  hypha/static_src/sass/components/_comment.scss
  hypha/static_src/sass/components/_determination.scss
  hypha/static_src/sass/components/_error-bar.scss
  hypha/static_src/sass/components/_funding-block.scss
  hypha/static_src/sass/components/_profile.scss
  hypha/static_src/sass/components/_revision.scss
  hypha/static_src/sass/components/_revisions.scss
  hypha/static_src/sass/components/_section.scss
  hypha/static_src/sass/main.scss
  hypha/static_src/sass/print.scss
  tailwind.config.js
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4231 Translations update from Hosted Weblate
  hypha/locale/eng_GB/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch
