Repository HyphaApp/hypha, pull requests merged in 2024-06, with the labels that each got.

#3896 Utilize emails as display name on comments when no name is set
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/users/models.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3965 Fix styles to use inline/block instead of left/right etc.
  hypha/static_src/sass/components/_all-submissions-table.scss
  hypha/static_src/sass/components/_form.scss
  hypha/static_src/sass/components/_projects-table.scss
  hypha/static_src/sass/wagtail_users_list.scss
Labels: Type: Maintenance, Type: Patch

#3950 Move addressfield into hypha and update jquery.addressfield.js.
  addressfield/static/jquery.addressfield.min.js
  hypha/addressfield/__init__.py
  hypha/addressfield/fields.py
  hypha/addressfield/models.py
  hypha/addressfield/static/address_form.js
  hypha/addressfield/static/addressfield.min.json
  hypha/addressfield/static/jquery.addressfield.min.js
  hypha/addressfield/templates/addressfield/widgets/nested_with_label.html
  hypha/addressfield/tests.py
  hypha/addressfield/widgets.py
  hypha/apply/funds/blocks.py
  hypha/apply/projects/forms/vendor.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/views/vendor.py
  hypha/settings/django.py
  pyproject.toml
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3928 Show Task list instead of activities in notification dropdown
  hypha/apply/dashboard/templates/dashboard/includes/my-tasks.html
  hypha/apply/todo/templates/todo/todolist_dropdown.html
  hypha/apply/todo/templates/todo/todolist_item.html
  hypha/apply/todo/urls.py
  hypha/apply/todo/views.py
  hypha/templates/base-apply.html
  hypha/urls.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3943 Add user menu as a dropdown
  hypha/templates/base-apply.html
  hypha/templates/includes/login_button.html
  hypha/templates/includes/user_menu.html
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3913 Email notifications on new comments for partners
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/models.py
  hypha/apply/activity/templates/messages/email/comment.html
  hypha/apply/activity/templates/messages/email/partners_update_partner.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/activity/tests/test_messaging.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#3930 Add application submission id everywhere, with an optional prefix
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/django_messages.py
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/adapters/slack.py
  hypha/apply/activity/templates/messages/email/batch_ready_to_review.html
  hypha/apply/activity/templates/messages/email/partners_update_applicant.html
  hypha/apply/activity/templates/messages/email/partners_update_partner.html
  hypha/apply/activity/templates/messages/email/ready_to_review.html
  hypha/apply/activity/templates/messages/email/submission_confirmation.html
  hypha/apply/dashboard/templates/dashboard/community_dashboard.html
  hypha/apply/dashboard/templates/dashboard/partials/applicant_submissions.html
  hypha/apply/dashboard/templates/dashboard/partner_dashboard.html
  hypha/apply/determinations/models.py
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/determinations/templates/determinations/determination_form.html
  hypha/apply/determinations/views.py
  hypha/apply/funds/management/commands/export_submissions_csv.py
  hypha/apply/funds/migrations/0120_applicationsubmission_public_id_and_more.py
  hypha/apply/funds/models/application_revisions.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/applicationrevision_list.html
  hypha/apply/funds/templates/funds/applicationsubmission_confirm_delete.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/apply/funds/templates/funds/includes/submission-list-item.html
  hypha/apply/funds/templates/funds/revisions_compare.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/tests/test_tags.py
  hypha/apply/review/templates/review/review_list.html
  hypha/settings/base.py
  hypha/static_src/javascript/batch-actions.js
  hypha/static_src/sass/base/_base.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3955 Update Screening UI & UX
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/api/v1/screening/__init__.py
  hypha/apply/api/v1/screening/filters.py
  hypha/apply/api/v1/screening/permissions.py
  hypha/apply/api/v1/screening/serializers.py
  hypha/apply/api/v1/screening/tests/__init__.py
  hypha/apply/api/v1/screening/tests/test_views.py
  hypha/apply/api/v1/screening/views.py
  hypha/apply/api/v1/urls.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/management/commands/export_submissions_csv.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/apply/funds/templates/funds/includes/screening_form.html
  hypha/apply/funds/templates/funds/includes/screening_status_block-button.html
  hypha/apply/funds/templates/funds/includes/screening_status_block.html
  hypha/apply/funds/templates/funds/includes/submission-list-item.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/utils.py
  hypha/apply/funds/views.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/vendor_detail.html
  hypha/apply/users/templates/users/login.html
  hypha/static_src/javascript/screening-status.js
  hypha/static_src/sass/components/_button.scss
  hypha/static_src/sass/components/_hypha-grid.scss
  hypha/static_src/sass/main.scss
  hypha/templates/django/forms/widgets/multiple_input.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3991 Add tips for forced push and history search in shell.
  docs/getting-started/contributing/developer-tips.md
Labels: Type: Patch, Type: Documentation

#3992 Give the task bell the same hover state as the user menu
  hypha/templates/base-apply.html
  hypha/templates/includes/user_menu.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#3985 Update the flagging feature to use htmx
  hypha/apply/dashboard/templates/dashboard/dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/flagged.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/flags/templates/flags/flags.html
  hypha/apply/flags/views.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_reviewer_detail.html
  hypha/apply/funds/templates/funds/grouped_application_list.html
  hypha/apply/funds/templates/funds/staff_assignments.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/templates/funds/submissions_staff_flagged.html
  hypha/apply/funds/templates/funds/submissions_user_flagged.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
  hypha/core/navigation.py
  hypha/static_src/javascript/flag.js
  hypha/static_src/sass/components/_button.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4004 Rename staff dashboard template to staff_dashboard.html.
  hypha/apply/dashboard/templates/dashboard/staff_dashboard.html
  hypha/apply/dashboard/views.py
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4005 Fix editing comment updates the comment visibility
  hypha/apply/api/v1/serializers.py
  hypha/apply/api/v1/tests/test_views.py
  hypha/apply/api/v1/views.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#3996 Link comments icon to submission -> communications tab
  hypha/apply/funds/templates/funds/includes/submission-list-item.html
Labels: Type: Enhancement, Type: Patch, Status: Tested - changes/discussion needed 🔨

#3997 Use x-clock on user-menu popover to hide it during initial load
  hypha/templates/includes/user_menu.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4006 Add activity for project title update
  hypha/apply/activity/adapters/activity_feed.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4007 Update node modules and node version
  .nvmrc
  .stylelintrc.yaml
  Makefile
  hypha/static_src/javascript/vendor/alpine-focus.min.js
  hypha/static_src/javascript/vendor/alpine.min.js
  hypha/static_src/javascript/vendor/htmx.min.js
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Patch

#3982 CSV export from all submissions
  hypha/apply/funds/templates/funds/base_submissions_table.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/rounds.html
  hypha/apply/funds/templates/funds/submissions.html
  hypha/apply/funds/utils.py
  hypha/apply/funds/views.py
Labels: Status: Tested - approved for live ✅

#3995 Update Wagtail to v5.2.5
  hypha/apply/dashboard/wagtail_hooks.py
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4003 Delete unused overview views for submissions and projects.
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/views.py
  hypha/apply/projects/templates/application_projects/overview.html
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project.py
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4000 Remove wagtail-cache and wagtail-purge
  Procfile
  docs/setup/deployment/production/stand-alone.md
  hypha/home/models.py
  hypha/public/partner/migrations/0001_add_investments_table_and_partners_page.py
  hypha/settings/base.py
  hypha/settings/dev.py
  hypha/settings/django.py
  hypha/settings/local.py.example
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4010 Name correction in package-lock.json.
  package-lock.json
Labels: Type: Maintenance, Type: Patch

#4013 Add back the source_type filter that was removed by mistake.
  hypha/apply/activity/templatetags/activity_tags.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch
