Repository HyphaApp/hypha, pull requests merged in 2024-08, with the labels that each got.

#4069 Check for `403_title` & `403_body` in SystemMessagesSettings migration
  hypha/core/migrations/0004_move_system_settings_data.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4057 Fix my task mobile view on the dashboard page
  hypha/apply/dashboard/templates/dashboard/includes/my-tasks.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4077 Update Django to 4.2.15.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#4079 Fix primary nav background color on gray background
  hypha/core/templates/core/navigation/primarynav-apply.html
Labels: Type: Bug, Type: Patch

#4043 Speed & appearance improvements to the results page
  hypha/apply/funds/templates/funds/includes/submission_stats.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/utils.py
  hypha/apply/funds/views.py
  hypha/apply/utils/templatetags/apply_tags.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4026 Fix: Task is not removed for staff while project moved to next stage
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4040 Remove tasks from task list
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/migrations/0083_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/dashboard/templates/dashboard/includes/my-tasks.html
  hypha/apply/todo/options.py
  hypha/apply/todo/templates/todo/todolist_dropdown.html
  hypha/apply/todo/templates/todo/todolist_item.html
  hypha/apply/todo/urls.py
  hypha/apply/todo/views.py
  hypha/templates/includes/menu-notifications.html
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#4068 Fix error in View All when no reviewer role image
  hypha/apply/review/views.py
Labels: Type: Bug, Type: Patch

#3970 Notification upon profile update
  hypha/apply/users/views.py
Labels: Type: Enhancement, Type: Patch

#4087 Remove left-over code related to old mobile menu
  hypha/static_src/javascript/main.js
  hypha/static_src/sass/components/_icon.scss
Labels: Type: Maintenance, Type: Patch

#4085 Make the Assign reviewers button use htmx and not old fancybox.
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/tests/test_views.py
Labels: Type: Bug, Status: Needs testing, Type: Patch, Status: Needs dev testing 🧑‍💻

#4099 Fixed broken application detail round URL
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
Labels: Type: Bug, Type: Patch

#4061 Sanitize user `full_name` without roadblocks
  hypha/apply/users/forms.py
  hypha/apply/users/models.py
  hypha/apply/users/utils.py
  requirements.txt
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#4078 Fix submit contract document category permission with required remaining categories instead of remaining categories
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/apply/projects/templatetags/contract_tools.py
  hypha/apply/projects/views/project.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4076 Hide Project task and project settings if projects is disabled
  hypha/apply/projects/models/project.py
  hypha/apply/projects/wagtail_hooks.py
  hypha/apply/todo/options.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4018 Hide PII from external reviewers, along with private reviews
  docs/setup/administrators/configuration.md
  hypha/apply/activity/templates/activity/include/listing_base.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/apply/funds/templates/funds/includes/review_sidebar.html
  hypha/apply/funds/templates/funds/includes/review_sidebar_item.html
  hypha/apply/funds/templatetags/workflow_tags.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/views_partials.py
  hypha/apply/review/templates/review/review_detail.html
  hypha/core/context_processors.py
  hypha/settings/base.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4064 Implemented `Remember me` for passwordless login
  docs/setup/administrators/configuration.md
  hypha/apply/users/forms.py
  hypha/apply/users/services.py
  hypha/apply/users/views.py
  hypha/core/utils.py
  hypha/urls.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4089 Fixed consent prompt always popping up when `Ok` is the only option
  hypha/cookieconsent/static/js/cookieconsent.js
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4059 Make background color consistent across the app
  hypha/apply/dashboard/templates/dashboard/applicant_dashboard.html
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/funds/templates/funds/reminder_confirm_delete.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/templates/application_projects/project_form.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/projects/templates/application_projects/vendor_form.html
  hypha/apply/review/templates/review/review_confirm_delete.html
  hypha/apply/review/templates/review/reviewopinion_confirm_delete.html
  hypha/public/news/templates/news/news_index.html
  hypha/static_src/sass/components/_nav.scss
  hypha/static_src/sass/components/_tabs.scss
  hypha/static_src/sass/components/_wrapper.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4100 Fix docs from being built
  docs/index.md
  hypha/core/middleware/__init__.py
Labels: Type: Bug, Type: Patch

#4095 Assign tasks to project leads instead of staff
  hypha/apply/funds/views.py
  hypha/apply/projects/service_utils.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
  hypha/apply/todo/utils.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4103 Fix js error when related sidebar is not displayed.
  hypha/static_src/javascript/toggle-actions-panel.js
  hypha/static_src/javascript/toggle-related.js
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4113 Add a gap between review buttons for staff.
  hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html
Labels: Type: Bug, Type: Patch

#4102 Update htmx to 2.x
  hypha/static_src/javascript/vendor/htmx-ext-multi-swap.min.js
  hypha/static_src/javascript/vendor/htmx.min.js
  package-lock.json
  package.json
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch
