Repository HyphaApp/hypha, pull requests merged in 2024-02, with the labels that each got.

#3747 Updated to Django 4.2.10.
  requirements.txt
Labels: Type: Maintenance, Type: Patch

#3749 Update test durations and local po files after removing public.
  .test_durations
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#3754 Fix footer link color
  hypha/templates/base-apply.html
Labels: Type: Bug, Type: Minor

#3751 Remove partial_match from search field, have no effect in Wagtail 5.
  hypha/apply/categories/models.py
Labels: Type: Maintenance, Type: Patch

#3734 Documentation overhaul - Fixing formatting issues, autodoc implementation, and added variables for versions.
  .github/workflows/deploy-docs.yml
  CODE_OF_CONDUCT.md
  README.md
  SECURITY.md
  docker/entrypoint.dev.sh
  docs/assets/how-to-login-login-page.png
  docs/assets/how-to-login-nav.png
  docs/assets/how-to-login-w-pass-btn.png
  docs/assets/how-to-login-w-pass-prompt.png
  docs/assets/how-to-login-wo-pw-page.png
  docs/getting-started/architecture.md
  docs/getting-started/contributing/code-contributions.md
  docs/getting-started/contributing/submitting-changes.md
  docs/getting-started/deployment.md
  docs/index.md
  docs/scripts/doc_macros.py
  docs/scripts/gen_ref_pages.py
  docs/setup/administrators/configuration.md
  docs/setup/administrators/setup-email.md
  docs/setup/administrators/setup-notifications.md
  docs/setup/deployment/development/docker.md
  docs/setup/deployment/development/stand-alone.md
  docs/setup/deployment/index.md
  docs/setup/deployment/production/docker.md
  docs/setup/deployment/production/heroku.md
  docs/setup/deployment/production/stand-alone.md
  docs/setup/setup-notifications.md
  docs/user-guides/applications/creating-submisison-application.md
  docs/user-guides/creating-a-user-account.md
  docs/user-guides/login.md
  hypha/apply/api/v1/determination/__init__.py
  hypha/apply/api/v1/reminder/__init__.py
  hypha/apply/dashboard/templatetags/__init__.py
  hypha/apply/projects/management/__init__.py
  hypha/apply/projects/management/commands/__init__.py
  hypha/apply/projects/service_utils.py
  hypha/apply/projects/services/__init__.py
  hypha/apply/projects/views/payment.py
  hypha/cookieconsent/templatetags/__init__.py
  hypha/core/management/__init__.py
  hypha/core/management/commands/__init__.py
  hypha/images/models.py
  hypha/storage_backends.py
  mkdocs.yml
  requirements-docs.txt
Labels: Type: Minor, Type: Documentation

#3755 Hide "Forms" menu in wagtail admin
  hypha/apply/funds/wagtail_hooks.py
Labels: Type: Bug, Type: Minor, Status: Needs dev testing 🧑‍💻

#3764 Fix footer display on the htmx rendered pages
  hypha/templates/includes/_partial-main.html
Labels: Type: Enhancement, Type: Patch

#3765 Fix homepage title and upgrade tailwind to 3.4.x
  hypha/apply/home/templates/apply_home/apply_home_page.html
  hypha/apply/home/templates/apply_home/includes/apply_listing.html
  package-lock.json
  package.json
Labels: Type: Enhancement, Type: Patch

#3679 Add dropdowns to navigation and access nav items via file
  hypha/apply/funds/templates/funds/reviewer_leaderboard.html
  hypha/apply/funds/templates/funds/round.html
  hypha/apply/funds/templates/funds/staff_assignments.html
  hypha/apply/funds/templates/funds/submissions_overview.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/urls.py
  hypha/apply/home/templates/apply_home/apply_home_page.html
  hypha/apply/projects/urls.py
  hypha/apply/users/decorators.py
  hypha/core/navigation.py
  hypha/core/templates/core/navigation/primarynav-apply.html
  hypha/core/templatetags/applynav_tags.py
  hypha/settings/base.py
  hypha/static_src/src/sass/apply/components/_filters.scss
  hypha/templates/base-apply.html
  hypha/templates/includes/primarynav-apply-item.html
  hypha/templates/includes/primarynav-apply.html
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#3761 Fix the 2FA flow
  hypha/apply/users/templates/elevate/elevate.html
  hypha/apply/users/templates/two_factor/_base.html
  hypha/apply/users/templates/two_factor/_base_focus.html
  hypha/apply/users/templates/two_factor/core/backup_tokens.html
  hypha/apply/users/templates/two_factor/core/backup_tokens_password.html
  hypha/apply/users/templates/two_factor/core/setup.html
  hypha/apply/users/templates/two_factor/core/setup_complete.html
  hypha/apply/users/templates/two_factor/core/two_factor_required.html
  hypha/apply/users/templates/two_factor/profile/disable.html
  hypha/apply/users/templates/two_factor/profile/profile.html
  hypha/apply/users/templates/users/account.html
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/tests/test_views.py
  hypha/apply/users/urls.py
  hypha/static_src/src/sass/apply/abstracts/_mixins.scss
  hypha/static_src/src/sass/apply/components/_button.scss
  hypha/urls.py
Labels: Type: Bug, Type: Patch, Status: Needs dev testing 🧑‍💻

#3762 Cleanup unused template from public site
  hypha/templates/blocks/apply_link_block.html
  hypha/templates/blocks/box_block.html
  hypha/templates/blocks/call_to_action_block.html
  hypha/templates/blocks/document_block.html
  hypha/templates/blocks/image_block.html
  hypha/templates/blocks/more_block.html
  hypha/templates/blocks/stream_block.html
  hypha/templates/includes/apply_button.html
  hypha/templates/includes/call_to_action.html
  hypha/templates/includes/relatedcontent.html
  hypha/templates/includes/relatedcontent_card.html
  hypha/templates/includes/sprites.html
Labels: Type: Maintenance, Type: Patch, Status: Needs user testing 👷

#3743 Add setting list_on_front_page to funds and labs.
  hypha/apply/funds/migrations/0115_list_on_front_page.py
  hypha/apply/funds/models/applications.py
  hypha/apply/home/templates/apply_home/includes/apply_listing.html
Labels: Type: Feature, Type: Patch, Status: Needs user testing 👷

#3767 Update test durations and local po files.
  .test_durations
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#3772 Add migration to remove the mailchimp table if it exist
  hypha/core/migrations/0002_auto_20240215_remove_mailhimp.py
Labels: Type: Maintenance, Type: Patch

#3776 Fix naming of status bar variable.
  hypha/static_src/src/sass/apply/components/_status-bar.scss
Labels: Type: Bug, Type: Patch

#3777 Add head end and body end include files. Empty by default to make it easy to insert custom content
  hypha/templates/base.html
  hypha/templates/includes/body_end.html
  hypha/templates/includes/head_end.html
Labels: Type: Enhancement, Type: Patch

#3778 Fixed category labels not being populated
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/views_beta.py
Labels: Type: Bug, Type: Patch

#3769 Update primary nagivation dropdown UX
  hypha/apply/funds/templates/submissions/all.html
  hypha/core/navigation.py
  hypha/core/templates/core/navigation/primarynav-apply.html
Labels: Type: Enhancement, Type: Minor, Status: Needs user testing 👷

#3766 Refractor the home module, move it 1-level up at hypha.home
  hypha/apply/dashboard/wagtail_hooks.py
  hypha/apply/funds/management/commands/seed_community_lab_application.py
  hypha/apply/funds/management/commands/seed_concept_note.py
  hypha/apply/funds/management/commands/seed_fellowship.py
  hypha/apply/funds/management/commands/seed_rapid_response.py
  hypha/apply/funds/management/commands/send_reminders.py
  hypha/apply/funds/tests/factories/models.py
  hypha/apply/funds/tests/test_admin_views.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/home/admin.py
  hypha/apply/projects/management/commands/notify_report_due.py
  hypha/apply/projects/tests/test_commands.py
  hypha/apply/projects/tests/test_forms.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/users/views.py
  hypha/core/context_processors.py
  hypha/home/__init__.py
  hypha/home/apps.py
  hypha/home/factories.py
  hypha/home/migrations/0001_initial.py
  hypha/home/migrations/0002_add_apply_homepage.py
  hypha/home/migrations/__init__.py
  hypha/home/models.py
  hypha/home/templates/apply_home/apply_home_page.html
  hypha/home/templates/apply_home/includes/apply_listing.html
  hypha/home/tests.py
  hypha/home/views.py
  hypha/home/wagtail_hooks.py
  hypha/settings/django.py
Labels: Type: Maintenance, Type: Patch, Status: Needs dev testing 🧑‍💻

#3750 Fix url namespace warnings.
  hypha/apply/projects/urls.py
Labels: Type: Bug, Type: Patch

#3783 Minor improvements to UI of submission beta
  hypha/apply/funds/templates/funds/includes/submission-list-item.html
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Enhancement, Type: Patch, Status: Needs user testing 👷

#3786 Avoid error when no submission values exist.
  hypha/apply/funds/views.py
Labels: Type: Bug, Type: Patch

#3791 Hide preview comment in `application_base.html`
  hypha/apply/funds/templates/funds/application_base.html
Labels: Type: Bug, Type: Patch
