Repository HyphaApp/hypha, pull requests merged in 2025-06, with the labels that each got.

#4559 Upgrade to postgresql 17 and node 24.
  .github/workflows/hypha-ci.yml
  .nvmrc
  docker/Dockerfile
  docker/compose.yaml
  docker/prod/Dockerfile
  hypha/static_src/javascript/vendor/alpine.min.js
  hypha/static_src/javascript/vendor/htmx.min.js
  mkdocs.yml
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Minor

#4567 Fix overlapping lines in header of submission PDF
  hypha/apply/utils/pdfs.py
Labels: Type: Bug, Type: Patch

#4569 Fix submission PDF download when project do not exist
  hypha/apply/funds/views/submission_detail.py
Labels: Type: Bug, Type: Patch

#4570 Set label in project header to "Project lead:" instead of only "Lead:"
  hypha/apply/projects/templates/application_projects/partials/project_lead.html
Labels: Type: Enhancement, Type: Patch

#4552 Expand co-applicant feature to projects
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/services.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/migrations/0127_coapplicant_project_permission.py
  hypha/apply/funds/migrations/0128_alter_coapplicant_role_alter_coapplicantinvite_role.py
  hypha/apply/funds/migrations/0129_coapplicantinvite_project_permission.py
  hypha/apply/funds/models/co_applicants.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/comments.html
  hypha/apply/funds/templates/funds/includes/co-applicant-block.html
  hypha/apply/funds/templates/funds/modals/edit_co_applicant_form.html
  hypha/apply/funds/templates/funds/modals/invite_co_applicant_form.html
  hypha/apply/funds/views/co_applicants.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/reports/permissions.py
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/contract_tools.py
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/tests/test_templatetags.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4575 Correct project template urls.
  hypha/apply/projects/templates/application_projects/partials/contracting_category_documents.html
  hypha/apply/projects/templates/application_projects/partials/supporting_documents.html
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4554 Create a json output version of the open calls on the front page.
  docs/references/open-calls-api-json.md
  hypha/api/__init__.py
  hypha/api/urls.py
  hypha/api/v2/__init__.py
  hypha/api/v2/urls.py
  hypha/api/v2/views.py
  hypha/apply/funds/models/applications.py
  hypha/urls.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4584 Update to python 3.12.11
  .python-version
  docker/Dockerfile
  docker/prod/Dockerfile
Labels: Type: Maintenance, Type: Patch

#4588 Fix ScoreAnswerWidget(Textarea) browser validation issue with tinymce
  hypha/apply/review/blocks.py
  hypha/apply/review/templates/review/review_form.html
  hypha/static_src/sass/components/_form.scss
Labels: Type: Bug, Type: Patch

#4590 Better handling for users entering long names
  hypha/apply/funds/blocks.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/funds/includes/submission-table-row.html
  hypha/apply/funds/templates/submissions/partials/submission-lead.html
Labels: Type: Bug, Type: Patch
