Repository HyphaApp/hypha, pull requests merged in 2025-07, with the labels that each got.

#4596 Restrict permission to invite and update co-applicant in archived submissions and complete projects
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/includes/co-applicant-block.html
  hypha/apply/funds/templatetags/co-applicant_tags.py
Labels: Type: Enhancement, Type: Patch

#4599 Fix Project lead visibility for org memeber like finance
  hypha/apply/projects/templates/application_projects/includes/project_header.html
Labels: Type: Bug, Type: Patch

#4597 Removed nested htmx triggering submission export on search
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Bug, Type: Minor

#4601 Better rendering of checkbox selection
  hypha/apply/stream_forms/blocks.py
  hypha/apply/stream_forms/templates/stream_forms/render_checkbox_field.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4604 Removed nested htmx call causing triggering of submission export.
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Minor

#4603 Refractor traffic light scss -> utility classes
  hypha/apply/review/templatetags/review_tags.py
  hypha/static_src/sass/components/_traffic-light.scss
  hypha/static_src/sass/main.scss
  hypha/static_src/tailwind/utilities/misc.css
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4608 Fixed incorrect pairing of revisions fields & revision CSS
  hypha/apply/funds/views/revisions.py
  hypha/static_src/tailwind/components/html-diff.css
Labels: Type: Patch
