Repository HyphaApp/hypha, pull requests merged in 2025-04, with the labels that each got.

#4479 Fix fund_name attribute error for determination
  hypha/apply/todo/options.py
Labels: Type: Bug, Type: Patch

#4477 Move project detail URL under submission namespace
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/comments.html
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/funds/includes/submission-table-row.html
  hypha/apply/funds/urls.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/urls.py
Labels: Type: Enhancement, Type: Minor

#4485 Make the make test command delete all the test files, not just some of them
  Makefile
Labels: Type: Maintenance, Type: Patch

#4468 Refactor "Reports" into its own app
  hypha/apply/funds/files.py
  hypha/apply/projects/filters.py
  hypha/apply/projects/forms/__init__.py
  hypha/apply/projects/migrations/0025_add_report_models.py
  hypha/apply/projects/migrations/0099_remove_reportconfig_project_and_more.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/reports/__init__.py
  hypha/apply/projects/reports/apps.py
  hypha/apply/projects/reports/filters.py
  hypha/apply/projects/reports/forms.py
  hypha/apply/projects/reports/management/__init__.py
  hypha/apply/projects/reports/management/commands/__init__.py
  hypha/apply/projects/reports/management/commands/notify_report_due.py
  hypha/apply/projects/reports/migrations/0001_initial.py
  hypha/apply/projects/reports/migrations/__init__.py
  hypha/apply/projects/reports/models.py
  hypha/apply/projects/reports/tables.py
  hypha/apply/projects/reports/templates/reports/includes/report_line.html
  hypha/apply/projects/reports/templates/reports/includes/reports.html
  hypha/apply/projects/reports/templates/reports/modals/report_frequency_config.html
  hypha/apply/projects/reports/templates/reports/report_detail.html
  hypha/apply/projects/reports/templates/reports/report_form.html
  hypha/apply/projects/reports/templates/reports/report_list.html
  hypha/apply/projects/reports/templates/reports/reporting.html
  hypha/apply/projects/reports/urls.py
  hypha/apply/projects/reports/views.py
  hypha/apply/projects/tables.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/urls.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project.py
  hypha/settings/django.py
Labels: Type: Maintenance, Type: Minor

#4487 Correct path to load reporting all template.
  hypha/apply/projects/reports/views.py
Labels: Type: Bug, Type: Patch

#4491 Fix todo item -> project waiting invoice
  hypha/apply/todo/options.py
Labels: Type: Bug, Type: Patch

#4490 Fix reporting modal - does not repeat checkbox
  hypha/static_src/javascript/report-calculator.js
Labels: Type: Enhancement, Type: Patch

#4486 Add tests to todo list
  hypha/apply/todo/options.py
  hypha/apply/todo/tests.py
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4510 Fix preview & submit button on application form
  hypha/apply/funds/templates/funds/application_base.html
  hypha/static_src/javascript/application-form.js
Labels: Type: Bug, Type: Patch

#4498 Refractor Project Reports Test cases
  hypha/apply/activity/tests/test_models.py
  hypha/apply/projects/permissions.py
  hypha/apply/projects/reports/tests/__init__.py
  hypha/apply/projects/reports/tests/factories.py
  hypha/apply/projects/reports/tests/test_commands.py
  hypha/apply/projects/reports/tests/test_models.py
  hypha/apply/projects/reports/tests/test_pages.py
  hypha/apply/projects/reports/tests/test_views.py
  hypha/apply/projects/reports/tests/utils.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/tests/test_views.py
Labels: Type: Maintenance, Type: Patch

#4503 Add project reports reference doc & enable mermaid diagrams
  docs/references/project-reports.md
  mkdocs.yml
Labels: Type: Documentation

#4502 Refactor project reports permissions
  hypha/apply/projects/permissions.py
  hypha/apply/projects/reports/permissions.py
  hypha/apply/projects/reports/templates/reports/includes/reports.html
  hypha/apply/projects/reports/views.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templatetags/project_tags.py
  hypha/apply/todo/tests.py
Labels: Type: Enhancement, Type: Patch

#4504 We do not have access to full submission in e-mail so use title and id directly
  hypha/apply/funds/models/submissions.py
Labels: Type: Bug, Type: Patch

#4512 Fix typos in docs, code and comments and "typos" to pre-commit
  .pre-commit-config.yaml
  docs/getting-started/contributing/localization-and-translation.md
  docs/getting-started/contributing/submitting-changes.md
  docs/references/accessibility.md
  docs/references/workflows.md
  docs/setup/administrators/configuration.md
  docs/setup/deployment/development/docker.md
  docs/setup/deployment/development/stand-alone.md
  docs/user-guides/applications/creating-submission-application.md
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/dashboard/tests/test_views.py
  hypha/apply/determinations/templates/determinations/batch_determination_form.html
  hypha/apply/funds/management/commands/sanitize_database.py
  hypha/apply/funds/models/applications.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/notificaitons.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/utils.py
  hypha/apply/funds/views/submission_edit.py
  hypha/apply/projects/migrations/0063_projectsettings_paf_approval_sequential.py
  hypha/apply/projects/migrations/0085_alter_projectsettings_paf_approval_sequential.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/tests/test_views.py
  hypha/apply/projects/views/payment.py
  hypha/apply/stream_forms/files.py
  hypha/apply/translate/utils.py
  hypha/apply/users/forms.py
  hypha/apply/users/templates/two_factor/core/setup.html
  hypha/cookieconsent/migrations/0001_initial.py
  hypha/locale/django.pot
  hypha/settings/base.py
  hypha/static_src/javascript/batch-actions.js
  hypha/static_src/javascript/file-uploads.js
  hypha/static_src/javascript/submission-text-cleanup.js
  hypha/static_src/sass/components/_feed.scss
  hypha/templates/base.html
  hypha/templates/includes/_modal-placeholder.html
  pyproject.toml
Labels: Type: Enhancement, Type: Patch

#4515 Update locale files.
  .test_durations
  hypha/locale/cs/LC_MESSAGES/django.po
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/locale/es/LC_MESSAGES/django.po
  hypha/locale/fr/LC_MESSAGES/django.po
  hypha/locale/ru/LC_MESSAGES/django.po
  hypha/locale/zh_Hans/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4483 Sending e-mail async with celery
  Procfile
  docs/getting-started/architecture.md
  docs/setup/administrators/configuration.md
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/tasks.py
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/activity/tests/test_tasks.py
  hypha/apply/funds/tests/test_models.py
  hypha/celery.py
  hypha/settings/base.py
  hypha/settings/test.py
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Feature, Type: Minor

#4521 Fixed procfile having wrong order of arguments
  Procfile
Labels: Type: Bug, Type: Patch

#4499 Easy fix for duplicate file issue
  hypha/apply/funds/models/mixins.py
  hypha/apply/funds/models/submissions.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Minor

#4032 Enable group stream boxes when in draft and edit mode
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/application_preview.html
  hypha/apply/funds/views/submission_edit.py
  hypha/apply/templates/forms/includes/field.html
  hypha/apply/templates/forms/includes/multi_input_field.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4518 Reporting is disabled by default so adjust text for that.
  hypha/apply/projects/reports/templates/reports/modals/report_frequency_config.html
Labels: Type: Enhancement, Type: Patch

#4522 Fixed `NoReverseMatch` on submitting status update
  hypha/apply/projects/templates/application_projects/partials/invoice_status_table.html
Labels: Type: Bug, Type: Patch, projects rollout

#4523 Update python packages.
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  requirements/translate.txt
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4524 Don't show mobile hamburger on auth and login pages
  hypha/templates/base-apply.html
Labels: Type: Enhancement, Type: Patch

#4525 Fix page being blank on small screens due to table filters
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
Labels: Type: Bug, Type: Patch
