Repository HyphaApp/hypha, pull requests merged in 2025-03, with the labels that each got.

#4429 Use tippy.js for tooltip, remove css tooltip
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/includes/translate_application_form.html
  hypha/apply/projects/templates/application_projects/partials/invoice_detail_actions.html
  hypha/apply/todo/templates/todo/todolist_item.html
  hypha/static_src/sass/components/_tooltip.scss
  hypha/static_src/sass/main.scss
Labels: Type: Maintenance, Type: Patch

#4428 Fix report form, allow saving as draft without filling required fields
  hypha/apply/projects/views/report.py
Labels: Type: Bug, Type: Patch

#4427 Update docstrings of BaseStreamForm class
  hypha/apply/stream_forms/models.py
Labels: Type: Patch, Type: Documentation

#4426 Fix and refractor the submission previews on dashboard
  hypha/apply/dashboard/templates/dashboard/community_dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/flagged.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/templates/dashboard/staff_dashboard.html
  hypha/apply/dashboard/views.py
  hypha/apply/funds/tables.py
Labels: Type: Enhancement, Type: Patch

#4395 Add django_hooks for template hooks
  docs/references/template-hooks.md
  hypha/core/templatehook.py
  hypha/core/templatetags/hooks_tags.py
Labels: Type: Feature, Type: Minor

#4372 Translations update from Hosted Weblate
  hypha/locale/cs/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4432 Missed to update uv.lock with new version.
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4433 Cleanup alert scss file, only used on report detail/form
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/static_src/sass/components/_alert.scss
  hypha/static_src/sass/main.scss
Labels: Type: Maintenance, Type: Patch

#4438 Remove extra /div that mess up the display of send_for_approval dialog
  hypha/apply/projects/templates/application_projects/modals/send_for_approval.html
Labels: Type: Bug, Type: Patch

#4436 Update pre-commit stylelint hook to auto fix
  .pre-commit-config.yaml
Labels: Type: Maintenance, Type: Patch

#4439 Python package upgrades. Mostly to get the file extension fix in django-file-form 3.8.2, for real this time.
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  requirements/translate.txt
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4437 Various UI tweaks to project detail page
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/includes/report_line.html
  hypha/apply/projects/templates/application_projects/includes/reports.html
  hypha/apply/projects/templates/application_projects/partials/invoice_status_table.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/static_src/javascript/past-reports-pagination.js
  hypha/static_src/sass/components/_data-block.scss
  hypha/static_src/tailwind/base/forms.css
  hypha/static_src/tailwind/components/choices.css
  hypha/static_src/tailwind/main.css
Labels: Type: Enhancement, Type: Patch

#4440 Fix "Your previous reviews" show all url plus some styling adjustments.
  hypha/apply/dashboard/templates/dashboard/includes/submissions-waiting-for-review.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/templates/dashboard/staff_dashboard.html
  hypha/static_src/sass/components/_all-submissions-table.scss
Labels: Type: Bug, Type: Patch

#4414 Update communication view to be an independent page
  .test_durations
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/models.py
  hypha/apply/activity/templates/activity/include/comment_form.html
  hypha/apply/activity/templates/messages/email/applicant_base.html
  hypha/apply/activity/templates/messages/email/comment.html
  hypha/apply/activity/templates/messages/email/contract_uploaded.html
  hypha/apply/activity/templates/messages/email/invited_to_proposal.html
  hypha/apply/activity/templates/messages/email/ready_for_invoicing.html
  hypha/apply/activity/templates/messages/email/submission_confirmation.html
  hypha/apply/activity/templates/messages/email/transition.html
  hypha/apply/activity/views.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/comments.html
  hypha/apply/funds/templates/funds/includes/generic_primary_actions.html
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/funds/includes/submission-table-row.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views/comments.py
  hypha/apply/funds/views/submission_detail.py
  hypha/apply/projects/templates/application_projects/includes/contracting_documents.html
  hypha/apply/projects/templates/application_projects/partials/invoice_status.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/views/project.py
Labels: Type: Enhancement, Type: Minor

#4442 Load field form assets always since we have file fields in modals/htmx.
  hypha/apply/stream_forms/fields.py
  hypha/templates/base.html
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Minor

#4453 Fix name of python image in Dockerfile
  docker/Dockerfile
Labels: Type: Bug, Type: Patch

#4452 Block multiple form submits on application form.
  hypha/apply/funds/templates/funds/application_preview.html
  hypha/static_src/javascript/application-form.js
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4454 Add gitleaks to pre-commit to check so no tokens api keys etc. gets commited to the repo
  .pre-commit-config.yaml
Labels: Type: Maintenance, Type: Patch

#4451 Fixed translate `_` being overwritten in elevate email confirmation
  hypha/apply/users/views.py
Labels: Type: Bug, Type: Patch

#4461 Fixes for bugs around exporting applications
  hypha/apply/funds/blocks.py
  hypha/apply/funds/utils.py
Labels: Type: Bug, Type: Patch

#4463 Remove bg colour from checkboxes on submission all view so not to overwrite checked state
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/funds/includes/submission-table-row.html
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Bug, Type: Patch

#4464 Update view link to use heroicon instead of SVG
  hypha/apply/activity/templates/activity/ui/activity-comment-item.html
Labels: Type: Enhancement, Type: Patch

#4470 Replace left/right with start/end for rtl support.
  hypha/static_src/sass/components/_button.scss
  hypha/static_src/sass/components/_cookieconsent.scss
  hypha/static_src/sass/components/_data-block.scss
  hypha/static_src/sass/components/_heading.scss
  hypha/static_src/sass/components/_hypha-grid.scss
  hypha/static_src/sass/components/_list.scss
  hypha/static_src/sass/components/_modal.scss
  hypha/static_src/sass/components/_nprogress.scss
  hypha/static_src/sass/components/_table.scss
  hypha/static_src/sass/print.scss
  hypha/static_src/tailwind/components/choices.css
  hypha/static_src/tailwind/components/daterangepicker.css
Labels: Type: Enhancement, Type: Patch

#4465 Ensure "coversations" tab is always last tab
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/comments.html
  hypha/apply/projects/templates/application_projects/project_detail.html
Labels: Type: Enhancement, Type: Patch

#4457 Required file field behaviour in stream field forms
  hypha/apply/stream_forms/fields.py
  hypha/static_src/javascript/file-uploads.js
Labels: Type: Bug, Type: Patch

#4467 Updated to latest major versions of almost all python packages.
  hypha/settings/base.py
  hypha/templates/base.html
  pyproject.toml
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  requirements/translate.txt
  uv.lock
Labels: Type: Maintenance, Type: Minor

#4425 Use new filters UI with django filters
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/templates/dashboard/staff_dashboard.html
  hypha/apply/funds/templates/funds/base_submissions_table.html
  hypha/apply/funds/templates/funds/grouped_application_list.html
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/reviewer_leaderboard.html
  hypha/apply/funds/templates/funds/reviewer_leaderboard_detail.html
  hypha/apply/funds/templates/funds/rounds.html
  hypha/apply/funds/templates/funds/staff_assignments.html
  hypha/apply/funds/templates/funds/submissions_result.html
  hypha/apply/funds/templatetags/table_tags.py
  hypha/apply/funds/views/all.py
  hypha/apply/projects/filters.py
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/templates/application_projects/project_list.html
  hypha/apply/projects/templates/application_projects/report_list.html
  hypha/apply/projects/templates/application_projects/reporting.html
  hypha/core/templatetags/querystrings.py
  hypha/static_src/javascript/submission-filters.js
  hypha/static_src/sass/components/_filters.scss
  hypha/static_src/sass/main.scss
Labels: Type: Enhancement, Type: Minor

#4466 Modernize the task-list UI
  hypha/apply/activity/templates/activity/notifications.html
  hypha/apply/activity/templates/messages/email/batch_ready_to_review.html
  hypha/apply/activity/templates/messages/email/partners_update_applicant.html
  hypha/apply/activity/templates/messages/email/partners_update_partner.html
  hypha/apply/activity/templates/messages/email/submission_confirmation.html
  hypha/apply/dashboard/templates/dashboard/community_dashboard.html
  hypha/apply/dashboard/templates/dashboard/includes/my-tasks.html
  hypha/apply/dashboard/templates/dashboard/partials/applicant_submissions.html
  hypha/apply/determinations/templates/determinations/determination_detail.html
  hypha/apply/determinations/templates/determinations/includes/determination_button.html
  hypha/apply/funds/management/commands/export_submissions_csv.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/funds/templates/funds/includes/application_header.html
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/funds/includes/submission-table-row.html
  hypha/apply/funds/templates/submissions/partials/submission-lead.html
  hypha/apply/funds/templates/submissions/partials/submission-title.html
  hypha/apply/funds/templatetags/submission_tags.py
  hypha/apply/funds/tests/test_tags.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/templates/application_projects/includes/project_header.html
  hypha/apply/projects/templates/application_projects/partials/project_title.html
  hypha/apply/projects/templates/application_projects/report_detail.html
  hypha/apply/review/templates/review/includes/review_button.html
  hypha/apply/review/templates/review/review_detail.html
  hypha/apply/review/templates/review/review_form.html
  hypha/apply/todo/options.py
  hypha/apply/todo/templates/todo/todolist_dropdown.html
  hypha/apply/todo/templates/todo/todolist_item.html
  hypha/apply/todo/views.py
  hypha/core/templates/components/admin_bar.html
  hypha/settings/base.py
Labels: Type: Enhancement, Type: Minor

#4474 Add a Clear current search query, filters and sorts button on django-filter tables
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
Labels: Type: Enhancement, Type: Patch
