Repository HyphaApp/hypha, pull requests merged in 2025-01, with the labels that each got.

#4311 Python updates 2024-12-31.
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4308 Refractor fund views
  hypha/apply/funds/services.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/views.py
  hypha/apply/funds/views/__init__.py
  hypha/apply/funds/views/all.py
  hypha/apply/funds/views/partials.py
  hypha/apply/funds/views/reminders.py
  hypha/apply/funds/views/results.py
  hypha/apply/funds/views/reviewer_leaderboard.py
  hypha/apply/funds/views/revisions.py
  hypha/apply/funds/views/staff_assignments.py
  hypha/apply/funds/views/submission_delete.py
  hypha/apply/funds/views/submission_detail.py
  hypha/apply/funds/views/submission_edit.py
  hypha/apply/funds/views/translate.py
Labels: Type: Maintenance, Type: Minor

#4314 Disable werkzeug logging by default, to noisy.
  hypha/settings/dev.py
Labels: Type: Maintenance, Type: Patch

#4272 Set default reporting frequency as disable
  hypha/apply/projects/migrations/0095_alter_reportconfig_disable_reporting.py
  hypha/apply/projects/models/report.py
  hypha/apply/projects/templates/application_projects/includes/reports.html
  hypha/apply/projects/tests/test_commands.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/tests/test_views.py
Labels: Type: Enhancement, Type: Patch

#4306 Make lead update modals UI same for both projects and applications
  .gitignore
  hypha/apply/funds/forms.py
  hypha/apply/funds/templates/submissions/partials/submission-lead.html
  hypha/apply/funds/views/submission_edit.py
  hypha/apply/projects/templates/application_projects/modals/lead_update.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4294 Update the UI to switch user aka become user
  hypha/apply/users/forms.py
  hypha/apply/users/models.py
  hypha/apply/users/templates/users/account.html
  hypha/apply/users/templates/users/become.html
  hypha/apply/users/tests/test_forms.py
  hypha/apply/users/urls.py
  hypha/apply/users/views.py
  hypha/core/context_processors.py
  hypha/settings/base.py
  hypha/static_src/tailwind/main.css
  hypha/templates/base.html
  hypha/templates/includes/hijack-bar.html
  hypha/templates/includes/user_menu.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4316 Added `mailto` URLs (when appropriate) where email addresses are displayed
  hypha/apply/funds/templates/funds/includes/rendered_answers.html
  hypha/apply/users/templates/wagtailusers/users/list.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4317 Minor lint fixes
  hypha/static_src/tailwind/main.css
Labels: Type: Maintenance, Type: Patch

#4305 Fix report submit notification to stream field form flow
  hypha/apply/projects/views/report.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4293 Removed unused code related to the v1 & Intacct API
  hypha/apply/api/__init__.py
  hypha/apply/api/urls.py
  hypha/apply/api/v1/__init__.py
  hypha/apply/api/v1/determination/__init__.py
  hypha/apply/api/v1/determination/permissions.py
  hypha/apply/api/v1/determination/serializers.py
  hypha/apply/api/v1/determination/utils.py
  hypha/apply/api/v1/determination/views.py
  hypha/apply/api/v1/filters.py
  hypha/apply/api/v1/mixin.py
  hypha/apply/api/v1/pagination.py
  hypha/apply/api/v1/permissions.py
  hypha/apply/api/v1/projects/__init__.py
  hypha/apply/api/v1/projects/serializers.py
  hypha/apply/api/v1/projects/views.py
  hypha/apply/api/v1/reminder/__init__.py
  hypha/apply/api/v1/reminder/serializers.py
  hypha/apply/api/v1/reminder/views.py
  hypha/apply/api/v1/review/__init__.py
  hypha/apply/api/v1/review/fields.py
  hypha/apply/api/v1/review/permissions.py
  hypha/apply/api/v1/review/serializers.py
  hypha/apply/api/v1/review/tests/__init__.py
  hypha/apply/api/v1/review/utils.py
  hypha/apply/api/v1/review/views.py
  hypha/apply/api/v1/serializers.py
  hypha/apply/api/v1/stream_serializers.py
  hypha/apply/api/v1/urls.py
  hypha/apply/api/v1/utils.py
  hypha/apply/api/v1/views.py
  hypha/apply/projects/migrations/0096_remove_invoicedeliverable_deliverable_and_more.py
  hypha/apply/projects/models/__init__.py
  hypha/apply/projects/models/payment.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/services/__init__.py
  hypha/apply/projects/services/sageintacct/__init__.py
  hypha/apply/projects/services/sageintacct/exceptions.py
  hypha/apply/projects/services/sageintacct/sageintacctsdk.py
  hypha/apply/projects/services/sageintacct/utils.py
  hypha/apply/projects/services/sageintacct/wrapper/__init__.py
  hypha/apply/projects/services/sageintacct/wrapper/api_base.py
  hypha/apply/projects/services/sageintacct/wrapper/constants.py
  hypha/apply/projects/services/sageintacct/wrapper/invoice.py
  hypha/apply/projects/services/sageintacct/wrapper/project.py
  hypha/apply/projects/services/sageintacct/wrapper/purchasing.py
  hypha/apply/projects/templates/application_projects/includes/deliverables_block.html
  hypha/apply/projects/templates/application_projects/invoice_admin_detail.html
  hypha/apply/projects/templates/application_projects/invoice_detail.html
  hypha/apply/projects/templatetags/invoice_tools.py
  hypha/apply/projects/tests/factories.py
  hypha/apply/projects/tests/test_models.py
  hypha/apply/projects/utils.py
  hypha/apply/projects/views/payment.py
  hypha/settings/django.py
  hypha/static_src/javascript/deliverables.js
  hypha/urls.py
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4324 Fix project section header button's layout
  hypha/apply/projects/templates/application_projects/includes/project_documents.html
  hypha/apply/projects/templates/application_projects/partials/contracting_category_documents.html
  hypha/apply/projects/templates/application_projects/partials/supporting_documents.html
  hypha/static_src/sass/components/_docs-block.scss
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4323 Remove any limit on rows exported when the submission is exported
  hypha/apply/funds/views/all.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4287 More clean up in how we load js and css files
  hypha/apply/activity/templates/activity/include/comment_form.html
  hypha/apply/dashboard/templates/dashboard/contracting_dashboard.html
  hypha/apply/dashboard/templates/dashboard/finance_dashboard.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/templates/dashboard/staff_dashboard.html
  hypha/apply/determinations/templates/determinations/base_determination_form.html
  hypha/apply/funds/templates/funds/application_base.html
  hypha/apply/funds/templates/funds/applicationsubmission_community_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/applicationsubmission_form.html
  hypha/apply/funds/templates/funds/applicationsubmission_reviewer_detail.html
  hypha/apply/funds/templates/funds/base_submissions_table.html
  hypha/apply/funds/templates/funds/grouped_application_list.html
  hypha/apply/funds/templates/funds/includes/delegated_form_base.html
  hypha/apply/funds/templates/funds/includes/dialog_form_base.html
  hypha/apply/funds/templates/funds/includes/translate_application_form.html
  hypha/apply/funds/templates/funds/includes/update_reviewer_form.html
  hypha/apply/funds/templates/funds/rounds.html
  hypha/apply/projects/templates/application_projects/includes/invoices.html
  hypha/apply/projects/templates/application_projects/invoice_form.html
  hypha/apply/projects/templates/application_projects/invoice_list.html
  hypha/apply/projects/templates/application_projects/modals/report_frequency_config.html
  hypha/apply/projects/templates/application_projects/project_approval_detail.html
  hypha/apply/projects/templates/application_projects/project_approval_form.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/templates/application_projects/project_form.html
  hypha/apply/projects/templates/application_projects/project_sow_form.html
  hypha/apply/projects/templates/application_projects/report_form.html
  hypha/apply/review/templates/review/review_edit_form.html
  hypha/apply/review/templates/review/review_form.html
  hypha/apply/stream_forms/fields.py
  hypha/apply/users/templates/wagtailusers/users/edit.html
  hypha/settings/base.py
  hypha/static_src/javascript/application-form-links-new-window.js
  hypha/static_src/javascript/application-form.js
  hypha/static_src/javascript/document-category.js
  hypha/static_src/javascript/file-uploads.js
  hypha/static_src/javascript/toggle-payment-block.js
  hypha/templates/base.html
  hypha/templates/includes/messages.html
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4326 Update stand-alone dev setup docs.
  docs/getting-started/contributing/contribute-to-documentation.md
  docs/getting-started/contributing/developer-tips.md
  docs/setup/administrators/cron-jobs.md
  docs/setup/deployment/development/stand-alone.md
  docs/setup/deployment/production/stand-alone.md
Labels: Type: Patch, Type: Documentation

#4325 Docker development environment update
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/Dockerfile.dockerignore
  docker/compose.yaml
  docker/docker-compose.yaml
  docker/entrypoint.dev.sh
  docker/entrypoint.sh
  docker/nginx/hypha.conf
  docker/prod/Dockerfile
  docker/prod/Dockerfile.dockerignore
  docker/prod/README.md
  docker/prod/entrypoint.sh
  docs/setup/deployment/development/docker.md
  docs/setup/deployment/production/docker.md
  mkdocs.yml
Labels: Type: Maintenance, Type: Patch, Type: Documentation

#4331 Remove API_BASE_URL references
  docs/setup/deployment/production/heroku.md
  docs/setup/deployment/production/stand-alone.md
Labels: Type: Patch, Type: Documentation

#4332 Fix warnings from docs build.
  docs/getting-started/contributing/developer-tips.md
  docs/references/user-roles.md
Labels: Type: Patch, Type: Documentation

#4335 Fix docs build, minor edit to docs so it builds with CI
  docs/index.md
  hypha/apply/funds/workflows/definitions/__init__.py
  hypha/apply/funds/workflows/models/__init__.py
  hypha/apply/funds/workflows/registry.py
Labels: Type: Bug, Type: Patch

#4337 Update to release-drafter v6.
  .github/workflows/release-drafter.yml
Labels: Type: Maintenance, Type: Patch

#4315 Translations update from Hosted Weblate
  hypha/locale/ta/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4338 Improvement to scroll-to-top component
  hypha/core/templates/components/scroll-to-top.html
Labels: Type: Enhancement, Type: Patch

#4343 Update Django to 4.2.18 and other minor python package updates.
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4347 Updated locale en files.
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4353 Add nh3 filter so HTML tags do not get escaped.
  hypha/apply/activity/templates/activity/notifications.html
Labels: Type: Bug, Status: Needs testing, Type: Patch, Status: Needs dev testing 🧑‍💻

#4340 Clean out old migration code and drupal id migration field.
  hypha/apply/activity/management/commands/migrate_comments.py
  hypha/apply/categories/categories_seed.py
  hypha/apply/categories/management/__init__.py
  hypha/apply/categories/management/commands/__init__.py
  hypha/apply/categories/management/commands/seed_categories.py
  hypha/apply/determinations/management/__init__.py
  hypha/apply/determinations/management/commands/__init__.py
  hypha/apply/determinations/management/commands/migrate_concept_determinations.py
  hypha/apply/determinations/management/commands/migrate_proposal_determinations.py
  hypha/apply/determinations/migrations/0017_remove_drupal_id_field.py
  hypha/apply/determinations/models.py
  hypha/apply/funds/management/commands/migrate_community_lab_applications.py
  hypha/apply/funds/management/commands/migrate_concept_notes.py
  hypha/apply/funds/management/commands/migrate_concept_notes_502.py
  hypha/apply/funds/management/commands/migrate_concept_notes_503.py
  hypha/apply/funds/management/commands/migrate_fellowship_application.py
  hypha/apply/funds/management/commands/migrate_fellowship_proposals.py
  hypha/apply/funds/management/commands/migrate_proposals.py
  hypha/apply/funds/management/commands/migrate_rr_applications.py
  hypha/apply/funds/management/commands/migration_base.py
  hypha/apply/funds/management/commands/seed_community_lab_application.py
  hypha/apply/funds/management/commands/seed_concept_note.py
  hypha/apply/funds/management/commands/seed_fellowship.py
  hypha/apply/funds/management/commands/seed_rapid_response.py
  hypha/apply/funds/migrations/0122_remove_drupal_id_field.py
  hypha/apply/funds/models/submissions.py
  hypha/apply/funds/views/results.py
  hypha/apply/review/management/commands/fix_stream_field_ids.py
  hypha/apply/review/management/commands/migrate_community_lab_reviews.py
  hypha/apply/review/management/commands/migrate_concept_reviews.py
  hypha/apply/review/management/commands/migrate_fellowship_application_reviews.py
  hypha/apply/review/management/commands/migrate_fellowship_proposal_reviews.py
  hypha/apply/review/management/commands/migrate_proposal_reviews.py
  hypha/apply/review/management/commands/migrate_rr_reviews.py
  hypha/apply/review/management/commands/migration_review_base.py
  hypha/apply/review/migrations/0026_remove_drupal_id_field.py
  hypha/apply/review/models.py
  hypha/apply/users/management/commands/migrate_users.py
  hypha/apply/users/migrations/0027_remove_drupal_id_field.py
  hypha/apply/users/models.py
  hypha/images/migrations/0007_remove_drupal_id_field.py
  hypha/images/models.py
Labels: Type: Maintenance, Type: Patch

#4362 Load htmx script in page bottom since we cannot defer it.
  hypha/templates/base.html
Labels: Status: Needs testing, Type: Maintenance, Type: Patch, Status: Needs dev testing 🧑‍💻

#4319 Remove select2 and uses choices.js
  hypha/apply/categories/blocks.py
  hypha/apply/dashboard/static/js/django_select2-checkboxes.js
  hypha/apply/dashboard/static/js/select2.multi-checkboxes.js
  hypha/apply/funds/forms.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
  hypha/apply/funds/templates/funds/includes/update_meta_terms_form.html
  hypha/apply/funds/widgets.py
  hypha/apply/projects/filters.py
  hypha/settings/django.py
  hypha/static_src/javascript/submission-filters.js
  hypha/static_src/sass/abstracts/_variables.scss
  hypha/static_src/sass/components/_filters.scss
  hypha/static_src/sass/components/_form.scss
  hypha/static_src/sass/components/_select2.scss
  hypha/static_src/sass/main.scss
  hypha/static_src/tailwind/components/choices.css
  hypha/templates/base.html
  hypha/urls.py
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Minor

#4359 Add @view-transition auto to root element.
  hypha/static_src/tailwind/base/core.css
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4366 Use wagtail_modeladmin as separate package
  hypha/apply/categories/admin.py
  hypha/apply/categories/admin_helpers.py
  hypha/apply/categories/admin_views.py
  hypha/apply/determinations/admin.py
  hypha/apply/determinations/admin_views.py
  hypha/apply/funds/admin.py
  hypha/apply/funds/admin_helpers.py
  hypha/apply/funds/admin_views.py
  hypha/apply/funds/wagtail_hooks.py
  hypha/apply/projects/admin.py
  hypha/apply/projects/admin_views.py
  hypha/apply/projects/wagtail_hooks.py
  hypha/apply/review/admin.py
  hypha/apply/review/admin_helpers.py
  hypha/apply/review/admin_views.py
  hypha/core/wagtail/admin/options.py
  hypha/settings/django.py
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  uv.lock
Labels: Type: Maintenance, Type: Patch

#3676 Remove unused pagedown css demo.css
  hypha/apply/activity/forms.py
  hypha/apply/utils/blocks.py
  hypha/core/widgets.py
  public/pagedown/demo/browser/demo.css
Labels: Type: Maintenance, Type: Patch

#4304 Fix batch determination different forms issue
  hypha/apply/determinations/views.py
  hypha/apply/funds/utils.py
  hypha/apply/funds/views/all.py
  hypha/apply/funds/views/partials.py
Labels: Type: Bug, Type: Minor

#4360 Small fixes to the submissions table
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/templates/submissions/submenu/bulk-update-lead.html
  hypha/apply/funds/templates/submissions/submenu/category.html
  hypha/apply/funds/templates/submissions/submenu/change-status.html
  hypha/apply/funds/templates/submissions/submenu/funds.html
  hypha/apply/funds/templates/submissions/submenu/leads.html
  hypha/apply/funds/templates/submissions/submenu/meta-terms.html
  hypha/apply/funds/templates/submissions/submenu/reviewers.html
  hypha/apply/funds/templates/submissions/submenu/rounds.html
  hypha/apply/funds/templatetags/table_tags.py
  hypha/apply/funds/views/all.py
  hypha/apply/search/query_parser.py
Labels: Type: Enhancement, Type: Patch
