Repository HyphaApp/hypha, pull requests merged in 2025-02, with the labels that each got.

#4368 Replace repeat icon from rotate icon for rounds
  hypha/apply/utils/admin.py
Labels: Type: Maintenance, Type: Patch

#4371 Raise PermissionDenied if anon user tries to access create_password
  hypha/apply/users/views.py
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/locale/ta/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4350 Remove need for DjangoMessagesAdapter
  hypha/apply/activity/adapters/__init__.py
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/adapters/django_messages.py
  hypha/apply/activity/messaging.py
  hypha/apply/activity/migrations/0086_remove_django_messages_adapter.py
  hypha/apply/activity/options.py
  hypha/apply/determinations/tests/test_views.py
  hypha/apply/determinations/views.py
  hypha/apply/funds/services.py
  hypha/apply/funds/views/all.py
  hypha/apply/funds/views/reminders.py
  hypha/apply/funds/views/submission_edit.py
  hypha/apply/funds/views/translate.py
  hypha/apply/projects/templates/application_projects/includes/report_line.html
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
  hypha/apply/projects/views/report.py
Labels: Type: Enhancement, Status: Needs testing, Type: Patch, Status: Needs dev testing 🧑‍💻

#4377 Improve no results page of submission list
  hypha/apply/funds/templates/submissions/all.html
Labels: Type: Enhancement, Type: Patch

#4374 Unify messages styles
  hypha/apply/funds/services.py
  hypha/apply/funds/views/all.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/views/payment.py
  hypha/apply/projects/views/project.py
  hypha/apply/users/templates/users/password_reset/confirm.html
  hypha/apply/users/templates/users/password_reset/form.html
  hypha/static_src/sass/components/_activity-notifications.scss
  hypha/static_src/sass/components/_messages.scss
  hypha/static_src/sass/main.scss
  hypha/templates/includes/message_item.html
  hypha/templates/includes/messages.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4378 Fix generated requirements files to ensure hashes are includes in all
  .pre-commit-config.yaml
  docs/setup/administrators/machine-translations.md
  docs/setup/deployment/production/stand-alone.md
  pyproject.toml
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  requirements/translate-cpu.txt
  requirements/translate.txt
  uv.lock
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4375 Change help text in stream field to RichText
  hypha/apply/categories/blocks.py
  hypha/apply/determinations/migrations/0018_help_text_rich_text.py
  hypha/apply/determinations/tests/test_admin_views.py
  hypha/apply/funds/blocks.py
  hypha/apply/funds/migrations/0123_help_text_rich_text.py
  hypha/apply/funds/tests/test_admin_views.py
  hypha/apply/projects/migrations/0097_help_text_rich_text.py
  hypha/apply/review/migrations/0027_help_text_rich_text.py
  hypha/apply/review/tests/test_admin_views.py
  hypha/apply/stream_forms/blocks.py
  hypha/apply/stream_forms/models.py
  hypha/apply/stream_forms/testing/factories.py
  hypha/apply/templates/forms/includes/field.html
  hypha/static_src/javascript/submission-form-copy.js
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Patch

#4341 Rename meta terms to tags
  docs/references/wagtail-admin.md
  docs/setup/administrators/configuration.md
  hypha/apply/categories/migrations/0007_rename_meta_terms_to_tags.py
  hypha/apply/categories/models.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/tables.py
  hypha/apply/funds/templates/funds/includes/admin_primary_actions.html
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/funds/templates/submissions/partials/meta-terms-card.html
  hypha/apply/funds/templates/submissions/submenu/meta-terms.html
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4381 Load Choices.js with data-js-choices.
  hypha/apply/activity/forms.py
  hypha/apply/activity/templates/activity/include/comment_form.html
  hypha/apply/funds/forms.py
  hypha/apply/funds/templates/funds/includes/update_reviewer_form.html
  hypha/apply/funds/templates/funds/modals/update_partner_form.html
  hypha/apply/funds/templates/submissions/submenu/bulk-update-reviewers.html
  hypha/apply/users/forms.py
  hypha/apply/users/templates/users/become.html
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4392 Add animation to details tag
  hypha/apply/funds/templates/submissions/partials/submission-lead.html
  hypha/apply/projects/templates/application_projects/partials/project-lead.html
  hypha/apply/projects/templates/application_projects/partials/project_title.html
  hypha/static_src/sass/base/_base.scss
  hypha/static_src/tailwind/base/core.css
Labels: Type: Enhancement, Type: Patch

#4379 Implement ViewTransition for htmx and tabs
  hypha/apply/activity/templates/activity/include/comment_list.html
  hypha/apply/activity/templates/activity/ui/edit_comment_form.html
  hypha/apply/flags/templates/flags/flags.html
  hypha/apply/funds/templates/funds/includes/screening_status_block-button.html
  hypha/apply/funds/templates/funds/includes/submission-list-row.html
  hypha/apply/funds/templates/funds/includes/submission-table-row.html
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/users/templates/elevate/elevate.html
  hypha/apply/users/templates/users/account.html
  hypha/apply/users/templates/users/passwordless_login_signup.html
  hypha/static_src/javascript/tabs.js
Labels: Type: Enhancement, Type: Patch

#4383 Replace everything in sprites.html with heroicons.
  hypha/apply/projects/templates/application_projects/partials/invoice_status.html
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/todo/options.py
  hypha/apply/todo/templates/todo/todolist_item.html
  hypha/templates/base.html
  hypha/templates/includes/sprites.html
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4385 Update Django messages to reuse toast component used by htmx
  hypha/static_src/tailwind/main.css
  hypha/templates/base.html
  hypha/templates/includes/_toast-placeholder.html
  hypha/templates/includes/message_item.html
  hypha/templates/includes/messages.html
Labels: Status: Tested - approved for live ✅, Type: Maintenance, Type: Patch

#4390 Added ability to set initial status when creating a project
  docs/setup/administrators/configuration.md
  hypha/apply/activity/adapters/activity_feed.py
  hypha/apply/activity/tests/test_messaging.py
  hypha/apply/determinations/tests/test_views.py
  hypha/apply/funds/tests/test_views.py
  hypha/apply/funds/views/submission_edit.py
  hypha/apply/projects/forms/project.py
  hypha/apply/projects/forms/utils.py
  hypha/apply/projects/models/project.py
  hypha/apply/projects/utils.py
  hypha/settings/base.py
Labels: Status: Tested - approved for live ✅, Type: Feature, Type: Minor

#4402 Fix alpinejs discrepencies, typos in review score
  hypha/apply/review/templates/review/review_edit_form.html
  hypha/apply/review/templates/review/review_form.html
Labels: Type: Bug, Type: Patch

#4405 Docs description update
  docs/index.md
Labels: Type: Documentation

#4404 Added marksafe to the file upload type help_text
  hypha/apply/stream_forms/blocks.py
Labels: Type: Bug, Type: Patch

#4349 Merge application and project communication tabs
  hypha/apply/activity/services.py
  hypha/apply/activity/templates/activity/include/activity_list.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/activity/urls.py
  hypha/apply/activity/views.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/urls.py
  hypha/apply/funds/views/partials.py
  hypha/apply/projects/migrations/0098_move_project_comments_to_application.py
  hypha/apply/projects/templates/application_projects/project_detail.html
  hypha/apply/projects/urls.py
  hypha/apply/projects/views/__init__.py
  hypha/apply/projects/views/project_partials.py
Labels: Type: Enhancement, Type: Minor

#4407 Update to include project id in the project header
  hypha/apply/projects/templates/application_projects/partials/project_title.html
Labels: Type: Enhancement, Type: Patch

#4410 The runtime.txt file is deprecated by Heroku, it has been replaced by the more widely supported .python-version file
  runtime.txt
Labels: Type: Maintenance, Type: Patch

#4412 Update to python 3.12.9
  .python-version
  docker/Dockerfile
  docker/prod/Dockerfile
  pyproject.toml
  uv.lock
Labels: Type: Maintenance, Type: Patch

#4399 Allow users so select Hypha language
  hypha/core/context_processors.py
  hypha/settings/base.py
  hypha/settings/django.py
  hypha/templates/base-apply.html
  hypha/templates/includes/language-switcher.html
  hypha/urls.py
Labels: Type: Feature, Type: Minor

#4400 Update submit for approval modal appearance and text
  hypha/apply/projects/templates/application_projects/modals/send_for_approval.html
Labels: Type: Enhancement, Status: Needs testing, Type: Patch, Status: Needs dev testing 🧑‍💻

#4409 Correcting view all urls on staff and reviewer dashboard.
  hypha/apply/dashboard/templates/dashboard/includes/submissions-waiting-for-review.html
  hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
  hypha/apply/dashboard/templates/dashboard/staff_dashboard.html
  hypha/apply/dashboard/views.py
Labels: Type: Bug, Type: Patch

#4416 Allow actions for deploying docs and release drafter to be run manually.
  .github/workflows/deploy-docs.yml
  .github/workflows/release-drafter.yml
Labels: Type: Maintenance, Type: Patch

#4415 Update locales part 2
  hypha/locale/cs/LC_MESSAGES/django.po
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/locale/es/LC_MESSAGES/django.po
  hypha/locale/fr/LC_MESSAGES/django.po
  hypha/locale/ru/LC_MESSAGES/django.po
  hypha/locale/zh_Hans/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4423 Can not use i18n when sending mail with MarkdownMail.
  hypha/apply/users/views.py
Labels: Type: Bug, Type: Patch

#4418 Implement modern text wrap pretty and balance
  hypha/static_src/sass/base/_base.scss
  hypha/static_src/sass/base/_typography.scss
Labels: Type: Enhancement, Status: Needs testing, Type: Patch, Status: Needs dev testing 🧑‍💻

#4422 Use same style for notification view as used on communication tab.
  hypha/apply/activity/templates/activity/notifications.html
  hypha/apply/activity/views.py
Labels: Type: Enhancement, Type: Patch

#4421 Sort project table by created_at instead of unused end_date.
  hypha/apply/projects/tables.py
Labels: Type: Enhancement, Type: Patch
