Repository HyphaApp/hypha, pull requests merged in 2025-05, with the labels that each got.

#4527 Show invoice stamping for approval steps & all after
  hypha/apply/projects/views/payment.py
Labels: Type: Bug, Type: Patch, projects rollout

#4519 Consistent use of title_text_display in e-mail notifications.
  hypha/apply/activity/templates/messages/email/assign_paf_approvers.html
  hypha/apply/activity/templates/messages/email/batch_ready_to_review.html
  hypha/apply/activity/templates/messages/email/contract_uploaded.html
  hypha/apply/activity/templates/messages/email/invoice_approved.html
  hypha/apply/activity/templates/messages/email/invoice_status_updated.html
  hypha/apply/activity/templates/messages/email/invoice_updated.html
  hypha/apply/activity/templates/messages/email/paf_for_approval.html
  hypha/apply/activity/templates/messages/email/partners_update_applicant.html
  hypha/apply/activity/templates/messages/email/partners_update_partner.html
  hypha/apply/activity/templates/messages/email/project_created.html
  hypha/apply/activity/templates/messages/email/project_final_approval.html
  hypha/apply/activity/templates/messages/email/project_request_change.html
  hypha/apply/activity/templates/messages/email/ready_for_contracting.html
  hypha/apply/activity/templates/messages/email/report_frequency.html
  hypha/apply/activity/templates/messages/email/report_notify.html
  hypha/apply/activity/templates/messages/email/report_skipped.html
  hypha/apply/activity/templates/messages/email/report_submitted.html
  hypha/apply/activity/templates/messages/email/sent_to_compliance.html
  hypha/apply/activity/templates/messages/email/submission_confirmation.html
  hypha/apply/activity/templates/messages/email/submit_contract_documents.html
  hypha/apply/funds/models/submissions.py
  hypha/apply/projects/models/project.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4526 Update PROJECTS_ENABLED to use middleware for url blocking
  hypha/apply/funds/urls.py
  hypha/apply/projects/middleware.py
  hypha/apply/projects/tests/test_middleware.py
  hypha/settings/django.py
Labels: Type: Enhancement, Status: Tested - approved for live ✅, Type: Patch

#4531 Fix/handle htmx requests for private page on session expiry
  hypha/core/middleware/htmx.py
  hypha/core/middleware/tests/__init__.py
  hypha/core/middleware/tests/test_htmx_auth_redirect.py
  hypha/settings/django.py
Labels: Type: Bug, Status: Tested - approved for live ✅, Type: Patch

#4536 Updated Django to v4.2.21 and other python packages minor upgrades.
  pyproject.toml
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  requirements/translate.txt
  uv.lock
Labels: Type: Maintenance, Type: Minor

#4534 Updated all locales and including markdown templates
  hypha/locale/cs/LC_MESSAGES/django.po
  hypha/locale/django.pot
  hypha/locale/en/LC_MESSAGES/django.po
  hypha/locale/es/LC_MESSAGES/django.po
  hypha/locale/fr/LC_MESSAGES/django.po
  hypha/locale/ru/LC_MESSAGES/django.po
  hypha/locale/zh_Hans/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4533 Render richtext help text on login pages.
  hypha/apply/users/admin_views.py
  hypha/apply/users/forms.py
  hypha/apply/users/templates/users/login.html
  hypha/apply/users/templates/users/passwordless_login_signup.html
Labels: Type: Bug, Type: Patch

#4539 Translations update from Hosted Weblate
  hypha/locale/cs/LC_MESSAGES/django.po
Labels: Type: Maintenance, Type: Patch

#4540 Added `ssl_check_hostname` query param for redis 6.0
  hypha/settings/base.py
Labels: Type: Bug, Type: Patch

#4538 Add sentry profiling options.
  hypha/settings/base.py
Labels: Type: Maintenance, Type: Patch

#4541 Fix fund & round getting put together for applicants
  hypha/apply/projects/templates/application_projects/includes/project_header.html
Labels: Type: Bug, Type: Patch

#4550 Remove added comment that made review comparisons always show up
  hypha/apply/review/templates/review/review_detail.html
Labels: Type: Bug, Type: Patch

#4492 Add Co-applicants feature to submissions
  hypha/apply/activity/adapters/base.py
  hypha/apply/activity/adapters/emails.py
  hypha/apply/activity/migrations/0087_alter_event_type.py
  hypha/apply/activity/options.py
  hypha/apply/activity/templates/messages/email/invite_co_applicant.html
  hypha/apply/activity/templatetags/activity_tags.py
  hypha/apply/dashboard/views.py
  hypha/apply/dashboard/views_partials.py
  hypha/apply/determinations/views.py
  hypha/apply/funds/forms.py
  hypha/apply/funds/migrations/0125_coapplicantinvite_coapplicant.py
  hypha/apply/funds/models/__init__.py
  hypha/apply/funds/models/co_applicants.py
  hypha/apply/funds/permissions.py
  hypha/apply/funds/templates/funds/applicationsubmission_detail.html
  hypha/apply/funds/templates/funds/coapplicant_invite_landing_page.html
  hypha/apply/funds/templates/funds/comments.html
  hypha/apply/funds/templates/funds/includes/co-applicant-block.html
  hypha/apply/funds/templates/funds/modals/edit_co_applicant_form.html
  hypha/apply/funds/templates/funds/modals/invite_co_applicant_form.html
  hypha/apply/funds/templatetags/primaryactions_tags.py
  hypha/apply/funds/templatetags/workflow_tags.py
  hypha/apply/funds/urls.py
  hypha/apply/funds/utils.py
  hypha/apply/funds/views/co_applicants.py
  hypha/apply/funds/views/comments.py
  hypha/apply/funds/views/submission_detail.py
  hypha/apply/funds/views/submission_edit.py
  hypha/apply/users/tokens.py
  hypha/settings/base.py
  hypha/templates/base-apply.html
Labels: Type: Feature, Type: Minor

#4549 Better error handling for dates, added submitted filter criteria
  hypha/apply/funds/templates/submissions/all.html
  hypha/apply/search/filters.py
  hypha/apply/search/query_parser.py
  hypha/apply/search/tests/test_filters.py
Labels: Type: Enhancement, Type: Patch

#4546 Add max length option on Titleblocks that sets maxlength attribute.
  hypha/apply/funds/blocks.py
  hypha/apply/funds/migrations/0126_add_max_length.py
  hypha/apply/templates/forms/includes/field.html
Labels: Type: Enhancement, Type: Patch

#4551 E-mail template whitespace improvements
  hypha/apply/activity/templates/messages/email/base.html
  hypha/apply/activity/templates/messages/email/invite_co_applicant.html
  hypha/apply/users/templates/users/email_change/update_info_email.html
Labels: Type: Enhancement, Type: Patch

#4553 Fix co-applicant invite not found issue
  hypha/apply/funds/views/co_applicants.py
Labels: Type: Bug, Type: Patch
